// ═══════════════════════════════════════════════════════════
// CONTENT "newspaper/environment/26_07_2026/rice-methane" — Auto-generated by build-bundle.js. DO NOT EDIT.
// Mirrors the source notes file js/data/newspaper/environment/26_07_2026/rice-methane.js. Loaded on demand
// by js/engine/loader.js the first time one of its topics is opened.
// Edit the source under js/data/ and re-run: node build-bundle.js
// ═══════════════════════════════════════════════════════════
__registerContent("newspaper/environment/26_07_2026/rice-methane", {
  notes: {
    "news-2026-07-26-rice-methane": {
      era: "Environment / GS-3",
      significance: [
        "GHG emissions from paddy fields worldwide have nearly doubled since the 1960s (up 90.4%), producing 1.1 billion tonnes of CO₂-equivalent annually in 2011-2020. India's irrigated paddy fields alone release 3.9 million tonnes of methane per year — slightly more than Germany's entire annual methane emissions. The study, published in Nature Food, integrates over 1,200 field experiments, process-based ecosystem modelling, and AI approaches.",
      ],
      features: [
        {
          key: "Scale of the Problem",
          main: "i) Global GHG emissions from paddy fields: ~1.1 billion tonnes CO₂-equivalent/year (2011-2020), up 90.4% from 1961-80 \nii) India: world's top rice producer; paddy cultivation covers 55% of India's rainfed harvested area \niii) Paddy area under cultivation increased ~25% since the 1970s \niv) Paddy fields in eastern India were among the global methane hotspots",
          note: "",
        },
        {
          key: "Why Paddy Fields Emit So Much Methane",
          main: "i) Flooded fields → low-oxygen (anaerobic) conditions → methane-producing microbes (methanogens) thrive \nii) ~50% of the increase stems from LOSS OF SOIL ORGANIC CARBON in paddy fields worldwide \niii) Continuous irrigation (fields kept flooded) → sustained anaerobic conditions \niv) Incorporation of crop residues (leftover stalks, leaves, stubble) → additional carbon decomposed into methane \nv) Increasing use of nitrogen fertilizers → amplified emissions",
          note: "",
        },
        {
          key: "Mitigation Options",
          main: "i) System of Rice Intensification (SRI): young seedlings transplanted precisely; fields NOT continuously flooded → reduces emissions \nii) Alternate Wetting and Drying (AWD): fields dried periodically — cuts methane significantly \niii) Better irrigation + residue management could reduce global rice-related GHG by ~10% by 2050 \niv) NICRA (National Innovations in Climate Resilient Agriculture): GOI project suggesting improved techniques \nv) Replacing lime with phosphogypsum in acidic soils: reduces subsoil emissions (Kerala experiment) \nvi) Crop diversification + limiting paddy expansion: essential to meet regional environmental and climate goals",
          note: "",
        },
        {
          key: "Barriers to Adoption",
          main: "i) Labour shortages in rural India \nii) Lack of technical knowledge among farmers \niii) Changes in rainfall patterns affecting technique applicability \niv) Region-specific soil, topography, irrigation conditions mean no one-size solution",
          note: "",
        },
        {
          key: "Key Schemes and Institutions",
          main: "i) NICRA (National Innovations in Climate Resilient Agriculture): Central Government scheme under ICAR; develops climate-resilient technologies for Indian agriculture \nii) ICAR-International Rice Research Institute (IRRI): co-developing low-emission rice systems in Kerala (KERA-AWD project) \niii) Swachh crop diversification push: no way forward without crop diversification per experts",
          note: "",
        },
        {
          key: "Cross-links to Other Subjects",
          main: "i) GS-1 Geography: Paddy cultivation patterns, Kharif crops, eastern India agriculture \nii) GS-2 Governance: NICRA as a Central Government scheme under ICAR; agriculture extension services \niii) GS-3 Agriculture: Rice-wheat cropping system, stubble burning, soil organic carbon, SRI technique \niv) GS-3 Environment: Greenhouse gas inventory, methane vs CO₂ global warming potential (GWP-28 over 100 years), India's NDC commitments \nv) Essay: 'India's food security and environmental sustainability — can they coexist?'",
          note: "",
        },
        {
          key: "Methane (CH₄)",
          main: "A greenhouse gas 28 times more potent than CO₂ over 100 years (GWP-100 = 28). In the short term (20 years), its GWP is ~84. Methane from paddy fields is produced by methanogenic archaea under anaerobic (flooded) conditions. While it dissipates from the atmosphere faster than CO₂ (~12 years vs centuries), its near-term warming impact is severe.",
          note: "",
        },
        {
          key: "System of Rice Intensification (SRI)",
          main: "An agronomic approach developed in Madagascar (1980s) by Fr. Henri de Laulanié. Core principles: young seedlings transplanted individually in rows, reduced plant density, intermittent irrigation (not continuous flooding), mechanical weeding, and organic matter application. Benefits: higher yields, 25-50% less water, and significantly lower methane emissions. India's ICAR promotes SRI under NICRA.",
          note: "",
        },
        {
          key: "Alternate Wetting and Drying (AWD)",
          main: "An irrigation technique where paddy fields are periodically dried (allowed to dry for a few days between irrigations) rather than kept continuously flooded. Reduces methane emissions by 30-40% while maintaining yields. Promoted by IRRI and the Government of India under schemes like KERA-AWD in Kerala.",
          note: "",
        },
        {
          key: "NICRA (National Innovations in Climate Resilient Agriculture)",
          main: "A Central Government network project under ICAR launched in February 2011. Aims to enhance resilience of Indian agriculture to climate change and climate variability through strategic research and technology development. Operates through 151 Krishi Vigyan Kendras. Budget: over ₹350 crore since inception. Develops region-specific climate-resilient technologies including SRI and AWD for rice.",
          note: "",
        },
        {
          key: "Soil Organic Carbon (SOC)",
          main: "The carbon stored in soil as organic matter (plant residues, animal waste, microbial biomass, humus). When SOC is lost (due to flooding, excessive tillage, or monocultures), it decomposes and releases CO₂ and methane. Maintaining high SOC is critical for both agricultural productivity and climate mitigation. The study found ~50% of methane increase from rice came from SOC loss.",
          note: "",
        },
      ],
      mainsAngle: [
        "Rice paddies and methane — India's dilemma: As the world's largest rice producer, India faces a classic food-environment trade-off. Paddy cultivation covers 55% of India's rainfed harvested area, providing food security for over a billion people. Yet its paddy fields are among the world's top methane hotspots, contributing emissions equivalent to Germany's entire annual methane output.",
        "The root cause is structural: continuous flooding creates anaerobic conditions ideal for methanogens, while incorporation of crop residues and nitrogen fertilizers amplifies this. About half the global increase in paddy methane since the 1960s stems from soil organic carbon loss — highlighting that unsustainable soil management, not merely rice cultivation per se, is the driver.",
        "Mitigation is technically available (SRI, AWD, reduced tillage) but adoption is constrained by labour shortages, poor extension services, and region-specific barriers. The NICRA framework and IRRI partnerships provide a policy architecture, but field-level implementation remains limited.",
        "The critical policy insight: no way forward without crop diversification. India cannot meet its NDC commitments while continuing to expand paddy cultivation without simultaneously investing in alternative cereals, strengthening extension services, and reforming MSP structures that currently incentivise rice over more climate-friendly crops like millets.",
      ],
      traps: [
        "Methane's GWP is 28 over 100 years (GWP-100) but ~84 over 20 years (GWP-20) — don't confuse the two timeframes.",
        "Methane is produced by methanogenic archaea, NOT bacteria, under anaerobic conditions — a common MCQ distractor.",
        "NICRA is under ICAR (Ministry of Agriculture), NOT under the Ministry of Environment or NITI Aayog.",
        "SRI was developed in Madagascar (1980s), not in India — India promotes it, but did not originate it.",
        "About 50% of the increase in paddy methane comes from soil organic carbon LOSS, not directly from fertilizers — fertilizers amplify emissions but are not the primary driver.",
        "AWD reduces methane by ~30-40%; the projected global rice GHG cut by 2050 (~10%) is a separate figure — don't mix them up.",
      ],
      recall: [
        "Methane GWP-100 = 28 (28 times more potent than CO₂ over 100 years)",
        "Paddy fields cover 55% of India's rainfed harvested area",
        "India's paddy fields emit ~3.9 million tonnes methane/year (> Germany's total annual methane emissions)",
        "NICRA: Central scheme under ICAR; launched February 2011",
        "SRI (System of Rice Intensification): developed in Madagascar; young seedlings + intermittent irrigation",
        "AWD (Alternate Wetting and Drying): reduces methane 30-40%; promoted by IRRI",
        "Global paddy emissions up 90.4% from 1961-80 to 2011-20",
        "~50% of increase = loss of soil organic carbon in paddy fields",
      ],
    },
  },
  quizzes: {
    "news-2026-07-26-rice-methane": {
      title: "Rice Fields & Methane (26 Jul 2026)",
      questions: [
        {
          q: "According to the Nature Food study, GHG emissions from paddy fields worldwide during 2011-2020 were up by how much compared to 1961-1980?",
          options: ["45%", "70%", "90.4%", "120%"],
          correct: 2,
          explain:
            "GHG emissions from paddy fields increased by 90.4% from the 1961-1980 baseline to 2011-2020, producing ~1.1 billion tonnes CO₂-equivalent annually.",
        },
        {
          q: "What makes paddy fields such significant sources of methane?",
          options: [
            "High use of pesticides that chemically produce methane",
            "Flooded conditions create low-oxygen environments where methane-producing microbes thrive",
            "Rice plants themselves directly release methane during photosynthesis",
            "Nitrogen from fertilizers combines with water to form methane",
          ],
          correct: 1,
          explain:
            "Flooded paddy fields create anaerobic (low-oxygen) conditions where methanogenic microbes thrive and produce methane. About 50% of the increase also stems from loss of soil organic carbon.",
        },
        {
          q: "Approximately how much methane do India's irrigated paddy fields release annually?",
          options: [
            "1.1 million tonnes",
            "3.9 million tonnes",
            "7.5 million tonnes",
            "12 million tonnes",
          ],
          correct: 1,
          explain:
            "India's irrigated paddy fields release about 3.9 million tonnes of methane per year — slightly more than Germany's entire annual methane emissions.",
        },
        {
          q: "The System of Rice Intensification (SRI) reduces methane emissions primarily by:",
          options: [
            "Using genetically modified rice varieties that produce less carbon",
            "Transplanting young seedlings precisely and NOT continuously flooding the fields",
            "Adding methane-absorbing chemicals to paddy water",
            "Eliminating the use of nitrogen fertilizers entirely",
          ],
          correct: 1,
          explain:
            "SRI involves precise transplanting of young seedlings and uses intermittent (not continuous) irrigation — keeping fields periodically dry prevents sustained anaerobic conditions, thereby reducing methane production.",
        },
        {
          q: "NICRA, the National Innovations in Climate Resilient Agriculture, is a scheme under:",
          options: [
            "Ministry of Environment, Forest and Climate Change",
            "NITI Aayog",
            "ICAR (Indian Council of Agricultural Research)",
            "Ministry of Water Resources",
          ],
          correct: 2,
          explain:
            "NICRA is a Central Government network project under ICAR (Indian Council of Agricultural Research), launched in February 2011 to enhance resilience of Indian agriculture to climate change.",
        },
        {
          q: "Assertion (A): India faces a structural conflict between food security and climate commitments in the rice sector.\nReason (R): Paddy cultivation covers 55% of India's rainfed harvested area, making it central to food security, while being one of the world's largest methane sources.\nWhich one of the following is correct?",
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R correctly explains A — the same crop that underpins food security (covering 55% of rainfed harvested area) is simultaneously a leading methane source, creating a genuine structural conflict.",
        },
        {
          q: "Alternate Wetting and Drying (AWD) as an irrigation technique for rice:",
          options: [
            "Keeps fields continuously flooded to maintain soil moisture",
            "Periodically dries the fields between irrigations, reducing methane emissions by 30-40%",
            "Uses saltwater irrigation to suppress methane-producing bacteria",
            "Combines chemical treatment of water with drip irrigation",
          ],
          correct: 1,
          explain:
            "AWD involves periodically drying paddy fields (allowing them to dry for a few days between irrigations). This disrupts continuous anaerobic conditions, reducing methane emissions by 30-40% while maintaining yields.",
        },
        {
          q: "The study projects that better irrigation and residue management could reduce global rice-related GHG emissions by what percentage by 2050?",
          options: ["5%", "10%", "25%", "50%"],
          correct: 1,
          explain:
            "The study projects that a combination of improved irrigation, optimised fertiliser use, residue management, and reduced tillage could reduce global rice-related GHG emissions by about 10% by mid-century.",
        },
        {
          q: "The methane global warming potential (GWP) over 100 years compared to CO₂ is:",
          options: ["5 times", "12 times", "28 times", "84 times"],
          correct: 2,
          explain:
            "Methane has a GWP-100 of 28 — meaning it is 28 times more potent than CO₂ as a greenhouse gas over a 100-year period. Its GWP-20 (20-year timeframe) is ~84, making its short-term impact even more severe.",
        },
        {
          q: "Which of the following is identified as a key structural barrier to adopting low-emission rice cultivation techniques in India?",
          options: [
            "Lack of scientific evidence for the techniques' effectiveness",
            "Constitutional restrictions on agricultural technology adoption",
            "Labour shortages, lack of technical knowledge, and changing rainfall patterns",
            "International trade agreements preventing technology transfer",
          ],
          correct: 2,
          explain:
            "Farmers remain reluctant to adopt alternative techniques due to labour shortages, lack of technical knowledge, and changes in rainfall patterns — these are the structural barriers identified in the article.",
        },
        {
          q: "Methane in flooded paddy fields is produced primarily by:",
          options: [
            "Methanogenic archaea under anaerobic (low-oxygen) conditions",
            "Aerobic bacteria in the presence of oxygen",
            "The rice plant during photosynthesis",
            "Chemical reaction of urea with water",
          ],
          correct: 0,
          explain:
            "Methane is generated by methanogenic archaea (microbes) that thrive in the anaerobic, low-oxygen conditions of continuously flooded fields — not by aerobic bacteria or photosynthesis.",
        },
        {
          q: [
            "Consider the following statements about NICRA:",
            "I. It was launched in February 2011.",
            "II. It is a network project of the Indian Council of Agricultural Research (ICAR).",
            "Which of the statements given above is/are correct?",
          ],
          options: ["I only", "II only", "Both I and II", "Neither I nor II"],
          correct: 2,
          explain:
            "Both are correct. NICRA (National Innovations in Climate Resilient Agriculture) was launched in February 2011 as a network project under ICAR.",
        },
        {
          q: "The global warming potential of methane over a 20-year horizon (GWP-20) is approximately:",
          options: [
            "28 times CO₂",
            "50 times CO₂",
            "84 times CO₂",
            "120 times CO₂",
          ],
          correct: 2,
          explain:
            "Methane's GWP-20 is about 84 (versus 28 for GWP-100), which is why its near-term climate impact is far more severe than its 100-year figure suggests.",
        },
        {
          q: [
            "Consider the following as drivers of the rise in paddy-field GHG emissions:",
            "I. Continuous flooding creating anaerobic conditions",
            "II. Loss of soil organic carbon",
            "III. Increased fertiliser use",
            "How many of the above are identified as contributing factors?",
          ],
          options: ["Only one", "Only two", "All three", "None"],
          correct: 2,
          explain:
            "All three contribute. Anaerobic flooding drives methane generation, about 50% of the increase stems from soil organic carbon loss, and fertiliser use amplifies emissions.",
        },
        {
          q: "Which of the following practices would NOT help reduce methane emissions from rice cultivation?",
          options: [
            "Alternate Wetting and Drying (AWD)",
            "System of Rice Intensification (SRI)",
            "Continuous flooding of fields throughout the season",
            "Improved residue management and reduced tillage",
          ],
          correct: 2,
          explain:
            "Continuous flooding sustains the anaerobic conditions that maximise methane production — it is the problem, not a solution. AWD, SRI, and better residue/tillage management all reduce emissions.",
        },
        {
          q: [
            "Consider the following statements:",
            "I. India's irrigated paddy fields release about 3.9 million tonnes of methane annually.",
            "II. This is slightly more than Germany's entire annual methane emissions.",
            "III. Paddy cultivation covers about 55% of India's rainfed harvested area.",
            "Which of the statements given above are correct?",
          ],
          options: [
            "I and II only",
            "II and III only",
            "I and III only",
            "I, II and III",
          ],
          correct: 3,
          explain:
            "All three are correct — these figures underline why rice sits at the intersection of India's food security and climate challenge.",
        },
        {
          q: "According to the Nature Food study, annual GHG emissions from paddy fields worldwide amount to approximately:",
          options: [
            "0.3 billion tonnes CO₂-equivalent",
            "1.1 billion tonnes CO₂-equivalent",
            "3.5 billion tonnes CO₂-equivalent",
            "5.0 billion tonnes CO₂-equivalent",
          ],
          correct: 1,
          explain:
            "The study estimated about 1.1 billion tonnes of CO₂-equivalent per year from paddy fields (after a 90.4% rise from the 1961-1980 baseline).",
        },
        {
          q: [
            "Match the technique with its description:",
            "I. SRI — a) periodically drying fields between irrigations",
            "II. AWD — b) transplanting young seedlings with intermittent (non-continuous) irrigation",
            "Select the correct answer:",
          ],
          options: [
            "I-a, II-b",
            "I-b, II-a",
            "Both I and II describe continuous flooding",
            "Neither can be matched",
          ],
          correct: 1,
          explain:
            "SRI (I) centres on precise transplanting of young seedlings with intermittent irrigation (b); AWD (II) specifically alternates wetting and drying of fields (a). Both avoid continuous flooding.",
        },
        {
          q: "Which best explains why intermittent irrigation reduces methane from paddy?",
          options: [
            "Drier spells introduce oxygen, disrupting the anaerobic conditions methanogens need",
            "It kills the rice plant's roots that emit methane",
            "It dissolves methane into the irrigation water",
            "It chemically neutralises methane with nitrogen",
          ],
          correct: 0,
          explain:
            "Periodic drying aerates the soil, breaking the sustained anaerobic (oxygen-poor) conditions that methane-producing archaea require — thereby cutting emissions.",
        },
        {
          q: "The projected ~10% cut in global rice-related GHG emissions by 2050 is expected to come from a combination of:",
          options: [
            "Banning rice cultivation in tropical countries",
            "Improved irrigation, optimised fertiliser use, residue management and reduced tillage",
            "Switching entirely to genetically modified rice",
            "Importing rice instead of growing it domestically",
          ],
          correct: 1,
          explain:
            "The study attributes the potential ~10% reduction to a package of measures: better irrigation (AWD/SRI), optimised fertiliser use, residue management and reduced tillage.",
        },
      ],
    },
  },
});
