// ═══════════════════════════════════════════════════════════
// CONTENT "gs1/geography/ncert/class7/ch5/ch5" — Auto-generated by build-bundle.js. DO NOT EDIT.
// Mirrors the source notes file js/data/gs1/geography/ncert/class7/ch5/ch5.js. Loaded on demand
// by js/engine/loader.js the first time one of its topics is opened.
// Edit the source under js/data/ and re-run: node build-bundle.js
// ═══════════════════════════════════════════════════════════
__registerContent("gs1/geography/ncert/class7/ch5/ch5", {
  notes: {
    "geo7-ch5": {
      era: "NCERT Class 7 — Geography (Our Environment), Chapter 5",
      significance: [
        "Water cycle, distribution of water bodies, salinity, and ocean movements (waves, tides, currents) are directly testable Prelims facts",
        "Tsunami 2004 case study with exact figures (magnitude 9.0, epicentre near Sumatra, Indira Point submerged) is a high-value static fact",
        "Spring tide vs neap tide mechanism, Labrador vs Gulf Stream distinction, and World Water Day (22 March) are individually tested",
      ],
      features: [
        {
          key: "Water Cycle",
          main: "The process by which water continually changes its form and circulates between oceans, atmosphere and land\nEvaporation → Water vapour rises → Cools → Condenses → Forms clouds → Precipitation (rain, snow, sleet) → Flows back to water bodies\nThe Earth is like a terrarium — the same water has existed for centuries (e.g. the same water that existed in Haryana field centuries ago may have flowed down the Amazon River)",
          note: "",
        },
        {
          key: "Distribution of Water",
          main: "Three-fourths (75%) of Earth's surface = covered by water\nOceans: 97.3% (saline) — unfit for human use\nFreshwater: 2.7% total\nIce caps: 2.0%; Ground water: 0.68%; Fresh water lakes: 0.009%; Inland seas and salt lakes: 0.009%; Atmosphere: 0.0019%; Rivers: 0.0001%",
          note: "Average salinity of oceans = 35 parts per thousand\nDead Sea (Israel) has salinity of 340 grams per litre — swimmers can float in it",
        },
        {
          key: "Salinity",
          main: "Salinity = the amount of salt present in grams in 1,000 grams of water\nAverage salinity of oceans = 35 parts per thousand\nMost of the salt is sodium chloride — common table salt\nDead Sea has salinity of 340 g/litre — swimmers can float because increased salt content makes water dense",
          note: "",
        },
        {
          key: "World Water Day",
          main: "Celebrated on 22 March — when the need to conserve water is reinforced",
          note: "",
        },
        {
          key: "Ocean Circulation — Three Types",
          main: "Movements in oceans broadly categorised as: Waves, Tides, and Ocean Currents",
          note: "",
        },
        {
          key: "Waves",
          main: "When water on the ocean surface rises and falls alternately = waves\nWaves are formed when winds scrape across the ocean surface\nThe stronger the wind, the bigger the wave\nDuring a storm, winds at very high speed form huge waves — may cause tremendous destruction",
          note: "",
        },
        {
          key: "Tsunami",
          main: "Huge tidal waves caused by an earthquake, volcanic eruption or underwater landslides\nTsunami = Japanese word meaning 'Harbour waves'\nMay be as high as 15 m; largest ever measured = 150 m\nTravel speed = more than 700 km per hour\nFirst indication of tsunami approaching = rapid withdrawal of water from coastal region",
          note: "",
        },
        {
          key: "Tsunami 2004 — Case Study",
          main: "Date: 26 December 2004; Indian Ocean\nEpicentre: close to western boundary of Sumatra\nMagnitude: 9.0 on the Richter Scale\nCause: Indian plate went under Burma plate → sudden movement of sea floor → ocean floor displaced by 10–20 m\nWaves travelled at ~800 km/hr (comparable to commercial aircraft)\nIndira Point (Andaman & Nicobar Islands) — southernmost point of India — got completely submerged\nMore than 10,000 people killed; more than lakh houses affected in India\nWorst affected in India: coastal areas of Andhra Pradesh, Tamil Nadu, Kerala, Puducherry, Andaman & Nicobar Islands\nTsunami of 2004 = most devastating tsunami in last several hundred years\nTsunami warning: early warning systems exist across the Pacific but NOT in the Indian Ocean (at the time)",
          note: "",
        },
        {
          key: "Tides",
          main: "Rhythmic rise and fall of ocean water twice in a day = tide\nHigh tide: water covers much of the shore by rising to its highest level\nLow tide: water falls to its lowest level and recedes from the shore\nCause: strong gravitational pull of sun and moon on Earth's surface",
          note: "",
        },
        {
          key: "Spring Tides",
          main: "During full moon and new moon days, Sun, Moon and Earth are in a straight line\nTides are highest = called SPRING TIDES",
          note: "",
        },
        {
          key: "Neap Tides",
          main: "When the Moon is in its first and last quarter (at right angles to Sun-Earth line)\nOcean waters are pulled in diagonally opposite directions by gravitational pull of Sun and Moon\nResult in LOW tides = called NEAP TIDES",
          note: "",
        },
        {
          key: "Uses of Tides",
          main: "High tides help in navigation — raise water level close to shores, helping ships arrive at harbour easily\nHigh tides help in fishing — more fish come closer to shore\nTidal energy used to generate electricity in some places",
          note: "",
        },
        {
          key: "Ocean Currents",
          main: "Streams of water flowing constantly on the ocean surface in definite directions = ocean currents\nWarm currents: originate near the equator and move towards the poles; bring warm temperature over land surface\nCold currents: carry water from polar or higher latitudes to tropical/lower latitudes\nExample: Labrador Ocean current = COLD current; Gulf Stream = WARM current\nWarm and cold currents meeting: provide best fishing grounds (e.g. around Japan, eastern coast of North America)\nMeeting areas also have foggy weather — difficult for navigation",
          note: "",
        },
      ],
      traps: [
        {
          label: "Water Distribution — Exact Percentages",
          lines: [
            "Oceans: 97.3% (saline); Total fresh water: 2.7%",
            "Ice caps: 2.0% (largest fresh water source); Groundwater: 0.68%",
            "Rivers only: 0.0001% — the tiniest fraction",
            "Common trap: assuming most fresh water is in rivers — most is locked in ice caps",
          ],
        },
        {
          label: "Spring Tide vs Neap Tide",
          lines: [
            "SPRING TIDE: Full moon/New moon → Sun, Moon, Earth in STRAIGHT LINE → HIGHEST tides",
            "NEAP TIDE: First/Last quarter of Moon → Moon at right angles → LOWEST tides",
            "Common trap: thinking spring tides occur only in spring season — they occur on full moon AND new moon days",
          ],
        },
        {
          label: "Labrador vs Gulf Stream",
          lines: [
            "Labrador = COLD current",
            "Gulf Stream = WARM current",
            "Warm currents originate near equator; cold currents from poles",
          ],
        },
        {
          label: "Tsunami 2004 Key Facts",
          lines: [
            "Date: 26 December 2004",
            "Magnitude: 9.0 on Richter Scale",
            "Epicentre: near western boundary of Sumatra (Burma plate zone)",
            "Indira Point (southernmost point of India) submerged",
            "Travel speed: ~800 km/hr",
            "No early warning system in Indian Ocean at the time",
          ],
        },
        {
          label: "World Water Day",
          lines: [
            "World Water Day: 22 March",
            "NOT to be confused with World Environment Day (5 June) or Earth Day (22 April)",
          ],
        },
        {
          label: "Dead Sea — Salinity",
          lines: [
            "Dead Sea (Israel): salinity = 340 grams per litre",
            "Average ocean salinity = 35 parts per thousand",
            "Dead Sea is about 10 times saltier than regular oceans",
          ],
        },
      ],
      mainsAngle:
        "Chapter 5 connects directly to multiple GS-3 themes: the tsunami 2004 case study (Disaster Management, early warning systems), ocean currents and fishing grounds (international waters, fisheries policy), and water scarcity despite Earth being 75% covered by water (water conservation, virtual water). World Water Day (22 March) is also directly relevant to environmental awareness questions.",
      mainsTheme:
        "Water cycle, ocean dynamics, tsunami preparedness, and water scarcity — foundational for GS-3 environment and disaster management",
      recall: [
        "Water cycle: evaporation → vapour → condensation → clouds → precipitation → runoff",
        "Ocean water: 97.3%; Ice caps: 2.0%; Groundwater: 0.68%; Rivers: 0.0001%",
        "Average ocean salinity: 35 parts per thousand; Dead Sea: 340 g/litre",
        "World Water Day: 22 March",
        "3 ocean movements: Waves, Tides, Ocean Currents",
        "Tsunami = Japanese = 'Harbour waves'; caused by underwater earthquake/eruption/landslide",
        "Tsunami 2004: 26 Dec 2004; 9.0 Richter; Sumatra epicentre; Indira Point submerged",
        "Spring tide: full/new moon → sun-moon-earth straight → highest tides",
        "Neap tide: first/last quarter moon → right angles → lowest tides",
        "Ocean currents: warm (from equator) vs cold (from poles)",
        "Labrador = cold current; Gulf Stream = warm current",
        "Warm + cold currents meeting = best fishing grounds + foggy weather",
      ],
    },
  },
  quizzes: {
    "geo7-ch5": {
      title: "Water",
      questions: [
        {
          q: "The water cycle is best defined as:",
          options: [
            "The process by which rivers flow into oceans",
            "The process by which water continually changes its form and circulates between oceans, atmosphere and land",
            "The process of water purification in treatment plants",
            "The movement of groundwater to the surface",
          ],
          correct: 1,
          explain:
            "The water cycle is the continuous process by which water changes form (liquid → vapour → clouds → precipitation) and circulates between oceans, atmosphere and land.",
        },
        {
          q: [
            "Consider the following pairs (Water source — Percentage of total water):",
            "I. Oceans — 97.3% (saline)",
            "II. Ice caps — 2.0%",
            "III. Rivers — 0.68%",
            "How many of the above pairs are correctly matched?",
          ],
          options: [
            "Only one pair",
            "Only two pairs",
            "All three pairs",
            "None of the pairs",
          ],
          correct: 1,
          explain:
            "Pairs I and II are correctly matched. Pair III is incorrect — Rivers contain only 0.0001% of total water. 0.68% is the figure for groundwater.",
        },
        {
          q: "The average salinity of the oceans is approximately:",
          options: [
            "10 parts per thousand",
            "25 parts per thousand",
            "35 parts per thousand",
            "340 parts per thousand",
          ],
          correct: 2,
          explain:
            "The average salinity of the oceans is 35 parts per thousand — meaning 35 grams of salt per 1,000 grams of water.",
        },
        {
          q: "The Dead Sea has a salinity of 340 grams per litre. Swimmers can float in the Dead Sea because:",
          options: [
            "The Dead Sea has no waves",
            "The water is extremely cold and dense",
            "The high salt content makes the water denser, providing greater buoyancy",
            "The Dead Sea is very shallow",
          ],
          correct: 2,
          explain:
            "The Dead Sea's extraordinary salinity (340 g/litre vs ocean average of 35 parts per thousand) makes the water much denser than the human body — providing enough buoyancy for people to float effortlessly.",
        },
        {
          q: "World Water Day is celebrated on:",
          options: ["5 June", "22 April", "22 March", "21 March"],
          correct: 2,
          explain:
            "World Water Day is celebrated on 22 March, when the need to conserve water is reinforced in different ways.",
        },
        {
          q: "The three broad categories of movements that occur in oceans are:",
          options: [
            "Rainfall, tides, and evaporation",
            "Waves, tides, and ocean currents",
            "Rivers, waves, and precipitation",
            "Currents, precipitation, and floods",
          ],
          correct: 1,
          explain:
            "The movements that occur in oceans are broadly categorised as waves, tides, and ocean currents.",
        },
        {
          q: "Waves are formed when:",
          options: [
            "The gravitational pull of the moon acts on the ocean",
            "Winds scrape across the ocean surface",
            "Ocean currents meet at the equator",
            "The ocean floor shifts due to earthquakes",
          ],
          correct: 1,
          explain:
            "Waves are formed when winds scrape across the ocean surface — the stronger the wind, the bigger the wave.",
        },
        {
          q: "The word 'Tsunami' is a Japanese word that means:",
          options: [
            "Killer wave",
            "Harbour waves",
            "Giant ocean",
            "Wall of water",
          ],
          correct: 1,
          explain:
            "Tsunami is a Japanese word meaning 'Harbour waves' — because harbours get destroyed whenever there is a tsunami.",
        },
        {
          q: "The 2004 Tsunami in the Indian Ocean was triggered by:",
          options: [
            "A volcanic eruption in Indonesia",
            "An earthquake of magnitude 9.0 near the western boundary of Sumatra, as the Indian plate went under the Burma plate",
            "A massive underwater landslide near Sri Lanka",
            "An unusually strong cyclone in the Bay of Bengal",
          ],
          correct: 1,
          explain:
            "The 2004 Tsunami was caused by a magnitude 9.0 earthquake near the western boundary of Sumatra — the Indian plate went under the Burma plate causing a sudden movement of the sea floor.",
        },
        {
          q: [
            "Assertion (A): The 2004 Indian Ocean Tsunami caused the Indira Point in the Andaman and Nicobar Islands to get completely submerged.",
            "Reason (R): The Indira Point is the southernmost point of India — its low elevation and proximity to the epicentre made it especially vulnerable to submergence.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both A and R are true and R correctly explains A — Indira Point's status as the southernmost (and low-lying) point of India, close to the epicentre of the Sumatra earthquake, made its submergence a direct consequence.",
        },
        {
          q: "The tsunami of December 2004 travelled at approximately what speed?",
          options: [
            "200 km per hour",
            "400 km per hour",
            "800 km per hour",
            "1,500 km per hour",
          ],
          correct: 2,
          explain:
            "The 2004 tsunami travelled at a speed of about 800 km per hour — comparable to the speed of a commercial aircraft.",
        },
        {
          q: "The first indication that a tsunami is approaching a coastal area is:",
          options: [
            "Extreme darkness covering the coastal region",
            "A very loud underwater sound",
            "Rapid withdrawal of water from the coastal region",
            "Strong winds blowing inland",
          ],
          correct: 2,
          explain:
            "The first indication of an approaching tsunami is the rapid WITHDRAWAL of water from the coastal region — creating a false impression that the sea is receding. People who go to the shore to view this phenomenon are in extreme danger when the wave strikes.",
        },
        {
          q: "Tides are defined as:",
          options: [
            "Streams of water flowing in definite directions on the ocean surface",
            "The rhythmic rise and fall of ocean water twice in a day",
            "Large ocean waves caused by underwater earthquakes",
            "The movement of air from high pressure to low pressure areas",
          ],
          correct: 1,
          explain:
            "Tides are the rhythmic rise and fall of ocean water twice in a day, caused by the gravitational pull of the sun and moon.",
        },
        {
          q: "Spring tides occur when:",
          options: [
            "The moon is in its first or last quarter (at right angles to Sun-Earth)",
            "The season of spring begins in the Northern Hemisphere",
            "The Sun, Moon and Earth are in a straight line during full moon and new moon",
            "Ocean currents warm the coastal waters",
          ],
          correct: 2,
          explain:
            "Spring tides occur on FULL MOON and NEW MOON days when the Sun, Moon, and Earth are in a straight line — gravitational pull is combined, producing the highest tides. They are NOT seasonal — they occur twice a month.",
        },
        {
          q: "Neap tides occur when:",
          options: [
            "The Sun, Moon and Earth are aligned in a straight line",
            "The Moon is in its first or last quarter (Moon at right angles to the Sun-Earth line), resulting in low tides",
            "Ocean currents are at their strongest",
            "There is a solar eclipse",
          ],
          correct: 1,
          explain:
            "Neap tides occur when the Moon is in its first or last quarter — its gravitational pull and the Sun's pull act in different (diagonally opposite) directions, resulting in LOW tides.",
        },
        {
          q: [
            "High tides are useful because:",
            "I. They help ships navigate by raising water levels close to shores.",
            "II. They bring more fish closer to shore, helping fishermen.",
            "III. They are used to generate electricity in some places.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I and II only",
            "II and III only",
            "I, II and III",
            "I only",
          ],
          correct: 2,
          explain:
            "All three statements are correct — high tides aid navigation, help fishermen, and can be used to generate tidal energy.",
        },
        {
          q: "Ocean currents are best described as:",
          options: [
            "The rise and fall of ocean water due to gravitational pull",
            "Streams of water flowing constantly on the ocean surface in definite directions",
            "Wind-generated waves on the ocean surface",
            "The movement of cold and warm air over the ocean",
          ],
          correct: 1,
          explain:
            "Ocean currents are streams of water flowing constantly on the ocean surface in definite directions — they may be warm or cold.",
        },
        {
          q: [
            "Consider the following pairs (Ocean current — Type):",
            "I. Labrador current — Cold current",
            "II. Gulf Stream — Warm current",
            "How many of the above pairs are correctly matched?",
          ],
          options: [
            "Only one pair",
            "Both pairs",
            "Neither pair",
            "Cannot be determined",
          ],
          correct: 1,
          explain:
            "Both pairs are correctly matched — Labrador is a cold current (from polar latitudes) and Gulf Stream is a warm current (originates near the equator).",
        },
        {
          q: "Where warm and cold ocean currents meet, which of the following conditions are typically found?",
          options: [
            "Desert conditions with no marine life",
            "Best fishing grounds AND foggy weather that is difficult for navigation",
            "Extremely rough seas with no fisheries",
            "Clear, calm weather with no marine life",
          ],
          correct: 1,
          explain:
            "Where warm and cold currents meet, they create the best fishing grounds in the world (areas around Japan, eastern coast of North America), but also produce foggy weather that makes navigation difficult.",
        },
        {
          q: [
            "Consider the following statements about the 2004 Indian Ocean Tsunami:",
            "I. It occurred on 26 December 2004.",
            "II. Its magnitude was 9.0 on the Richter Scale.",
            "III. Early warning systems in the Indian Ocean successfully gave a 3-hour advance warning.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I and II only",
            "I, II and III",
            "II and III only",
            "I only",
          ],
          correct: 0,
          explain:
            "Statements I and II are correct. Statement III is incorrect — the chapter specifically states that early warning systems existed across the Pacific Ocean but NOT in the Indian Ocean at the time — which is why the damage was so severe.",
        },
        {
          q: "Approximately what proportion of the Earth's surface is covered by water, and how much of the total water is held by the oceans?",
          options: [
            "One-half of the surface; oceans hold 50%",
            "Three-fourths of the surface; oceans hold 97.3% (saline)",
            "One-fourth of the surface; oceans hold 75%",
            "Two-thirds of the surface; oceans hold 2.7%",
          ],
          correct: 1,
          explain:
            "About three-fourths (75%) of the Earth's surface is covered by water, and the oceans hold 97.3% of all water — which is saline and unfit for human use.",
        },
        {
          q: "Salinity is defined as:",
          options: [
            "The temperature of ocean water at the surface",
            "The amount of salt present in grams in 1,000 grams of water",
            "The depth at which ocean water becomes dense",
            "The rate at which ocean water evaporates",
          ],
          correct: 1,
          explain:
            "Salinity is the amount of salt (in grams) present in 1,000 grams of water. Most of this salt is sodium chloride — common table salt.",
        },
        {
          q: "Which of the following holds the largest share of the Earth's fresh water?",
          options: [
            "Rivers",
            "Fresh water lakes",
            "Ice caps",
            "The atmosphere",
          ],
          correct: 2,
          explain:
            "Ice caps hold about 2.0% of all water — the largest share of fresh water. Groundwater is 0.68% and rivers only 0.0001%.",
        },
        {
          q: "The share of total water held by rivers is only about:",
          options: ["2.0%", "0.68%", "0.009%", "0.0001%"],
          correct: 3,
          explain:
            "Rivers hold only about 0.0001% of the total water — the tiniest fraction. Most fresh water is locked in ice caps (2.0%).",
        },
        {
          q: "Warm ocean currents are best described as those which:",
          options: [
            "Carry water from polar regions towards the tropics",
            "Originate near the equator and move towards the poles, bringing warm temperatures over the land surface",
            "Flow only along the ocean floor",
            "Are caused by the gravitational pull of the moon",
          ],
          correct: 1,
          explain:
            "Warm currents originate near the equator and move towards the poles, bringing warm temperatures over land. Cold currents carry water from polar/higher latitudes to tropical/lower latitudes.",
        },
        {
          q: "The rhythmic rise and fall of ocean water twice a day (tides) is caused mainly by:",
          options: [
            "Winds scraping across the ocean surface",
            "The strong gravitational pull of the sun and the moon on the Earth's surface",
            "Underwater earthquakes and volcanic eruptions",
            "The rotation of ocean currents",
          ],
          correct: 1,
          explain:
            "Tides are caused by the strong gravitational pull of the sun and the moon on the Earth's surface, producing high and low tides twice a day.",
        },
        {
          q: [
            "Consider the following statements about tsunamis:",
            "I. A tsunami can be caused by an earthquake, a volcanic eruption or an underwater landslide.",
            "II. The largest tsunami wave ever measured was about 150 m high.",
            "Which of the statements given above is/are correct?",
          ],
          options: ["I only", "II only", "Both I and II", "Neither I nor II"],
          correct: 2,
          explain:
            "Both statements are correct — tsunamis are caused by earthquakes, volcanic eruptions or underwater landslides, and while they may be as high as 15 m, the largest ever measured was about 150 m.",
        },
        {
          q: [
            "Assertion (A): The same water has existed on Earth for centuries and is continually recycled.",
            "Reason (R): Water in the water cycle continually changes its form and circulates between the oceans, the atmosphere and the land.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R correctly explains A — because water endlessly circulates through the water cycle (changing form between ocean, atmosphere and land), the same water has effectively existed for centuries, like in a terrarium.",
        },
        {
          q: "Which of the following correctly distinguishes high tide from low tide?",
          options: [
            "High tide: water recedes to its lowest level; Low tide: water rises to its highest level",
            "High tide: water rises to its highest level covering much of the shore; Low tide: water falls to its lowest level and recedes",
            "High tide and low tide occur only during full moon",
            "High tide occurs in summer; low tide occurs in winter",
          ],
          correct: 1,
          explain:
            "During high tide, water covers much of the shore by rising to its highest level. During low tide, water falls to its lowest level and recedes from the shore.",
        },
        {
          q: "The 2004 tsunami caused a sudden displacement of the ocean floor by about:",
          options: ["1–2 m", "10–20 m", "50–60 m", "100–150 m"],
          correct: 1,
          explain:
            "As the Indian plate went under the Burma plate, there was a sudden movement of the sea floor, displacing the ocean floor by about 10–20 m and triggering the devastating tsunami.",
        },
      ],
    },
  },
});
