// ═══════════════════════════════════════════════════════════
// CONTENT CHUNK "gs1" — Auto-generated by build-bundle.js.
// DO NOT EDIT DIRECTLY. Loaded on demand by js/engine/loader.js the
// first time a topic in this subject is opened. Edit source under
// js/data/ and re-run: node build-bundle.js
// ═══════════════════════════════════════════════════════════
__registerContent("gs1", {
  notes: {
    "geo6-ch1": {
      era: "NCERT Class 6 — Geography, Chapter 1",
      significance: [
        "Foundational chapter for the entire Geography syllabus — defines celestial bodies, the solar system's structure, and the Earth's unique position within it",
        "Distances, orbital periods, and rotation periods from this chapter are among the most frequently tested static facts in Prelims",
        "Establishes core vocabulary (star, planet, satellite, asteroid, meteoroid, galaxy) used throughout higher-level Geography and even some Science-based Prelims questions",
      ],
      features: [
        {
          key: "Celestial Bodies",
          main: "The sun, the moon, and all objects shining in the night sky are called celestial bodies",
          note: "",
        },
        {
          key: "Stars",
          main: "Very big, hot celestial bodies made up of gases, with their own heat and light\nThe Sun is a star",
          note: "Other stars appear tiny and give no felt heat/light because they are extremely far away",
        },
        {
          key: "Constellations",
          main: "Patterns formed by different groups of stars\nUrsa Major (Big Bear) is one such constellation",
          note: "Saptarishi ('seven sages') — a group of 7 stars forming part of Ursa Major",
        },
        {
          key: "Pole Star (North Star)",
          main: "Indicates the north direction; always remains in the same position in the sky\nLocated using the Saptarishi's pointer stars",
          note: "Used historically to determine direction at night",
        },
        {
          key: "Planets",
          main: "Celestial bodies with NO heat/light of their own — lit by starlight\nWord 'planet' comes from Greek 'Planetai' meaning 'wanderers'\nEarth is a planet, getting its heat & light from the Sun",
          note: "",
        },
        {
          key: "Satellites",
          main: "A celestial body that moves around a planet, the way planets move around the Sun\nThe Moon is Earth's (only) natural satellite",
          note: "Human-made satellites are artificial bodies, carried by rockets, placed in orbit for communication/data-gathering — e.g. INSAT, IRS, EDUSAT (Indian satellites)",
        },
        {
          key: "The Solar System",
          main: "Sun + 8 planets + satellites + asteroids + meteoroids = the Solar System (a 'solar family' with the Sun as its head)",
          note: "",
        },
        {
          key: "The Sun",
          main: "Centre of the Solar System; huge, made of extremely hot gases\nProvides the pulling (gravitational) force binding the Solar System; ultimate source of heat & light",
          note: "About 150 million km from Earth",
        },
        {
          key: "The 8 Planets (in order from Sun)",
          main: "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune\nMnemonic: 'My Very Efficient Mother Just Served Us Nuts'",
          note: "All planets move around the Sun in fixed, elongated paths called orbits",
        },
        {
          key: "Mercury",
          main: "Nearest planet to the Sun; distance from Sun ≈ 58 million km\nTakes only ~88 days to complete one orbit",
          note: "",
        },
        {
          key: "Venus",
          main: "Called 'Earth's twin' — size and shape very similar to Earth's\nDistance from Sun ≈ 108 million km",
          note: "",
        },
        {
          key: "Earth",
          main: "3rd nearest planet to the Sun; 5th largest planet\nSlightly flattened at the poles → shape described as a Geoid (earth-like shape)\nDistance from Sun ≈ 150 million km",
          note: "Unique due to: not too hot/cold, presence of water & air, oxygen (life-supporting gas)",
        },
        {
          key: "Earth as 'Blue Planet'",
          main: "Appears blue from outer space because two-thirds of its surface is covered by water",
          note: "",
        },
        { key: "Mars", main: "Distance from Sun ≈ 228 million km", note: "" },
        {
          key: "Jupiter",
          main: "Largest planet; distance from Sun ≈ 778 million km",
          note: "Has rings (belts of small debris), visible from Earth via powerful telescopes",
        },
        {
          key: "Saturn",
          main: "Distance from Sun ≈ 1,427 million km",
          note: "Has rings, visible from Earth via powerful telescopes",
        },
        {
          key: "Uranus",
          main: "Distance from Sun ≈ 2,869 million km",
          note: "Has rings, visible from Earth via powerful telescopes",
        },
        {
          key: "Neptune",
          main: "Farthest planet from the Sun; distance from Sun ≈ 4,496 million km",
          note: "",
        },
        {
          key: "Pluto — Dwarf Planet",
          main: "Considered a planet until August 2006\nInternational Astronomical Union reclassified it (along with Ceres, 2003 UB313) as a 'dwarf planet'",
          note: "",
        },
        {
          key: "The Moon",
          main: "Earth's only natural satellite; diameter ≈ 1/4 of Earth's\nDistance from Earth ≈ 3,84,400 km\nOrbits Earth in ~27 days, and also SPINS on its axis in ~27 days",
          note: "Because orbit period = spin period, only ONE side of the Moon is ever visible from Earth",
        },
        {
          key: "Moon's Surface",
          main: "No conditions favourable for life\nHas mountains, plains, and depressions, which cast shadows visible from Earth",
          note: "",
        },
        {
          key: "Asteroids",
          main: "Numerous tiny bodies that move around the Sun\nFound in the Asteroid Belt — between the orbits of Mars and Jupiter",
          note: "Scientists believe asteroids are parts of a planet that exploded long ago",
        },
        {
          key: "Meteoroids",
          main: "Small pieces of rock that move around the Sun\nWhen they near Earth and fall, friction with air heats/burns them, causing a flash of light ('meteor' / shooting star)",
          note: "A meteoroid not fully burnt may fall on Earth and create a hollow (crater)",
        },
        {
          key: "Milky Way Galaxy",
          main: "The whitish broad band across a clear starry night sky — a cluster of millions of stars\nOur Solar System is part of this galaxy",
          note: "In ancient India, imagined as a river of light in the sky, named Akash Ganga",
        },
        {
          key: "Galaxy & Universe",
          main: "A galaxy = a huge system of billions of stars + clouds of dust and gases\nMillions of such galaxies together make up the Universe",
          note: "",
        },
        {
          key: "Full Moon & New Moon",
          main: "Full Moon Night (Poornima) — moon fully visible, occurs once about every month\nNew Moon Night (Amavasya) — moon not visible at all, a fortnight after Poornima",
          note: "New Moon night is best for observing the night sky clearly",
        },
        {
          key: "First Moon Landing",
          main: "Neil Armstrong — first human to step on the Moon's surface, on 20 July 1969",
          note: "",
        },
      ],
      traps: [
        {
          label: "Distance Order Trap (memorise exact figures)",
          lines: [
            "Mercury 58 → Venus 108 → Earth 150 → Mars 228 (million km from Sun)",
            "Jupiter 778 → Saturn 1,427 → Uranus 2,869 → Neptune 4,496",
            "UPSC may ask 'which planet is X million km from the Sun' or rank planets by distance",
          ],
        },
        {
          label: "Orbit Period vs Spin Period",
          lines: [
            "'One orbit around Sun' (revolution) ≠ 'one spin on axis' (rotation) — don't confuse the two",
            "Mercury: orbit 88 days, spin 59 days",
            "Venus: orbit 255 days, spin 243 days (spin is SLOWER than a Mercury year!)",
            "Earth: orbit 365 days, spin 1 day",
          ],
        },
        {
          label: "Moon: Orbit = Spin (unique among these)",
          lines: [
            "The Moon orbits Earth in ~27 days AND spins on its axis in ~27 days",
            "This equality is WHY only one side of the Moon is ever visible from Earth",
            "Don't confuse this with planets, where orbit and spin periods are usually very different",
          ],
        },
        {
          label: "Star vs Planet vs Satellite",
          lines: [
            "Star = own heat & light (e.g. Sun)",
            "Planet = NO own heat/light, lit by a star, orbits a star (e.g. Earth)",
            "Satellite = orbits a PLANET, not a star (e.g. Moon orbits Earth)",
          ],
        },
        {
          label: "Pluto Reclassification",
          lines: [
            "Pluto was a planet UNTIL August 2006",
            "Reclassified as a 'dwarf planet' by the International Astronomical Union",
            "Other dwarf planets mentioned: Ceres, 2003 UB313",
          ],
        },
        {
          label: "Asteroids vs Meteoroids",
          lines: [
            "Asteroids: bigger, found in the belt between Mars and Jupiter, orbit the Sun continuously",
            "Meteoroids: smaller ROCK pieces; when they enter Earth's atmosphere they burn up (flash of light) or create a crater",
          ],
        },
        {
          label: "Number of Moons (from the table)",
          lines: [
            "Earth = 1 moon; Mars = 2 moons",
            "Jupiter ≈ 53 moons; Saturn ≈ 53 moons (approximately equal!)",
            "Uranus ≈ 27 moons; Neptune = 13 moons",
            "Mercury & Venus = 0 moons (not listed with any moon count)",
          ],
        },
      ],
      mainsAngle:
        "While this NCERT chapter is primarily a Prelims-facts chapter (distances, orbital data, classification), its core theme — Earth's rare combination of conditions (temperature, water, oxygen) enabling life — connects to broader GS-1/GS-3 discussions on planetary habitability, the search for exoplanets, and India's own space exploration programme (ISRO's planetary missions).",
      mainsTheme:
        "Earth's habitability as a 'unique planet' — foundational concept for broader space & environment discussions",
      recall: [
        "8 planets: My Very Efficient Mother Just Served Us Nuts",
        "Sun–Earth distance ≈ 150 million km",
        "Earth = 3rd from Sun, 5th largest, shape = Geoid",
        "Earth = 'Blue Planet' (2/3 water-covered)",
        "Moon: orbit period = spin period ≈ 27 days → same side always visible",
        "Asteroid belt: between Mars & Jupiter",
        "Pluto → dwarf planet since Aug 2006",
        "Pole Star located via Saptarishi's pointer stars",
        "Neil Armstrong — first Moon landing, 20 July 1969",
        "Milky Way = our galaxy; Akash Ganga (ancient Indian name)",
        "Indian satellites: INSAT, IRS, EDUSAT",
      ],
    },
    "geo6-ch2": {
      era: "NCERT Class 6 — Geography, Chapter 2",
      significance: [
        "Establishes the entire coordinate system (latitude/longitude) used throughout Geography, map reading, and time-zone calculations — one of the most exam-relevant foundational chapters",
        "The exact degree values (23½°, 66½°, 82½°E) and heat-zone boundaries are extremely frequently tested static facts",
        "Directly underpins understanding of India's Standard Meridian and time-zone calculation logic, both recurring Prelims themes",
      ],
      features: [
        {
          key: "Globe",
          main: "A true model (miniature form) of the Earth\nShows countries, continents, and oceans in their correct size",
          note: "Comes in varying sizes: large, small pocket globes, inflatable globe-balloons",
        },
        {
          key: "Axis",
          main: "The tilted needle fixed through the globe, connecting North Pole and South Pole\nOn the real Earth, the axis is an IMAGINARY line (no physical needle)",
          note: "",
        },
        {
          key: "Equator",
          main: "An imaginary line dividing the Earth into two equal halves\nRepresents 0° latitude",
          note: "Divides Earth into Northern Hemisphere and Southern Hemisphere",
        },
        {
          key: "Latitude — Definition",
          main: "Parallel circles running from the equator up to the poles are called parallels of latitude\nMeasured in degrees",
          note: "Size of latitude parallels DECREASES as you move away from the equator toward the poles",
        },
        {
          key: "Latitude — Range & Poles",
          main: "Distance from equator to either pole = 1/4 of a full circle = 1/4 × 360° = 90°\nNorth Pole = 90°N; South Pole = 90°S",
          note: "Parallels north of equator = 'north latitudes' (N); south of equator = 'south latitudes' (S)",
        },
        {
          key: "4 Important Parallels (besides Equator & Poles)",
          main: "Tropic of Cancer — 23½°N\nTropic of Capricorn — 23½°S\nArctic Circle — 66½°N\nAntarctic Circle — 66½°S",
          note: "",
        },
        {
          key: "Torrid Zone",
          main: "Region between Tropic of Cancer (23½°N) and Tropic of Capricorn (23½°S)\nMid-day sun is exactly overhead at least once a year on every latitude here → receives MAXIMUM heat",
          note: "",
        },
        {
          key: "Temperate Zones",
          main: "North Temperate Zone: between Tropic of Cancer and Arctic Circle\nSouth Temperate Zone: between Tropic of Capricorn and Antarctic Circle\nMid-day sun never shines directly overhead here → moderate temperatures",
          note: "",
        },
        {
          key: "Frigid Zones",
          main: "North Frigid Zone: between Arctic Circle and North Pole\nSouth Frigid Zone: between Antarctic Circle and South Pole\nSun's rays always slanting (low angle) → very cold",
          note: "",
        },
        {
          key: "Longitude — Definition",
          main: "Meridians of longitude: reference lines running from North Pole to South Pole\nUsed to find how far EAST or WEST a place is from a reference line",
          note: "Distance measured in degrees of longitude; each degree divided into minutes, minutes into seconds",
        },
        {
          key: "Longitude — Shape & Convergence",
          main: "Meridians are semi-circles\nDistance between meridians DECREASES toward the poles, becoming ZERO at the poles (where all meridians meet)",
          note: "",
        },
        {
          key: "Latitude vs Longitude — Equal Length",
          main: "Latitudes: parallels are of DIFFERENT/decreasing lengths (largest at equator)\nLongitudes: ALL meridians are of EQUAL length",
          note: "This is why longitudes needed a special reference point to be numbered (unlike latitude, which naturally starts at the equator)",
        },
        {
          key: "Prime Meridian",
          main: "Passes through Greenwich (location of the British Royal Observatory)\nValue = 0° longitude; counted 180° eastward and 180° westward from it",
          note: "180°E and 180°W meridians are actually the SAME line",
        },
        {
          key: "Eastern & Western Hemisphere",
          main: "Prime Meridian + 180° meridian together divide the Earth into Eastern Hemisphere and Western Hemisphere",
          note: "Longitude values use E (east) or W (west) suffix",
        },
        {
          key: "Locating a Point (Latitude + Longitude)",
          main: "Any point on the globe can be located using its latitude AND longitude together (the grid)",
          note: "Example given: Dhubri, Assam is at 26°N, 90°E",
        },
        {
          key: "Local Time",
          main: "Best measured by the Sun's movement — shadow is shortest at noon, longest at sunrise/sunset\nWhen the Sun is at its highest point over the Prime Meridian, all places along it have noon",
          note: "All places on the SAME meridian of longitude share the same local time",
        },
        {
          key: "Time Difference — East vs West of Greenwich",
          main: "Places EAST of Greenwich are AHEAD of Greenwich time\nPlaces WEST of Greenwich are BEHIND Greenwich time",
          note: "Earth rotates west to east, causing this directional difference",
        },
        {
          key: "Time Calculation Rate",
          main: "Earth rotates 360° in ~24 hours → 15° per hour, or 1° in 4 minutes",
          note: "15°E of Greenwich = 1 hour AHEAD; 15°W of Greenwich = 1 hour BEHIND; 180° = exactly 12 hours different (midnight when Greenwich is noon)",
        },
        {
          key: "Why Standard Time is Needed",
          main: "Local time differs across meridians within the same country — impractical for things like train timetables",
          note: "Example: Dwarka (Gujarat) and Dibrugarh (Assam) differ by about 1 hour 45 minutes in local time",
        },
        {
          key: "Indian Standard Time (IST)",
          main: "India's Standard Meridian = 82½°E (82°30'E)\nLocal time at this meridian = Indian Standard Time (IST) for the whole country",
          note: "IST is 5 hours 30 minutes AHEAD of GMT (Greenwich Mean Time)",
        },
        {
          key: "Countries with Multiple Time Zones",
          main: "Countries with great longitudinal extent may adopt more than one standard time",
          note: "Russia has as many as 11 standard times",
        },
        {
          key: "World Time Zones",
          main: "Earth divided into 24 time zones of 1 hour each\nEach zone covers 15° of longitude",
          note: "",
        },
      ],
      traps: [
        {
          label: "Latitude vs Longitude — Shape/Length Confusion",
          lines: [
            "Latitudes = circles/parallels, DECREASING size toward poles, DIFFERENT lengths",
            "Longitudes = semi-circles/meridians, ALL of EQUAL length",
            "(A very frequently tested reversal trap)",
          ],
        },
        {
          label: "Exact Degree Values",
          lines: [
            "Tropic of Cancer = 23½°N (NOT 22½° or 21½°)",
            "Tropic of Capricorn = 23½°S",
            "Arctic Circle = 66½°N; Antarctic Circle = 66½°S",
            "India's Standard Meridian = 82½°E (NOT 80° or 85°)",
          ],
        },
        {
          label: "IST Offset from GMT",
          lines: [
            "IST = GMT + 5 hours 30 minutes (India is AHEAD, being east of Greenwich)",
            "Common trap: reversing direction (India is NOT behind GMT)",
          ],
        },
        {
          label: "East = Ahead, West = Behind",
          lines: [
            "Places EAST of Greenwich → AHEAD of Greenwich time",
            "Places WEST of Greenwich → BEHIND Greenwich time",
            "This is because Earth rotates west to east",
          ],
        },
        {
          label: "180° Meridian — Same Line Both Ways",
          lines: [
            "180°E and 180°W are the SAME physical meridian",
            "This line relates to the International Date Line concept",
          ],
        },
        {
          label: "Rate of Time Change",
          lines: [
            "1° longitude = 4 minutes of time difference",
            "15° longitude = 1 hour of time difference",
            "180° longitude = 12 hours difference",
          ],
        },
        {
          label: "Torrid/Temperate/Frigid Zone Boundaries",
          lines: [
            "Torrid Zone: between the two Tropics (23½°N to 23½°S)",
            "Temperate Zones: between a Tropic and the corresponding Circle (Arctic/Antarctic)",
            "Frigid Zones: between a Circle (Arctic/Antarctic) and the corresponding Pole",
          ],
        },
      ],
      mainsAngle:
        "The latitude-longitude coordinate system and standard time mechanism illustrate how geographic and astronomical principles translate into practical governance tools — India's choice of a single standard meridian (82½°E) despite significant east-west longitudinal spread reflects a deliberate trade-off between administrative simplicity and local time accuracy, a trade-off other large countries like Russia resolved differently by adopting multiple time zones.",
      mainsTheme:
        "Geography-to-governance link: how coordinate systems enable practical administration (standard time, timetables)",
      recall: [
        "Equator = 0° latitude; Poles = 90°N/90°S",
        "Tropic of Cancer 23½°N; Tropic of Capricorn 23½°S",
        "Arctic Circle 66½°N; Antarctic Circle 66½°S",
        "Torrid → Temperate → Frigid zones (equator to poles)",
        "Prime Meridian = 0°, through Greenwich",
        "Longitudes: ALL equal length; Latitudes: decreasing length toward poles",
        "1° longitude = 4 minutes time difference",
        "India's Standard Meridian = 82½°E",
        "IST = GMT + 5:30, India is AHEAD",
        "Russia has 11 standard times",
        "24 time zones worldwide, 15° each",
      ],
    },
  },
  quizzes: {
    "geo6-ch1": {
      title: "The Earth in the Solar System",
      questions: [
        {
          q: "Which of the following best defines a 'celestial body'?",
          options: [
            "Only planets and their moons",
            "The sun, the moon, and all objects shining in the night sky",
            "Only stars visible without a telescope",
            "Only human-made satellites",
          ],
          correct: 1,
          explain:
            "Celestial bodies include the sun, moon, and all shining objects in the night sky — a broad category covering stars, planets, satellites, asteroids, and meteoroids.",
        },
        {
          q: [
            "Consider the following statements regarding stars:",
            "I. Stars are made up of extremely hot gases.",
            "II. Stars have their own heat and light.",
            "III. All stars appear small because they are inherently smaller than planets.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I and II only",
            "II and III only",
            "I, II and III",
            "I only",
          ],
          correct: 0,
          explain:
            "Statements I and II are correct. Statement III is incorrect — stars appear small/tiny because of their extreme DISTANCE from us, not because they are inherently small; in fact the Sun (a star) is far larger than Earth.",
        },
        {
          q: "The Sun is classified as a:",
          options: ["Planet", "Star", "Satellite", "Dwarf planet"],
          correct: 1,
          explain:
            "The Sun is a star — a huge, hot celestial body made of gases with its own heat and light.",
        },
        {
          q: "A 'constellation' is best defined as:",
          options: [
            "A single very bright star",
            "A pattern formed by a group of stars",
            "Another name for a galaxy",
            "A belt of asteroids",
          ],
          correct: 1,
          explain:
            "A constellation is a pattern formed by different groups of stars, such as Ursa Major.",
        },
        {
          q: "The Saptarishi, a group of seven stars, forms part of which constellation?",
          options: [
            "Orion",
            "Ursa Major (Big Bear)",
            "Ursa Minor",
            "Cassiopeia",
          ],
          correct: 1,
          explain:
            "The Saptarishi is a group of seven stars forming part of the Ursa Major (Big Bear) constellation.",
        },
        {
          q: [
            "Assertion (A): The Pole Star (North Star) has historically been used to determine direction at night.",
            "Reason (R): The Pole Star always remains in the same position in the sky.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R directly explains A — the Pole Star's fixed position is precisely why it could reliably indicate the north direction for navigation.",
        },
        {
          q: "The position of the Pole Star can be located with the help of which group of stars?",
          options: [
            "Orion's Belt",
            "The Saptarishi (pointer stars)",
            "The Milky Way band",
            "The Asteroid Belt",
          ],
          correct: 1,
          explain:
            "An imaginary line joining the Saptarishi's 'pointer stars' and extended further points to the Pole Star.",
        },
        {
          q: "Which of the following correctly distinguishes a planet from a star?",
          options: [
            "Planets have their own heat and light; stars do not",
            "Planets have NO heat/light of their own and are lit by starlight; stars have their own heat and light",
            "Both planets and stars generate their own heat and light equally",
            "There is no meaningful difference between the two",
          ],
          correct: 1,
          explain:
            "This is the fundamental distinction — planets are lit by reflected/received starlight, while stars generate their own heat and light.",
        },
        {
          q: "The word 'planet' is derived from the Greek word 'Planetai', which means:",
          options: [
            "Shining objects",
            "Wanderers",
            "Fixed stars",
            "Giant bodies",
          ],
          correct: 1,
          explain:
            "'Planetai' means 'wanderers' — reflecting how planets appear to move against the fixed backdrop of stars.",
        },
        {
          q: "A 'satellite' is best defined as a celestial body that:",
          options: [
            "Moves around the Sun directly, like a planet",
            "Moves around a planet, in the same way planets move around the Sun",
            "Generates its own heat and light",
            "Is found only in the asteroid belt",
          ],
          correct: 1,
          explain:
            "A satellite orbits a planet, analogous to how planets orbit the Sun — the Moon is Earth's natural satellite.",
        },
        {
          q: "Which of the following are examples of Indian human-made satellites?",
          options: [
            "INSAT, IRS, EDUSAT",
            "Sputnik, Apollo, Voyager",
            "Hubble, Kepler, Chandra",
            "Artemis, Orion, Gemini",
          ],
          correct: 0,
          explain:
            "INSAT, IRS, and EDUSAT are examples of Indian satellites mentioned in the chapter.",
        },
        {
          q: [
            "Consider the following statements regarding the composition of the Solar System:",
            "I. It consists of the Sun, eight planets, and satellites.",
            "II. It also includes asteroids and meteoroids.",
            "III. Pluto is officially counted among the eight planets of the Solar System.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I and II only",
            "I, II and III",
            "II and III only",
            "I only",
          ],
          correct: 0,
          explain:
            "Statements I and II are correct. Statement III is incorrect — Pluto was reclassified as a 'dwarf planet' in August 2006 and is not among the eight planets.",
        },
        {
          q: "What force does the Sun provide that binds the Solar System together?",
          options: [
            "Magnetic force",
            "The pulling (gravitational) force",
            "Nuclear force",
            "Electrostatic force",
          ],
          correct: 1,
          explain:
            "The Sun provides the pulling (gravitational) force that binds the entire Solar System together.",
        },
        {
          q: "The approximate distance between the Sun and the Earth is:",
          options: [
            "108 million km",
            "150 million km",
            "228 million km",
            "778 million km",
          ],
          correct: 1,
          explain:
            "The Sun is approximately 150 million km away from the Earth.",
        },
        {
          q: "Which of the following correctly lists the eight planets of the Solar System in order of increasing distance from the Sun?",
          options: [
            "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune",
            "Venus, Mercury, Earth, Mars, Saturn, Jupiter, Neptune, Uranus",
            "Mercury, Earth, Venus, Mars, Jupiter, Uranus, Saturn, Neptune",
            "Mercury, Venus, Mars, Earth, Jupiter, Saturn, Neptune, Uranus",
          ],
          correct: 0,
          explain:
            "The correct order, matching the mnemonic 'My Very Efficient Mother Just Served Us Nuts', is Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.",
        },
        {
          q: "Which planet is nearest to the Sun, and approximately how long does it take to complete one orbit?",
          options: [
            "Venus; about 255 days",
            "Mercury; about 88 days",
            "Earth; about 365 days",
            "Mars; about 687 days",
          ],
          correct: 1,
          explain:
            "Mercury is nearest to the Sun and takes about 88 days to complete one orbit.",
        },
        {
          q: "Which planet is often referred to as 'Earth's twin' because of its similar size and shape?",
          options: ["Mars", "Venus", "Mercury", "Jupiter"],
          correct: 1,
          explain:
            "Venus is called 'Earth's twin' due to its size and shape being very similar to Earth's.",
        },
        {
          q: [
            "Consider the following pairs of planets and their approximate distance from the Sun (in million km):",
            "I. Mars — 228",
            "II. Jupiter — 1,427",
            "III. Neptune — 4,496",
            "How many of the above pairs are correctly matched?",
          ],
          options: [
            "Only one pair",
            "Only two pairs",
            "All three pairs",
            "None of the pairs",
          ],
          correct: 1,
          explain:
            "Pairs I and III are correctly matched. Pair II is incorrect — Jupiter's distance is approximately 778 million km; 1,427 million km is Saturn's distance.",
        },
        {
          q: "The Earth is the ____ nearest planet to the Sun and the ____ largest planet in the Solar System.",
          options: [
            "third; fifth",
            "fifth; third",
            "second; fourth",
            "fourth; fifth",
          ],
          correct: 0,
          explain:
            "The Earth is the third nearest planet to the Sun and the fifth largest planet overall.",
        },
        {
          q: "The Earth's shape is described as a 'Geoid' primarily because:",
          options: [
            "It is a perfect sphere",
            "It is slightly flattened at the poles",
            "It has continents and oceans",
            "It rotates on a tilted axis",
          ],
          correct: 1,
          explain:
            "'Geoid' (earth-like shape) describes the Earth's actual shape, which is slightly flattened at the poles rather than a perfect sphere.",
        },
        {
          q: "Which of the following is NOT among the reasons the chapter gives for Earth being called a 'unique planet'?",
          options: [
            "Presence of water",
            "Presence of life-supporting gases like oxygen",
            "Neither too hot nor too cold",
            "Presence of visible rings",
          ],
          correct: 3,
          explain:
            "Visible rings are a feature of Jupiter, Saturn, and Uranus — NOT a reason cited for Earth's uniqueness. Earth's uniqueness stems from its temperature balance, water, and oxygen-rich air.",
        },
        {
          q: "The Earth is called the 'Blue Planet' because:",
          options: [
            "Its atmosphere scatters blue light exclusively",
            "Two-thirds of its surface is covered by water",
            "It appears blue due to its core temperature",
            "Its polar ice caps are blue in colour",
          ],
          correct: 1,
          explain:
            "The Earth appears blue from outer space because two-thirds of its surface is covered by water.",
        },
        {
          q: "Which planet has rings around it, as visible with powerful telescopes?",
          options: [
            "Only Saturn",
            "Jupiter, Saturn, and Uranus",
            "Only Jupiter and Mars",
            "Mercury, Venus, and Mars",
          ],
          correct: 1,
          explain:
            "Jupiter, Saturn, and Uranus all have rings — belts of small debris — visible from Earth with powerful telescopes.",
        },
        {
          q: [
            "Consider the following statements regarding Pluto:",
            "I. It was considered a planet until August 2006.",
            "II. It was reclassified as a 'dwarf planet' by the International Astronomical Union.",
            "III. Ceres and 2003 UB313 were reclassified alongside Pluto.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I and II only",
            "I, II and III",
            "II and III only",
            "I only",
          ],
          correct: 1,
          explain:
            "All three statements are correct — Pluto's 2006 reclassification alongside Ceres and 2003 UB313 into the 'dwarf planet' category is a frequently tested fact.",
        },
        {
          q: "The Moon's diameter is approximately what fraction of the Earth's diameter?",
          options: ["One-half", "One-third", "One-quarter", "One-tenth"],
          correct: 2,
          explain:
            "The Moon's diameter is only about one-quarter that of the Earth's.",
        },
        {
          q: "The Moon is approximately how far from the Earth?",
          options: [
            "1,50,000 km",
            "3,84,400 km",
            "5,00,000 km",
            "10,00,000 km",
          ],
          correct: 1,
          explain:
            "The Moon is about 3,84,400 km away from the Earth — vastly closer than the Sun (150 million km).",
        },
        {
          q: [
            "Assertion (A): Only one side of the Moon is ever visible from Earth.",
            "Reason (R): The Moon's orbital period around Earth and its rotational (spin) period on its own axis are both approximately 27 days.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R directly explains A — because the Moon's orbit and spin periods are equal (~27 days each), the same face always points toward Earth.",
        },
        {
          q: "Which of the following features are found on the Moon's surface?",
          options: [
            "Oceans and rivers only",
            "Mountains, plains, and depressions",
            "Dense forests",
            "Polar ice caps only",
          ],
          correct: 1,
          explain:
            "The Moon's surface has mountains, plains, and depressions, which cast shadows visible from Earth.",
        },
        {
          q: "Asteroids are found primarily in the belt located between the orbits of which two planets?",
          options: [
            "Earth and Mars",
            "Mars and Jupiter",
            "Jupiter and Saturn",
            "Venus and Earth",
          ],
          correct: 1,
          explain:
            "The Asteroid Belt lies between the orbits of Mars and Jupiter.",
        },
        {
          q: "According to the chapter, what do scientists believe about the origin of asteroids?",
          options: [
            "They are fragments of comets",
            "They are parts of a planet that exploded many years back",
            "They are debris from the Moon",
            "They originated from the Sun's outer layers",
          ],
          correct: 1,
          explain:
            "Scientists are of the view that asteroids are parts of a planet which exploded many years back.",
        },
        {
          q: "Which of the following correctly distinguishes asteroids from meteoroids?",
          options: [
            "Asteroids are tiny bodies orbiting the Sun (mainly in the Mars-Jupiter belt); meteoroids are small rock pieces that may fall to Earth and burn up due to atmospheric friction",
            "Meteoroids orbit only within the asteroid belt, while asteroids fall to Earth",
            "Both terms refer to exactly the same category of celestial body",
            "Asteroids are found only near the Moon, while meteoroids orbit the Sun",
          ],
          correct: 0,
          explain:
            "Asteroids are tiny Sun-orbiting bodies (mainly between Mars and Jupiter); meteoroids are small rock fragments that, upon nearing Earth, heat up and burn due to atmospheric friction — sometimes producing a visible flash or, if unburnt, a crater.",
        },
        {
          q: "The flash of light sometimes seen in the night sky, caused by a meteoroid burning up due to friction with air, is commonly called a:",
          options: ["Comet", "Meteor (shooting star)", "Nova", "Constellation"],
          correct: 1,
          explain:
            "This flash of light, caused by atmospheric friction burning a meteoroid, is what is commonly seen as a 'shooting star' or meteor.",
        },
        {
          q: "The whitish, broad, glowing band visible across a clear night sky is:",
          options: [
            "The Asteroid Belt",
            "The Milky Way galaxy",
            "The Pole Star's halo",
            "Earth's shadow",
          ],
          correct: 1,
          explain:
            "This band is the Milky Way galaxy, a cluster of millions of stars — our Solar System is part of it.",
        },
        {
          q: "In ancient India, the Milky Way was imagined as a river of light flowing in the sky and was named:",
          options: [
            "Ganga Sagar",
            "Akash Ganga",
            "Nakshatra Path",
            "Surya Marg",
          ],
          correct: 1,
          explain:
            "The Milky Way was poetically named Akash Ganga in ancient India.",
        },
        {
          q: "A 'galaxy' is best defined as:",
          options: [
            "A single very large star",
            "A huge system of billions of stars along with clouds of dust and gases",
            "The path a planet takes around the Sun",
            "A collection of all the planets in one solar system",
          ],
          correct: 1,
          explain:
            "A galaxy is a huge system of billions of stars and clouds of dust and gases — millions of such galaxies together form the Universe.",
        },
        {
          q: "Which of the following correctly describes 'Poornima' and 'Amavasya'?",
          options: [
            "Poornima is New Moon night; Amavasya is Full Moon night",
            "Poornima is Full Moon night; Amavasya is New Moon night, occurring about a fortnight later",
            "Both refer to the same lunar phase",
            "Poornima occurs only once a year",
          ],
          correct: 1,
          explain:
            "Poornima is the Full Moon night; Amavasya, the New Moon night (when the Moon is not visible at all), occurs about a fortnight after Poornima.",
        },
        {
          q: "The night sky is best observed on which of the following nights, according to the chapter?",
          options: [
            "Poornima (Full Moon)",
            "Amavasya (New Moon), provided it is clear",
            "Any night with a full sky of clouds",
            "Only during a solar eclipse",
          ],
          correct: 1,
          explain:
            "On Amavasya (New Moon night), with no bright moonlight to interfere, the night sky can be observed best, provided it is a clear night.",
        },
        {
          q: "Neil Armstrong became the first human to step on the surface of the Moon on which date?",
          options: [
            "15 August 1969",
            "20 July 1969",
            "4 July 1969",
            "12 April 1961",
          ],
          correct: 1,
          explain:
            "Neil Armstrong stepped onto the Moon's surface on 20 July 1969.",
        },
        {
          q: "Considering the table of orbital and rotational data, which of the following pairs is correctly matched (planet — approximate number of moons)?",
          options: [
            "Earth — 2 moons",
            "Mars — 1 moon",
            "Jupiter — about 53 moons",
            "Neptune — about 27 moons",
          ],
          correct: 2,
          explain:
            "Jupiter has about 53 moons. Earth has 1 moon (not 2), Mars has 2 moons (not 1), and Neptune has 13 moons (not 27 — that figure belongs to Uranus).",
        },
        {
          q: "Which of the following planets takes LONGER to spin once on its axis than Mercury takes to complete an entire orbit around the Sun?",
          options: [
            "Earth",
            "Mars",
            "Venus",
            "None — no planet's spin period exceeds Mercury's orbital period",
          ],
          correct: 2,
          explain:
            "Venus takes about 243 days to spin once on its axis — longer than Mercury's ~88-day orbital period around the Sun, an unusual and frequently tested fact about Venus's extremely slow rotation.",
        },
      ],
    },
    "geo6-ch2": {
      title: "Globe: Latitudes and Longitudes",
      questions: [
        {
          q: "A globe is best described as:",
          options: [
            "A flat representation of the Earth",
            "A true model (miniature form) of the Earth",
            "A model showing only oceans",
            "A device used only for measuring time",
          ],
          correct: 1,
          explain:
            "A globe is a true model (miniature form) of the Earth, showing countries, continents, and oceans in their correct relative size.",
        },
        {
          q: [
            "Consider the following statements regarding the axis of the Earth:",
            "I. On a globe, the axis is represented by a tilted needle passing through the North and South Poles.",
            "II. On the real Earth, the axis is a physical, visible structure.",
            "Which of the statements given above is/are correct?",
          ],
          options: ["I only", "II only", "Both I and II", "Neither I nor II"],
          correct: 0,
          explain:
            "Statement I is correct. Statement II is incorrect — on the real Earth, the axis is an IMAGINARY line, unlike the physical needle used in a globe model.",
        },
        {
          q: "The equator is best described as:",
          options: [
            "An imaginary line dividing the Earth into Eastern and Western Hemispheres",
            "An imaginary line dividing the Earth into Northern and Southern Hemispheres, representing 0° latitude",
            "A physical boundary marking the Torrid Zone only",
            "The line along which all meridians converge",
          ],
          correct: 1,
          explain:
            "The equator divides the Earth into the Northern and Southern Hemispheres and represents 0° latitude.",
        },
        {
          q: [
            "Assertion (A): The size of latitude parallels decreases as one moves away from the equator toward the poles.",
            "Reason (R): Latitude parallels are circles drawn parallel to the equator, and the Earth's shape causes these circles to shrink closer to the poles.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R correctly explains A — as latitude parallels approach the poles, the Earth's curvature causes their circumference to shrink continuously until reaching a point at the poles.",
        },
        {
          q: "The distance from the equator to either pole represents what fraction of a full circle around the Earth, and what angular value does this correspond to?",
          options: [
            "1/2 of a circle; 180°",
            "1/4 of a circle; 90°",
            "1/3 of a circle; 120°",
            "1/8 of a circle; 45°",
          ],
          correct: 1,
          explain:
            "The distance from the equator to a pole is 1/4 of a full circle (360°), which equals 90° — hence the poles are at 90°N and 90°S.",
        },
        {
          q: [
            "Consider the following statements:",
            "I. Parallels north of the equator are called 'north latitudes'.",
            "II. Chandrapur (Maharashtra, India) and Belo Horizonte (Brazil) are both located on parallels of about 20° latitude, but on opposite sides of the equator.",
            "Which of the statements given above is/are correct?",
          ],
          options: ["I only", "II only", "Both I and II", "Neither I nor II"],
          correct: 2,
          explain:
            "Both statements are correct — Chandrapur is at 20°N while Belo Horizonte is at 20°S, illustrating how the same numerical latitude value can apply to places in opposite hemispheres.",
        },
        {
          q: "Which of the following correctly lists all four 'important parallels of latitude' besides the equator and the poles?",
          options: [
            "Tropic of Cancer, Tropic of Capricorn, Arctic Circle, Antarctic Circle",
            "Tropic of Cancer, Prime Meridian, Arctic Circle, International Date Line",
            "Equator, Tropic of Capricorn, Arctic Circle, Standard Meridian",
            "Tropic of Cancer, Tropic of Capricorn, North Pole, South Pole",
          ],
          correct: 0,
          explain:
            "The four important parallels (besides equator and poles) are the Tropic of Cancer, Tropic of Capricorn, Arctic Circle, and Antarctic Circle.",
        },
        {
          q: "The Tropic of Cancer is located at:",
          options: ["23½°S", "23½°N", "66½°N", "0°"],
          correct: 1,
          explain:
            "The Tropic of Cancer is located at 23½° north of the equator, in the Northern Hemisphere.",
        },
        {
          q: [
            "Consider the following pairs:",
            "Parallel — Value",
            "I. Tropic of Capricorn — 23½°S",
            "II. Arctic Circle — 66½°N",
            "III. Antarctic Circle — 60°S",
            "How many of the above pairs are correctly matched?",
          ],
          options: [
            "Only one pair",
            "Only two pairs",
            "All three pairs",
            "None of the pairs",
          ],
          correct: 1,
          explain:
            "Pairs I and II are correctly matched. Pair III is incorrect — the Antarctic Circle is at 66½°S, not 60°S.",
        },
        {
          q: "The region between the Tropic of Cancer and the Tropic of Capricorn, where the mid-day sun is exactly overhead at least once a year on every latitude, is called the:",
          options: [
            "Temperate Zone",
            "Torrid Zone",
            "Frigid Zone",
            "Equatorial Trough",
          ],
          correct: 1,
          explain:
            "This region, receiving maximum heat, is called the Torrid Zone.",
        },
        {
          q: "Which of the following correctly describes the boundaries of the North Temperate Zone?",
          options: [
            "Between the equator and the Tropic of Cancer",
            "Between the Tropic of Cancer and the Arctic Circle",
            "Between the Arctic Circle and the North Pole",
            "Between the Tropic of Capricorn and the Antarctic Circle",
          ],
          correct: 1,
          explain:
            "The North Temperate Zone lies between the Tropic of Cancer (23½°N) and the Arctic Circle (66½°N).",
        },
        {
          q: "Why are the Frigid Zones (areas between the Arctic/Antarctic Circles and the respective Poles) very cold?",
          options: [
            "Because they receive no sunlight at all, ever",
            "Because the sun does not rise much above the horizon there, so its rays are always slanting and provide less heat",
            "Because they are located at the highest altitude on Earth",
            "Because ocean currents there are always cold",
          ],
          correct: 1,
          explain:
            "In the Frigid Zones, the sun stays low on the horizon, so its rays strike at a slanting angle, delivering less heat per unit area — not because there is no sunlight at all.",
        },
        {
          q: [
            "Consider the following statements regarding heat zones:",
            "I. The Torrid Zone lies between the two Tropics.",
            "II. The Temperate Zones lie between a Tropic and the corresponding polar Circle.",
            "III. The Frigid Zones lie between a polar Circle and the corresponding Pole.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I and II only",
            "II and III only",
            "I, II and III",
            "I only",
          ],
          correct: 2,
          explain:
            "All three statements correctly describe the sequential structure of Earth's heat zones from equator to poles.",
        },
        {
          q: "Meridians of longitude are used to determine:",
          options: [
            "How far north or south a place is from the equator",
            "How far east or west a place is from a given reference line running pole to pole",
            "The height of a place above sea level",
            "The temperature zone of a place",
          ],
          correct: 1,
          explain:
            "Longitude measures east-west position relative to a reference meridian, complementing latitude's north-south measurement.",
        },
        {
          q: "Which of the following places are given as an example of locations on the SAME latitude (20°S) but needing longitude to be precisely distinguished?",
          options: [
            "Chandrapur and Belo Horizonte",
            "Tonga Islands and Mauritius Islands",
            "Dwarka and Dibrugarh",
            "Dhubri and Greenwich",
          ],
          correct: 1,
          explain:
            "Tonga Islands (Pacific Ocean) and Mauritius Islands (Indian Ocean) are both at 20°S, illustrating why longitude is needed alongside latitude to pinpoint a location precisely.",
        },
        {
          q: [
            "Assertion (A): All meridians of longitude are of equal length.",
            "Reason (R): Meridians are semi-circles running from the North Pole to the South Pole, and every such semi-circle spans the same north-south distance.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R explains A — since every meridian runs the same pole-to-pole distance, all meridians share equal length, unlike latitude parallels which shrink toward the poles.",
        },
        {
          q: "Which of the following correctly distinguishes latitude parallels from longitude meridians in terms of length?",
          options: [
            "Latitudes are all equal in length; longitudes decrease toward the poles",
            "Longitudes are all equal in length; latitudes decrease in length toward the poles",
            "Both latitudes and longitudes are equal in length",
            "Both latitudes and longitudes decrease in length toward the poles",
          ],
          correct: 1,
          explain:
            "This is a classic, frequently tested distinction — longitudes (meridians) are all equal in length, while latitudes (parallels) decrease in length moving from the equator toward the poles.",
        },
        {
          q: "Why did countries need to select a specific reference meridian (unlike latitude, which naturally starts at the equator)?",
          options: [
            "Because meridians are of unequal length, making a natural starting point necessary",
            "Because all meridians are of EQUAL length, so there was no natural 'zero point' the way the equator serves for latitude",
            "Because longitude cannot be measured in degrees",
            "Because only some meridians pass through the poles",
          ],
          correct: 1,
          explain:
            "Since all meridians are equal in length, none stood out naturally as a 'zero' reference the way the equator does for latitude — hence the need for countries to agree on the Prime Meridian.",
        },
        {
          q: "The Prime Meridian passes through which location?",
          options: [
            "Paris, France",
            "Greenwich, location of the British Royal Observatory",
            "Washington D.C., USA",
            "New Delhi, India",
          ],
          correct: 1,
          explain:
            "The Prime Meridian passes through Greenwich, where the British Royal Observatory is located, and has a value of 0° longitude.",
        },
        {
          q: "From the Prime Meridian, longitude is counted:",
          options: [
            "90° eastward and 90° westward only",
            "180° eastward as well as 180° westward",
            "360° in one direction only",
            "45° eastward and 45° westward only",
          ],
          correct: 1,
          explain:
            "Longitude is measured 180° eastward and 180° westward from the Prime Meridian.",
        },
        {
          q: "Which of the following statements about the 180° meridian is correct?",
          options: [
            "180°E and 180°W are two entirely separate meridians on opposite sides of the Earth",
            "180°E and 180°W are actually the same line",
            "The 180° meridian passes through Greenwich",
            "The 180° meridian does not exist; longitude stops at 90°",
          ],
          correct: 1,
          explain:
            "180°E and 180°W meridians are, interestingly, the same physical line — since counting 180° eastward and 180° westward from the Prime Meridian brings you to the same point.",
        },
        {
          q: "The Prime Meridian and the 180° meridian together divide the Earth into which two hemispheres?",
          options: [
            "Northern and Southern Hemispheres",
            "Eastern and Western Hemispheres",
            "Torrid and Temperate Hemispheres",
            "Land and Water Hemispheres",
          ],
          correct: 1,
          explain:
            "Together, the Prime Meridian and the 180° meridian divide the Earth into the Eastern Hemisphere and Western Hemisphere.",
        },
        {
          q: "To precisely locate a specific point on the globe (such as Dhubri, Assam), one needs to know:",
          options: [
            "Only its latitude",
            "Only its longitude",
            "Both its latitude AND longitude together",
            "Only its distance from the equator",
          ],
          correct: 2,
          explain:
            "A precise location requires both latitude and longitude together — the chapter gives Dhubri, Assam (26°N, 90°E) as an example.",
        },
        {
          q: "Local time at a place can best be measured using:",
          options: [
            "The length of shadows cast by the moon",
            "The movement of the sun, with shadows shortest at noon and longest at sunrise/sunset",
            "Only artificial clocks calibrated in Greenwich",
            "The position of the Pole Star",
          ],
          correct: 1,
          explain:
            "Local time is traditionally reckoned using the sun's movement, with the shortest shadow at noon and longest shadows at sunrise and sunset.",
        },
        {
          q: "When the sun is at its highest point over the Prime Meridian, what time is it at all places along that meridian?",
          options: ["Sunrise", "Sunset", "Mid-day/noon", "Midnight"],
          correct: 2,
          explain:
            "When the Prime Meridian has the sun at its highest point, all places along that meridian experience mid-day/noon.",
        },
        {
          q: "Which of the following correctly describes the relationship between longitude and time difference from Greenwich?",
          options: [
            "Places east of Greenwich are behind Greenwich time; places west are ahead",
            "Places east of Greenwich are ahead of Greenwich time; places west are behind",
            "There is no relationship between longitude and time",
            "Only places exactly on the Prime Meridian have any defined time",
          ],
          correct: 1,
          explain:
            "Because the Earth rotates west to east, places east of Greenwich experience sunrise/noon earlier and are therefore AHEAD of Greenwich time, while places west are BEHIND.",
        },
        {
          q: "The Earth rotates 360° in approximately 24 hours. This corresponds to how many degrees of rotation per hour?",
          options: ["10°", "15°", "20°", "24°"],
          correct: 1,
          explain: "360° ÷ 24 hours = 15° per hour.",
        },
        {
          q: "How many minutes of time difference correspond to 1° of longitude?",
          options: ["1 minute", "2 minutes", "4 minutes", "10 minutes"],
          correct: 2,
          explain:
            "Since 15° corresponds to 60 minutes (1 hour), 1° corresponds to 60/15 = 4 minutes.",
        },
        {
          q: "If it is 12 noon at Greenwich, what time will it be at 15° WEST of Greenwich?",
          options: ["1:00 p.m.", "11:00 a.m.", "12:00 midnight", "1:00 a.m."],
          correct: 1,
          explain:
            "15° west of Greenwich is 1 hour BEHIND Greenwich time, so if it is 12 noon at Greenwich, it will be 11:00 a.m. there.",
        },
        {
          q: "If it is 12 noon at Greenwich, what time will it be at exactly 180° longitude?",
          options: [
            "6:00 a.m.",
            "6:00 p.m.",
            "12:00 midnight",
            "12:00 noon (same as Greenwich)",
          ],
          correct: 2,
          explain:
            "180° represents exactly 12 hours of time difference (180° ÷ 15° per hour = 12 hours), so it will be midnight at 180° when it is noon at Greenwich.",
        },
        {
          q: "Why do countries generally need to adopt a 'standard time' rather than using pure local time everywhere?",
          options: [
            "Because local time is scientifically inaccurate",
            "Because local times differ across meridians within the same country, making things like train timetables impractical",
            "Because only Greenwich is allowed to have an official time",
            "Because standard time is required by international law regardless of longitudinal extent",
          ],
          correct: 1,
          explain:
            "The chapter cites the practical difficulty of scheduling (e.g. train timetables) across a country if every meridian kept a slightly different local time — hence the adoption of one standard time per country.",
        },
        {
          q: "Which longitude is treated as India's Standard Meridian?",
          options: ["68°E", "82½°E", "90°E", "97°E"],
          correct: 1,
          explain:
            "82½°E (82°30'E) is India's Standard Meridian, and its local time is taken as the Indian Standard Time (IST) for the whole country.",
        },
        {
          q: "Indian Standard Time (IST) is ahead of Greenwich Mean Time (GMT) by:",
          options: [
            "4 hours 30 minutes",
            "5 hours 30 minutes",
            "6 hours 30 minutes",
            "5 hours only, no minutes",
          ],
          correct: 1,
          explain:
            "IST is 5 hours 30 minutes ahead of GMT, since India lies east of Greenwich at 82°30'E.",
        },
        {
          q: "According to the chapter's example, if a cricket match starts at 2:00 p.m. in London, what time would it begin in India?",
          options: ["7:30 a.m.", "9:30 a.m.", "7:30 p.m.", "8:30 p.m."],
          correct: 2,
          explain:
            "Since IST is 5 hours 30 minutes ahead of GMT, a 2:00 p.m. start in London corresponds to 7:30 p.m. in India.",
        },
        {
          q: [
            "Consider the following statements regarding time zones:",
            "I. Countries with a large longitudinal extent may adopt more than one standard time.",
            "II. Russia has as many as 11 standard times.",
            "III. The Earth is divided into 24 time zones of 1 hour each, each covering 15° of longitude.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I and II only",
            "II and III only",
            "I, II and III",
            "I only",
          ],
          correct: 2,
          explain:
            "All three statements are correct — this set of facts (multiple time zones for large countries, Russia's 11 zones, and the 24 × 15° global division) is frequently tested together.",
        },
        {
          q: "Which of the following statements about the Indian Standard Meridian's location relative to India's landmass is best supported by the chapter?",
          options: [
            "It passes through the westernmost point of India",
            "It passes through the country roughly north-south, chosen as a central reference longitude for the whole country",
            "It lies entirely outside India's territory",
            "It changes every few years based on population shifts",
          ],
          correct: 1,
          explain:
            "82½°E was chosen as a central reference meridian running through India, whose local time is applied uniformly as IST across the country, despite India's actual longitudinal spread from about 68°E to 97°E.",
        },
      ],
    },
  },
});
