// ═══════════════════════════════════════════════════════════
// CONTENT "gs1/geography/ncert/class6/ch5/ch5" — Auto-generated by build-bundle.js. DO NOT EDIT.
// Mirrors the source notes file js/data/gs1/geography/ncert/class6/ch5/ch5.js. Loaded on demand
// by js/engine/loader.js the first time one of its topics is opened.
// Edit the source under js/data/ and re-run: node build-bundle.js
// ═══════════════════════════════════════════════════════════
__registerContent("gs1/geography/ncert/class6/ch5/ch5", {
  notes: {
    "geo6-ch5": {
      era: "NCERT Class 6 — Geography, Chapter 5",
      significance: [
        "The four domains (Lithosphere, Hydrosphere, Atmosphere, Biosphere) and their definitions are foundational Environment/Geography Prelims facts",
        "Ocean rankings by size, specific ocean characteristics (Pacific's shape, Atlantic's indented coast, Indian Ocean named after India), and atmospheric composition (N₂ 78%, O₂ 21%) are individually tested",
        "Continent-specific facts (Africa has all three tropics, Australia is an island continent, Antarctica has Indian research stations Maitri and Bharati) are high-value recall items",
      ],
      features: [
        {
          key: "Four Major Domains of the Earth",
          main: "1. Lithosphere — solid portion\n2. Hydrosphere — water portion\n3. Atmosphere — gaseous layer\n4. Biosphere — zone of life (where all three meet)",
          note: "Greek origins: Lithos=stone, Hudor=water, Atmos=vapour, Bios=life",
        },
        {
          key: "Lithosphere",
          main: "The solid portion of the Earth\nComprises rocks of the Earth's crust + thin layers of soil with nutrient elements that sustain organisms\nTwo main divisions: Continents (large landmasses) and Ocean Basins (huge water bodies)",
          note: "Elevation of land is measured from sea level (taken as zero)",
        },
        {
          key: "Mt. Everest and Mariana Trench",
          main: "Highest mountain peak: Mt. Everest = 8,848 metres above sea level\nGreatest depth: Mariana Trench = 11,022 metres (in the Pacific Ocean)\nThe depth of the sea is much more than the highest point on land",
          note: "",
        },
        {
          key: "Seven Continents",
          main: "Asia, Europe, Africa, North America, South America, Australia, Antarctica\nGreater part of land mass lies in the Northern Hemisphere",
          note: "",
        },
        {
          key: "Asia",
          main: "Largest continent — covers about one-third of total land area of Earth\nLies in Eastern Hemisphere\nTropic of Cancer passes through it\nSeparated from Europe by the Ural Mountains on the west\nCombined landmass of Europe + Asia = Eurasia",
          note: "",
        },
        {
          key: "Europe",
          main: "Much smaller than Asia\nLies to the west of Asia\nArctic Circle passes through it\nBound by water bodies on three sides",
          note: "",
        },
        {
          key: "Africa",
          main: "Second largest continent after Asia\nEquator (0° latitude) runs almost through the middle\nLarge part lies in the Northern Hemisphere\nOnly continent through which the Tropic of Cancer, the Equator, AND the Tropic of Capricorn all pass\nSahara Desert (world's largest hot desert) is in Africa\nNile is the world's longest river — flows through Africa\nBound on all sides by oceans and seas",
          note: "",
        },
        {
          key: "North America",
          main: "Third largest continent\nLinked to South America by Isthmus of Panama (a very narrow strip of land)\nLies completely in the Northern and Western Hemisphere\nThree oceans surround it",
          note: "",
        },
        {
          key: "South America",
          main: "Lies mostly in the Southern Hemisphere\nAndes — world's longest mountain range, runs north to south through it\nAmazon — world's largest river by volume, flows through it",
          note: "Surrounded by the Atlantic Ocean (east) and Pacific Ocean (west)",
        },
        {
          key: "Australia",
          main: "Smallest continent\nLies entirely in the Southern Hemisphere\nSurrounded on all sides by oceans and seas\nCalled an 'island continent'",
          note: "",
        },
        {
          key: "Antarctica",
          main: "Completely in the Southern Hemisphere\nSouth Pole lies at the centre\nLocated in the South Polar Region\nPermanently covered with thick ice sheets\nNo permanent human settlements\nMany countries have research stations there\nIndia's research stations: Maitri and Bharati",
          note: "",
        },
        {
          key: "Isthmus vs Strait",
          main: "Isthmus: a narrow strip of LAND joining two landmasses (e.g. Isthmus of Panama)\nStrait: a narrow passage of WATER connecting two large water bodies like seas and oceans",
          note: "",
        },
        {
          key: "Hydrosphere",
          main: "The Earth is called the 'blue planet'\nMore than 71% of Earth's surface = water; 29% = land\nHydrosphere = water in all its forms (running water in rivers/oceans, ice in glaciers, underground water, water vapour in atmosphere)\nMore than 97% of Earth's water is in the oceans — too salty for human use\nOnly 2.5% is fresh water",
          note: "Despite being a 'blue planet', we face a shortage of fresh water",
        },
        {
          key: "Five Oceans (in order of size)",
          main: "1. Pacific Ocean — largest\n2. Atlantic Ocean\n3. Indian Ocean\n4. Southern Ocean\n5. Arctic Ocean — smallest",
          note: "Three chief movements of ocean water: waves, tides, and ocean currents",
        },
        {
          key: "Pacific Ocean",
          main: "Largest ocean — spread over one-third of the Earth\nMariana Trench (deepest part of Earth) lies here\nAlmost circular in shape\nAsia, Australia, North and South America surround it",
          note: "",
        },
        {
          key: "Atlantic Ocean",
          main: "Second largest ocean\n'S' shaped\nFlanked by North and South America on the west, and Europe and Africa on the east\nHighly indented coastline — ideal for natural harbours and ports\nBusiest ocean from the point of view of commerce",
          note: "",
        },
        {
          key: "Indian Ocean",
          main: "Only ocean named after a country — India\nShape is almost triangular\nBounded in the north by Asia, west by Africa, east by Australia",
          note: "",
        },
        {
          key: "Southern Ocean",
          main: "Encircles the continent of Antarctica\nExtends northward to 60 degrees south latitude",
          note: "",
        },
        {
          key: "Arctic Ocean",
          main: "Located within the Arctic Circle, surrounds the North Pole\nConnected with the Pacific Ocean by the Bering Strait (a narrow stretch of shallow water)\nBound by northern coasts of North America and Eurasia",
          note: "",
        },
        {
          key: "Atmosphere",
          main: "The Earth is surrounded by a layer of gas called the atmosphere\nExtends up to about 1,600 km height\nDivided into 5 layers (from Earth's surface): Troposphere, Stratosphere, Mesosphere, Thermosphere, Exosphere\nProtects Earth from harmful sun rays and provides air to breathe",
          note: "",
        },
        {
          key: "Composition of Atmosphere",
          main: "Nitrogen: 78%\nOxygen: 21%\nOther gases (CO₂, argon, etc.): 1%\nNitrogen + Oxygen = about 99% of clean dry air",
          note: "Oxygen = breath of life; Nitrogen = helps growth of living organisms; CO₂ = absorbs heat (keeps planet warm) + essential for plant growth",
        },
        {
          key: "Atmosphere — Key Properties",
          main: "Density maximum at sea level; decreases with height\nTemperature decreases as we go upward\nAtmosphere exerts pressure on Earth → varies from place to place (high and low pressure areas)\nAir moves from high pressure to low pressure → moving air = wind",
          note: "",
        },
        {
          key: "Biosphere — Domain of Life",
          main: "The narrow zone of contact between land, water, and air\nThe only zone where life exists\nContains all forms of life from microbes and bacteria to huge mammals\nOrganisms divided into plant kingdom and animal kingdom\nAll three domains (lithosphere, hydrosphere, atmosphere) interact with each other",
          note: "",
        },
        {
          key: "Human Impact on Domains",
          main: "Cutting forests → fast removal of soil from slopes\nDischarge of waste into lakes/rivers → water unsuitable for use\nEmissions from industries/vehicles → CO₂ increase → Global Warming\nNeed to maintain balance between the three domains",
          note: "",
        },
      ],
      traps: [
        {
          label: "Ocean Rankings (Largest to Smallest)",
          lines: [
            "1st: Pacific (largest, >1/3 of Earth), 2nd: Atlantic, 3rd: Indian, 4th: Southern, 5th: Arctic",
            "Busiest for commerce: Atlantic (NOT Pacific)",
            "Only ocean named after a country: Indian Ocean",
          ],
        },
        {
          label: "Continent Size Rankings",
          lines: [
            "1st: Asia (largest, 1/3 of land area), 2nd: Africa, 3rd: North America",
            "Smallest: Australia (also called island continent)",
            "Europe is much smaller than Asia",
          ],
        },
        {
          label: "Africa — Three Tropics",
          lines: [
            "Africa is the ONLY continent through which ALL THREE of these pass:",
            "Tropic of Cancer (23½°N), Equator (0°), Tropic of Capricorn (23½°S)",
            "Other continents have only 1 or 2 of these passing through them",
          ],
        },
        {
          label: "World Records (Rivers, Mountains, Deserts)",
          lines: [
            "Longest river: Nile (Africa)",
            "Longest mountain range: Andes (South America)",
            "Largest river by volume: Amazon (South America)",
            "Deepest point: Mariana Trench, Pacific Ocean (11,022 m)",
            "Highest peak: Mt. Everest (8,848 m)",
            "Largest hot desert: Sahara (Africa)",
          ],
        },
        {
          label: "Atmospheric Composition",
          lines: [
            "N₂ = 78%, O₂ = 21%, others = 1%",
            "Common trap: switching N₂ and O₂ percentages",
          ],
        },
        {
          label: "Freshwater vs Saltwater",
          lines: [
            "97%+ of water = in oceans (salty, unfit for human use)",
            "Only 2.5% = fresh water",
            "Most fresh water is locked in ice sheets/glaciers — very little available for human use",
          ],
        },
        {
          label: "India's Antarctic Research Stations",
          lines: [
            "Maitri and Bharati — India's research stations in Antarctica",
            "NOT 'Dakshin Gangotri' (that was India's first station, now decommissioned — not mentioned in this chapter)",
          ],
        },
      ],
      mainsAngle:
        "The interdependence of the four domains (lithosphere, hydrosphere, atmosphere, biosphere) is at the heart of contemporary environmental debates. Global warming (CO₂ → atmospheric domain → warming lithosphere → melting glaciers → hydrosphere changes → biosphere impacts) is a perfect example of cross-domain cascading effects, directly relevant to GS-3 Environment questions.",
      mainsTheme:
        "Interdependence of Earth's four domains — the scientific basis of environmental challenges",
      recall: [
        "4 domains: Lithosphere, Hydrosphere, Atmosphere, Biosphere",
        "Lithosphere = solid; Hydrosphere = water; Atmosphere = gas; Biosphere = zone of life",
        "7 continents; most land in Northern Hemisphere",
        "Asia = largest (1/3 land area); Africa = 2nd; Smallest = Australia (island continent)",
        "Africa: only continent with all 3 — Tropic of Cancer, Equator, Tropic of Capricorn",
        "Oceans: Pacific > Atlantic > Indian > Southern > Arctic",
        "Atlantic = 'S' shaped + busiest for commerce",
        "Indian Ocean = only ocean named after a country",
        "Mariana Trench (Pacific) = deepest (11,022m); Mt. Everest = highest (8,848m)",
        "Nile = longest river; Andes = longest mountain range; Amazon = largest river by volume",
        "Atmosphere: N₂ 78%, O₂ 21%; extends ~1,600 km; 5 layers",
        "5 layers: Troposphere, Stratosphere, Mesosphere, Thermosphere, Exosphere",
        "Earth's water: 97%+ saltwater; only 2.5% fresh",
        "India's Antarctica stations: Maitri + Bharati",
      ],
    },
  },
  quizzes: {
    "geo6-ch5": {
      title: "Major Domains of the Earth",
      questions: [
        {
          q: "Which of the following correctly defines the Lithosphere?",
          options: [
            "The gaseous layer surrounding the Earth",
            "The solid portion of the Earth comprising rocks of the crust and thin layers of soil",
            "The water bodies covering the Earth's surface",
            "The narrow zone where land, water and air meet",
          ],
          correct: 1,
          explain:
            "The Lithosphere is the solid portion, comprising the Earth's crust rocks and thin layers of soil that contain nutrients sustaining organisms.",
        },
        {
          q: [
            "Consider the following word origins:",
            "I. Lithos (Greek) = Stone",
            "II. Atmos (Greek) = Vapour",
            "III. Hudor (Greek) = Life",
            "IV. Bios (Greek) = Water",
            "How many of the above are correctly matched?",
          ],
          options: [
            "Only one pair",
            "Only two pairs",
            "Only three pairs",
            "All four pairs",
          ],
          correct: 1,
          explain:
            "Pairs I and II are correctly matched. Pair III is incorrect — Hudor means Water (not Life). Pair IV is incorrect — Bios means Life (not Water).",
        },
        {
          q: "The Earth is called the 'Blue Planet' because:",
          options: [
            "It appears blue due to its gaseous atmosphere",
            "More than 71% of its surface is covered by water",
            "The sky appears blue when viewed from space",
            "It has the most number of water bodies among all planets",
          ],
          correct: 1,
          explain:
            "The Earth is called the 'Blue Planet' because more than 71% of its surface is covered with water, making it appear blue from space.",
        },
        {
          q: "The Biosphere is best defined as:",
          options: [
            "The solid portion of the Earth",
            "The total water available on Earth",
            "The narrow zone where land, water and air meet and all forms of life exist",
            "The gaseous envelope surrounding the Earth",
          ],
          correct: 2,
          explain:
            "The Biosphere is the narrow zone of contact between land, water and air — it is the zone unique to this planet where life exists in all its forms.",
        },
        {
          q: "The highest mountain peak on Earth (Mt. Everest) is 8,848 metres high. The greatest ocean depth (Mariana Trench) is 11,022 metres. The Mariana Trench is located in which ocean?",
          options: [
            "Atlantic Ocean",
            "Indian Ocean",
            "Pacific Ocean",
            "Arctic Ocean",
          ],
          correct: 2,
          explain:
            "The Mariana Trench, the deepest point on Earth at 11,022 metres, is located in the Pacific Ocean.",
        },
        {
          q: "Which of the following is the ONLY continent through which the Tropic of Cancer, the Equator, AND the Tropic of Capricorn all pass?",
          options: ["Asia", "South America", "Africa", "Australia"],
          correct: 2,
          explain:
            "Africa is the only continent through which all three — Tropic of Cancer (23½°N), Equator (0°), and Tropic of Capricorn (23½°S) — pass.",
        },
        {
          q: [
            "Consider the following statements about Africa:",
            "I. It is the second largest continent after Asia.",
            "II. The Sahara Desert, the world's largest hot desert, is in Africa.",
            "III. The Nile, the world's longest river, flows through Africa.",
            "IV. Africa lies entirely in the Northern Hemisphere.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I, II and III only",
            "I and III only",
            "I, II, III and IV",
            "II and IV only",
          ],
          correct: 0,
          explain:
            "Statements I, II, and III are correct. Statement IV is incorrect — while a large part of Africa lies in the Northern Hemisphere, the Equator and Tropic of Capricorn also pass through it, meaning it extends into the Southern Hemisphere.",
        },
        {
          q: "The combined landmass of Europe and Asia is called:",
          options: ["Pangaea", "Gondwana", "Eurasia", "Laurasia"],
          correct: 2,
          explain:
            "The combined landmass of Europe and Asia is called Eurasia.",
        },
        {
          q: "Asia is separated from Europe by which geographical feature on the west?",
          options: [
            "Himalayan Mountains",
            "Alps Mountains",
            "Ural Mountains",
            "Caucasus Mountains",
          ],
          correct: 2,
          explain:
            "Asia is separated from Europe by the Ural Mountains on the west.",
        },
        {
          q: "Which continent is linked to South America by the Isthmus of Panama?",
          options: ["Asia", "Europe", "Africa", "North America"],
          correct: 3,
          explain:
            "North America is linked to South America by the very narrow Isthmus of Panama — a narrow strip of land joining two landmasses.",
        },
        {
          q: "Which of the following correctly describes Australia?",
          options: [
            "Second smallest continent, lies in the Northern Hemisphere",
            "Smallest continent, lies entirely in the Southern Hemisphere, called an island continent",
            "Third smallest continent, lies in both hemispheres",
            "Smallest continent, lies entirely in the Northern Hemisphere",
          ],
          correct: 1,
          explain:
            "Australia is the smallest continent, lies entirely in the Southern Hemisphere, and is called an 'island continent' because it is surrounded on all sides by oceans and seas.",
        },
        {
          q: "India's research stations in Antarctica are named:",
          options: [
            "Dakshin Gangotri and Maitri",
            "Maitri and Bharati",
            "Bharati and Himalaya",
            "Ganga and Bharati",
          ],
          correct: 1,
          explain:
            "India's research stations in Antarctica are Maitri and Bharati, as mentioned in Chapter 5. (Dakshin Gangotri was India's first station but has been decommissioned.)",
        },
        {
          q: [
            "Assertion (A): Despite being called the 'Blue Planet', we face a shortage of water.",
            "Reason (R): More than 97% of Earth's water is in the oceans and is too salty for human use, leaving only about 2.5% as fresh water — most of which is locked in ice sheets.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R directly explains A — the paradox of abundant water yet water scarcity is precisely explained by the fact that 97%+ is saltwater and most fresh water is inaccessible in glaciers.",
        },
        {
          q: "The five major oceans in order of their size (largest to smallest) are:",
          options: [
            "Pacific, Atlantic, Indian, Southern, Arctic",
            "Atlantic, Pacific, Indian, Arctic, Southern",
            "Pacific, Indian, Atlantic, Southern, Arctic",
            "Pacific, Atlantic, Southern, Indian, Arctic",
          ],
          correct: 0,
          explain:
            "In order of size: Pacific > Atlantic > Indian > Southern > Arctic.",
        },
        {
          q: "Which ocean is described as 'S' shaped and is considered the busiest from the point of view of commerce?",
          options: [
            "Pacific Ocean",
            "Atlantic Ocean",
            "Indian Ocean",
            "Southern Ocean",
          ],
          correct: 1,
          explain:
            "The Atlantic Ocean is 'S' shaped, flanked by North/South America on the west and Europe/Africa on the east, with a highly indented coastline that provides ideal natural harbours — making it the busiest ocean for commerce.",
        },
        {
          q: "Which is the only ocean named after a country?",
          options: [
            "Atlantic Ocean",
            "Pacific Ocean",
            "Indian Ocean",
            "Southern Ocean",
          ],
          correct: 2,
          explain:
            "The Indian Ocean is the only ocean in the world named after a country — India.",
        },
        {
          q: "The Arctic Ocean is connected with the Pacific Ocean by:",
          options: [
            "Strait of Malacca",
            "Bering Strait",
            "Strait of Gibraltar",
            "Strait of Hormuz",
          ],
          correct: 1,
          explain:
            "The Arctic Ocean is connected with the Pacific Ocean by the Bering Strait, a narrow stretch of shallow water.",
        },
        {
          q: [
            "Consider the following statements about the Atmosphere:",
            "I. It extends up to about 1,600 km.",
            "II. It is divided into five layers.",
            "III. Nitrogen comprises 78% and Oxygen 21% of clean, dry air.",
            "IV. Temperature increases as we go upward.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I, II and III only",
            "I, II, III and IV",
            "IV only",
            "I and III only",
          ],
          correct: 0,
          explain:
            "Statements I, II, and III are correct. Statement IV is incorrect — temperature DECREASES as we go upward, not increases.",
        },
        {
          q: "The five layers of the atmosphere, from Earth's surface upward, are:",
          options: [
            "Stratosphere, Troposphere, Mesosphere, Thermosphere, Exosphere",
            "Troposphere, Stratosphere, Mesosphere, Thermosphere, Exosphere",
            "Exosphere, Thermosphere, Mesosphere, Stratosphere, Troposphere",
            "Troposphere, Mesosphere, Stratosphere, Thermosphere, Exosphere",
          ],
          correct: 1,
          explain:
            "From Earth's surface upward: Troposphere → Stratosphere → Mesosphere → Thermosphere → Exosphere.",
        },
        {
          q: [
            "Carbon dioxide (CO₂) in the atmosphere is important because:",
            "I. It absorbs heat radiated by the Earth, thereby keeping the planet warm.",
            "II. It is essential for the growth of plants.",
            "III. It constitutes 21% of clean, dry air.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I and II only",
            "I, II and III",
            "II and III only",
            "I only",
          ],
          correct: 0,
          explain:
            "Statements I and II are correct. Statement III is incorrect — CO₂ is a trace gas comprising only about 1% of the atmosphere (along with other gases). Oxygen comprises 21%, not CO₂.",
        },
        {
          q: [
            "Assertion (A): An increase in the amount of CO₂ in the atmosphere leads to global warming.",
            "Reason (R): CO₂ absorbs heat radiated by the Earth, and as its concentration increases, more heat is retained in the atmosphere.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R correctly explains the greenhouse mechanism — CO₂ absorbs outgoing terrestrial radiation, and more CO₂ means more heat retained, leading to global warming.",
        },
        {
          q: "Which of the following pairs (Continent — Key Feature) is NOT correctly matched?",
          options: [
            "Africa — World's longest river (Nile)",
            "South America — World's longest mountain range (Andes)",
            "North America — Linked to South America by Isthmus of Panama",
            "Australia — Lies entirely in the Northern Hemisphere",
          ],
          correct: 3,
          explain:
            "Australia lies entirely in the SOUTHERN Hemisphere, not the Northern Hemisphere — this is the incorrectly matched pair.",
        },
        {
          q: [
            "Read the following passage:",
            "'The organisms in the biosphere may broadly be divided into the plant kingdom and the animal kingdom. The three domains of the earth interact with each other and affect each other in some way or the other. For example, cutting of forests for fulfilling our needs of wood, or clearing land for agriculture may lead to fast removal of soil from slopes.'",
            "Which of the following is most directly supported by this passage?",
          ],
          options: [
            "The three domains operate independently and do not affect one another",
            "Human activities affecting one domain (lithosphere — deforestation) can cause adverse effects in another (soil erosion)",
            "The biosphere encompasses only the plant kingdom",
            "Deforestation has no impact on the lithosphere",
          ],
          correct: 1,
          explain:
            "The passage directly illustrates cross-domain interaction — deforestation (affecting the biosphere) leads to soil erosion (affecting the lithosphere).",
        },
        {
          q: "An 'Isthmus' and a 'Strait' are related terms. Which of the following correctly distinguishes them?",
          options: [
            "Isthmus: narrow passage of water; Strait: narrow strip of land",
            "Isthmus: narrow strip of land joining two landmasses; Strait: narrow passage of water connecting two large water bodies",
            "Both terms describe narrow land features",
            "Both terms describe narrow water features",
          ],
          correct: 1,
          explain:
            "An Isthmus is a narrow strip of LAND joining two landmasses (e.g. Isthmus of Panama). A Strait is a narrow passage of WATER connecting two large water bodies (e.g. Bering Strait).",
        },
        {
          q: [
            "Consider the following statements:",
            "I. The Pacific Ocean is spread over one-third of the Earth.",
            "II. The Atlantic Ocean is the busiest ocean for commerce.",
            "III. The Indian Ocean is triangular in shape.",
            "IV. The Southern Ocean encircles Africa.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I, II and III only",
            "II and IV only",
            "I, II, III and IV",
            "I and III only",
          ],
          correct: 0,
          explain:
            "Statements I, II, and III are correct. Statement IV is incorrect — the Southern Ocean encircles ANTARCTICA, not Africa.",
        },
        {
          q: "Which of the following correctly explains why mountaineers carry oxygen cylinders at high altitudes?",
          options: [
            "Because oxygen concentration is zero above 8,000 metres",
            "Because the density of the atmosphere decreases with height, making the air thinner and oxygen harder to breathe in sufficient quantities",
            "Because temperatures at high altitudes are too cold for oxygen to exist",
            "Because winds blow oxygen away from high altitudes",
          ],
          correct: 1,
          explain:
            "The density of the atmosphere decreases as altitude increases — at high altitudes, the air is much thinner (lower pressure, lower oxygen density), making it very difficult to breathe adequate amounts of oxygen.",
        },
      ],
    },
  },
});
