// ═══════════════════════════════════════════════════════════
// CONTENT "gs1/geography/ncert/class7/ch6/ch6" — Auto-generated by build-bundle.js. DO NOT EDIT.
// Mirrors the source notes file js/data/gs1/geography/ncert/class7/ch6/ch6.js. Loaded on demand
// by js/engine/loader.js the first time one of its topics is opened.
// Edit the source under js/data/ and re-run: node build-bundle.js
// ═══════════════════════════════════════════════════════════
__registerContent("gs1/geography/ncert/class7/ch6/ch6", {
  notes: {
    "geo7-ch6": {
      era: "NCERT Class 7 — Geography (Our Environment), Chapter 6",
      significance: [
        "Amazon Basin and Ganga-Brahmaputra Basin are two of the most frequently tested human-environment regions in Prelims",
        "Specific facts: Amazon = largest river basin, Trans-Amazon highway (1970), slash-and-burn agriculture, Manioc as staple food — all individually testable",
        "Ganga-Brahmaputra Basin: one-horned rhinoceros (Brahmaputra plain), Bengal tiger (delta), Kolkata on Hooghly, Swachh Bharat Mission (2 Oct 2014), Namami Gange Programme",
        "Deodars and firs = coniferous trees; Bengal tiger in delta area; Kaziranga and Manas wildlife sanctuaries are direct match-the-following targets",
      ],
      features: [
        {
          key: "Amazon Basin — Location",
          main: "Located close to the equator, between 10°N and 10°S — called the equatorial region\nThe Amazon River flows from the mountains to the west and reaches the Atlantic Ocean to the east\nDrains portions of Brazil, Peru, Bolivia, Ecuador, Colombia and a small part of Venezuela\nThe Amazon Basin is the largest river basin in the world",
          note: "The place where a river flows into another body of water is called the river's MOUTH\nTributaries: small rivers joining the main river; main river + all tributaries drain an area = the river basin (catchment area)",
        },
        {
          key: "Amazon Basin — Climate",
          main: "Hot and wet climate throughout the year\nBoth day and nights are almost equally hot and humid\nThe skin feels sticky; temperature goes down but humidity remains high\nIt rains almost everyday",
          note: "",
        },
        {
          key: "Amazon — Rainforests",
          main: "Dense, thick forests\nForests form a 'roof' of leaves so thick that sunlight cannot reach the ground\nGround remains dark and damp; only shade-tolerant vegetation grows\nOrchids, bromeliads grow as plant parasites",
          note: "Bromeliads: special plants that store water in their leaves; frogs use these pockets of water to lay eggs",
        },
        {
          key: "Amazon — Flora and Fauna",
          main: "Rich in fauna: toucans (brilliantly coloured, oversized bills), macaw (humming birds), monkeys\nVarious reptiles and snakes: crocodiles, anaconda, boa constrictor, pythons\nPiranha fish: flesh-eating fish found in the rivers\nSloth and ant-eating tapirs are also found",
          note: "Basin is home to thousands of species of insects",
        },
        {
          key: "People of the Amazon Rainforests",
          main: "People grow most food in small areas after clearing some trees\nWomen hunt and fish along the rivers; women mainly grow crops\nMen hunt and fish\nStaple food: MANIOC (also known as cassava) — grows underground like a potato\nAlso eat queen ants and egg sacs; cash crops include coffee, maize, cocoa\nSlash and Burn agriculture (also called 'shifting cultivation')",
          note: "",
        },
        {
          key: "Slash and Burn Agriculture",
          main: "Farmers clear a piece of land by slashing/cutting trees and burning the bushes\nReleases nutrients into the soil; crops are grown for a few years\nAfter soil loses nutrients, land is abandoned; farmers clear another plot\nMeanwhile, young trees grow in the old field restoring soil fertility\nPeople can then return to it and start cultivating again",
          note: "",
        },
        {
          key: "Amazon — Housing",
          main: "Rainforests provide a lot of wood for houses\nSome families live in thatched houses shaped like beehives\nOther large apartment-like houses called 'Maloca' with a steeply slanting roof",
          note: "",
        },
        {
          key: "Amazon — Changing Life",
          main: "In older days, heart of the forest accessible only by river\n1970: Trans-Amazon highway made all parts accessible by road\nAircrafts and helicopters also used\nIndigenous population pushed out and forced to settle in new areas",
          note: "",
        },
        {
          key: "Destruction of Amazon Rainforests",
          main: "Developmental activities leading to gradual destruction of biologically diverse rainforests\nA large area disappearing annually in the Amazon basin\nTopsoil washed away as rains fall; lush forest turns into a barren landscape",
          note: "",
        },
        {
          key: "Ganga-Brahmaputra Basin — Location",
          main: "Formed by tributaries of Rivers Ganga and Brahmaputra together\nLies in the sub-tropical region between 10°N and 30°N latitudes\nTributaries of Ganga: Ghaghra, Son, Chambal, Gandak, Kosi\nPlains of the Ganga and Brahmaputra, mountains and foothills of Himalayas, and Sundarbans delta are the main features",
          note: "River Brahmaputra is known by different names in different places",
        },
        {
          key: "Ganga-Brahmaputra — Climate",
          main: "Dominated by monsoon climate\nMonsoon brings rains from mid-June to mid-September\nSummers are hot; winters are cool\nOx-bow lakes dot the plain area",
          note: "",
        },
        {
          key: "Ganga-Brahmaputra — Agriculture",
          main: "Main occupation of people where flat land is available = agriculture\nMain crop: PADDY (requires sufficient water; grown where rainfall amount is high)\nOther crops: wheat, maize, sorghum, gram, millets\nCash crops: sugarcane, jute\nBanana plantations in some areas\nWest Bengal and Assam: tea grown in plantations\nSilk produced through cultivation of silkworms in parts of Bihar and Assam\nMountain and hill slopes: terrace farming",
          note: "",
        },
        {
          key: "Ganga-Brahmaputra — Vegetation",
          main: "Plains: tropical deciduous trees (teak, sal, peepal)\nBrahmaputra plain: thick bamboo groves\nDelta area: mangrove forests (Sundarbans)\nUttarakhand, Sikkim, Arunachal Pradesh: coniferous trees — pine, deodar, fir",
          note: "Deodars and firs = coniferous trees (frequently tested in exercises)",
        },
        {
          key: "Ganga-Brahmaputra — Wildlife",
          main: "Elephants, tigers, deer and monkeys are common\nOne-horned rhinoceros: found in the BRAHMAPUTRA PLAIN\nDelta area: Bengal tiger and crocodiles found\nAquatic life: rohu, catla, hilsa fish\nFish and rice = staple diet of people in the area\nFresh waters: 'Susu' (blind dolphin) found in Ganga and Brahmaputra — indicator of river health",
          note: "",
        },
        {
          key: "Ganga-Brahmaputra — Cities",
          main: "Several big towns and cities\nAllahabad, Kanpur, Varanasi, Lucknow, Patna, and Kolkata — all with population more than 10 lakh — located along the Ganga\nKolkata is an important port on the River HOOGHLY",
          note: "",
        },
        {
          key: "Transport in Ganga-Brahmaputra Basin",
          main: "All four ways of transport well developed\nPlain areas: roadways and railways\nWaterways: effective along rivers\nKolkata: important port on River Hooghly\nPlain area also has a large number of airports",
          note: "",
        },
        {
          key: "Tourism in Ganga-Brahmaputra Basin",
          main: "Taj Mahal (banks of River Yamuna, Agra), Allahabad (confluence of Ganga and Yamuna), Buddhist stupas in UP and Bihar, Lucknow with its Imambara, Assam with Kaziranga and Manas wildlife sanctuaries, Arunachal Pradesh with distinct tribal culture",
          note: "",
        },
        {
          key: "Environmental Concerns",
          main: "Wastewater from towns and industries discharged into rivers → pollution of rivers\nSwachh Bharat Mission launched by Prime Minister of India on 2 October 2014 to achieve universal sanitation coverage\nNamami Ganga Programme initiated to conserve River Ganga",
          note: "",
        },
      ],
      traps: [
        {
          label: "Amazon Basin Location",
          lines: [
            "Amazon Basin = equatorial region (between 10°N and 10°S)",
            "Located in SOUTH AMERICA — NOT Africa or Asia",
            "River Amazon flows west to east → into the ATLANTIC OCEAN (not Pacific)",
          ],
        },
        {
          label: "Manioc (Cassava) vs Paddy",
          lines: [
            "Manioc (cassava) = staple food of AMAZON BASIN people",
            "Paddy = main crop of GANGA-BRAHMAPUTRA BASIN",
            "Do NOT swap these — the chapter's exercises test this distinction",
          ],
        },
        {
          label: "One-horned Rhinoceros Location",
          lines: [
            "One-horned rhinoceros = found in BRAHMAPUTRA PLAIN",
            "Bengal tiger = found in DELTA AREA",
            "This distinction is directly tested in the chapter exercises",
          ],
        },
        {
          label: "Kolkata is on the Hooghly",
          lines: [
            "Kolkata is on the River HOOGHLY — NOT the Ganga directly",
            "Exercise answer: Kolkata is located on the river Hooghly",
          ],
        },
        {
          label: "Deodars and Firs = Coniferous Trees",
          lines: [
            "Deodars and firs = CONIFEROUS trees (found in Uttarakhand, Sikkim, Arunachal Pradesh)",
            "Exercise directly asks: 'Deodars and firs are a type of — coniferous trees'",
          ],
        },
        {
          label: "Swachh Bharat Mission Date",
          lines: [
            "Swachh Bharat Mission launched: 2 October 2014",
            "Launched by the Prime Minister of India",
            "NOT to be confused with Namami Gange (river conservation)",
          ],
        },
        {
          label: "Trans-Amazon Highway",
          lines: [
            "Trans-Amazon Highway built in 1970",
            "Made all parts of the rainforest accessible",
            "This accelerated the forced displacement of indigenous populations",
          ],
        },
      ],
      mainsAngle:
        "This chapter illustrates the tension between development and ecological preservation at two extremes — the Amazon rainforest (rapid destruction due to road-building and agriculture) and the Ganga-Brahmaputra basin (river pollution from urban-industrial waste). Both are directly relevant to GS-3 Environment and Disaster Management questions on deforestation, river conservation (Namami Gange), and sustainable development.",
      mainsTheme:
        "Human-environment interaction in tropical and subtropical regions — development vs ecological balance",
      recall: [
        "Amazon Basin: equatorial region (10°N–10°S), South America, largest river basin in world",
        "Amazon flows into ATLANTIC OCEAN",
        "Staple food in Amazon: Manioc (cassava)",
        "Trans-Amazon highway: built in 1970",
        "Slash and burn agriculture: clears land, burns bushes, restores fertility by rotation",
        "Maloca: large apartment-like house with steeply slanting roof",
        "Piranha: flesh-eating fish of Amazon rivers",
        "Ganga-Brahmaputra: sub-tropical (10°N–30°N); monsoon climate (mid-June to mid-September)",
        "Main crop: Paddy; Cash crops: sugarcane, jute",
        "One-horned rhinoceros: Brahmaputra plain",
        "Bengal tiger + crocodiles: delta area",
        "Kolkata: on River Hooghly (important port)",
        "Deodars and firs: coniferous trees",
        "Susu (blind dolphin): Ganga and Brahmaputra; indicator of river health",
        "Swachh Bharat Mission: 2 October 2014",
        "Namami Gange: to conserve River Ganga",
      ],
    },
  },
  quizzes: {
    "geo7-ch6": {
      title: "Human Environment Interactions: Tropical and Subtropical Region",
      questions: [
        {
          q: "The Amazon Basin lies in which latitudinal range, and is referred to as:",
          options: [
            "Between 10°N and 10°S; called the equatorial region",
            "Between 10°N and 30°N; called the sub-tropical region",
            "Between 0° and 23½°N; called the tropical region",
            "Between 23½°N and 66½°N; called the temperate region",
          ],
          correct: 0,
          explain:
            "The Amazon Basin lies between 10°N and 10°S, close to the equator — hence it is referred to as the equatorial region.",
        },
        {
          q: "The Amazon River drains portions of which countries?",
          options: [
            "Brazil, Peru, Bolivia, Ecuador, Colombia, and a small part of Venezuela",
            "Argentina, Chile, Uruguay, Paraguay, and Bolivia",
            "Mexico, Guatemala, Honduras, and Nicaragua",
            "India, Bangladesh, Nepal, and Bhutan",
          ],
          correct: 0,
          explain:
            "The Amazon Basin drains portions of Brazil, Peru, Bolivia, Ecuador, Colombia and a small part of Venezuela.",
        },
        {
          q: "The Amazon River flows from the mountains in the west and reaches which ocean in the east?",
          options: [
            "Pacific Ocean",
            "Indian Ocean",
            "Atlantic Ocean",
            "Arctic Ocean",
          ],
          correct: 2,
          explain:
            "The Amazon River flows from the Andes mountains in the west to the Atlantic Ocean in the east.",
        },
        {
          q: "The Amazon Basin is described as the largest river basin in the world because:",
          options: [
            "It has the longest river",
            "The Amazon River and all its tributaries together drain the largest catchment area in the world",
            "It has the most number of tributaries",
            "It receives the most rainfall of any basin",
          ],
          correct: 1,
          explain:
            "The Amazon Basin is the world's largest river basin because the Amazon River plus all its tributaries (catchment area) cover an enormous area — larger than any other river basin.",
        },
        {
          q: [
            "Assertion (A): Only shade-tolerant vegetation can grow on the floor of the Amazon rainforest.",
            "Reason (R): The forest canopy is so thick and dense that sunlight cannot reach the ground, keeping it dark and damp.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R correctly explains A — the dense 'roof' of leaves created by the canopy prevents sunlight from reaching the ground, which is why only shade-tolerant plants like orchids and bromeliads can grow there.",
        },
        {
          q: "The staple food of the people of the Amazon Basin is:",
          options: ["Paddy", "Manioc (cassava)", "Wheat", "Maize"],
          correct: 1,
          explain:
            "Manioc (also known as cassava) is the staple food of the Amazon Basin people — it grows underground like a potato.",
        },
        {
          q: "In 'slash and burn agriculture' (shifting cultivation), why is the land abandoned after a few years?",
          options: [
            "Because the farmers move to cities",
            "Because flooding destroys the crops",
            "Because the soil loses its nutrients after repeated use and needs time to recover",
            "Because government regulations prevent continued farming",
          ],
          correct: 2,
          explain:
            "After repeatedly using a patch of land, the soil loses its nutrients. The land is then abandoned; the farmer clears a new plot. Meanwhile, young trees grow in the old field and restore soil fertility, allowing farmers to return later.",
        },
        {
          q: "The large apartment-like houses of the Amazon people with a steeply slanting roof are called:",
          options: ["Igloos", "Maloca", "Thatched huts", "Bromeliads"],
          correct: 1,
          explain:
            "Large apartment-like houses with steeply slanting roofs are called 'Maloca'. Some families also live in thatched houses shaped like beehives.",
        },
        {
          q: "The Trans-Amazon Highway, built in 1970, was significant because it:",
          options: [
            "Helped indigenous populations expand their traditional farming practices",
            "Made all parts of the Amazon rainforest accessible by road, accelerating the displacement of indigenous populations",
            "Created a protected corridor for Amazonian wildlife",
            "Connected the Amazon Basin to the Pacific Ocean directly",
          ],
          correct: 1,
          explain:
            "The Trans-Amazon Highway (1970) made the entire rainforest accessible, but it also caused the indigenous population to be pushed out and forced to settle in new areas.",
        },
        {
          q: "Which of the following is a flesh-eating fish found in the rivers of the Amazon Basin?",
          options: ["Rohu", "Hilsa", "Piranha", "Catla"],
          correct: 2,
          explain:
            "Piranha is the flesh-eating fish found in the rivers of the Amazon Basin. Rohu, hilsa, and catla are fish of the Ganga-Brahmaputra basin.",
        },
        {
          q: "The Ganga-Brahmaputra Basin lies in which latitudinal range and is classified as:",
          options: [
            "Between 10°N and 10°S; equatorial region",
            "Between 10°N and 30°N; sub-tropical region",
            "Between 23½°N and 66½°N; temperate region",
            "Between 0° and 30°S; southern hemisphere subtropical",
          ],
          correct: 1,
          explain:
            "The Ganga-Brahmaputra Basin lies in the sub-tropical region between 10°N and 30°N latitudes.",
        },
        {
          q: [
            "Consider the following tributaries and their parent rivers:",
            "I. Ghaghra, Son, Chambal, Gandak, Kosi — tributaries of the Ganga",
            "II. The Amazon Basin tributaries join the Amazon River from the north and south",
            "Which of the statements given above is/are correct?",
          ],
          options: ["I only", "II only", "Both I and II", "Neither I nor II"],
          correct: 0,
          explain:
            "Statement I is correct — Ghaghra, Son, Chambal, Gandak, and Kosi are all tributaries of the Ganga. Statement II is a generalisation not specifically stated in the chapter — the chapter focuses on Statement I's detail.",
        },
        {
          q: "The main crop of the Ganga-Brahmaputra Basin and the reason it is grown in high-rainfall areas is:",
          options: [
            "Wheat; because it requires dry conditions",
            "Paddy; because its cultivation requires sufficient water and high amounts of rainfall",
            "Maize; because it can grow in all climate types",
            "Jute; because it is the most profitable cash crop",
          ],
          correct: 1,
          explain:
            "Paddy is the main crop of the Ganga-Brahmaputra plains. It requires sufficient water, so it is grown in areas where the amount of rainfall is high.",
        },
        {
          q: "Which of the following correctly pairs a product/activity with its location in the Ganga-Brahmaputra Basin?",
          options: [
            "Tea — grown in plantations in West Bengal and Assam",
            "Silk — produced in parts of Gujarat and Rajasthan",
            "One-horned rhinoceros — found in the delta area",
            "Bengal tiger — found in the Brahmaputra plain",
          ],
          correct: 0,
          explain:
            "Tea is grown in West Bengal and Assam. Silk is produced in Bihar and Assam. One-horned rhinoceros is in the BRAHMAPUTRA PLAIN (not delta). Bengal tiger is in the DELTA AREA — the exercise directly tests these distinctions.",
        },
        {
          q: "The one-horned rhinoceros is found in which part of the Ganga-Brahmaputra Basin?",
          options: [
            "The delta area",
            "The mountain foothills",
            "The Brahmaputra plain",
            "The western dry areas",
          ],
          correct: 2,
          explain:
            "The one-horned rhinoceros is found specifically in the Brahmaputra plain. Bengal tiger and crocodiles are found in the delta area.",
        },
        {
          q: "Kolkata is an important port located on which river?",
          options: [
            "River Ganga",
            "River Brahmaputra",
            "River Yamuna",
            "River Hooghly",
          ],
          correct: 3,
          explain:
            "Kolkata is an important port located on the River Hooghly — this is a directly testable detail that exercises ask as a 'tick the correct answer' question.",
        },
        {
          q: [
            "Consider the following pairs (Tree type — Classification):",
            "I. Deodars and firs — Coniferous trees",
            "II. Teak and sal — Tropical deciduous trees",
            "III. Bamboo — Coniferous trees",
            "How many of the above pairs are correctly matched?",
          ],
          options: [
            "Only one pair",
            "Only two pairs",
            "All three pairs",
            "None of the pairs",
          ],
          correct: 1,
          explain:
            "Pairs I and II are correctly matched. Pair III is incorrect — bamboo is NOT a coniferous tree; bamboo groves are thick in the Brahmaputra plain but bamboo is a grass, not a conifer.",
        },
        {
          q: "The 'Susu' or blind dolphin found in the Ganga and Brahmaputra rivers is significant because:",
          options: [
            "It is the largest freshwater mammal in India",
            "Its presence is an indication of the health of the river",
            "It was introduced from the Amazon Basin",
            "It feeds exclusively on piranha fish",
          ],
          correct: 1,
          explain:
            "The Susu (blind dolphin) is a bio-indicator — its presence indicates the health of the river. Its populations are declining due to untreated industrial and urban waste with high amounts of chemicals.",
        },
        {
          q: "The Swachh Bharat Mission was launched on:",
          options: [
            "15 August 2014",
            "26 January 2015",
            "2 October 2014",
            "5 June 2014",
          ],
          correct: 2,
          explain:
            "The Swachh Bharat Mission was launched by the Prime Minister of India on 2nd October 2014 to accelerate efforts towards universal sanitation coverage.",
        },
        {
          q: "Which programme was initiated specifically to conserve River Ganga?",
          options: [
            "Swachh Bharat Mission",
            "Namami Gange Programme",
            "National River Linking Project",
            "Jal Jeevan Mission",
          ],
          correct: 1,
          explain:
            "The 'Namami Gange' Programme has been initiated specifically to conserve the River Ganga — distinct from the Swachh Bharat Mission which focuses on sanitation broadly.",
        },
      ],
    },
  },
});
