// ═══════════════════════════════════════════════════════════
// CONTENT "gs1/geography/ncert/class6/ch1/ch1" — Auto-generated by build-bundle.js. DO NOT EDIT.
// Mirrors the source notes file js/data/gs1/geography/ncert/class6/ch1/ch1.js. Loaded on demand
// by js/engine/loader.js the first time one of its topics is opened.
// Edit the source under js/data/ and re-run: node build-bundle.js
// ═══════════════════════════════════════════════════════════
__registerContent("gs1/geography/ncert/class6/ch1/ch1", {
  notes: {
    "geo6-ch1": {
      era: "NCERT Class 6 — Geography, Chapter 1",
      significance: [
        "Foundational chapter for the entire Geography syllabus — defines celestial bodies, the solar system's structure, and the Earth's unique position within it",
        "Distances, orbital periods, and rotation periods from this chapter are among the most frequently tested static facts in Prelims",
        "Establishes core vocabulary (star, planet, satellite, asteroid, meteoroid, galaxy) used throughout higher-level Geography and even some Science-based Prelims questions",
      ],
      features: [
        {
          key: "Celestial Bodies",
          main: "The sun, the moon, and all objects shining in the night sky are called celestial bodies",
          note: "",
        },
        {
          key: "Stars",
          main: "Very big, hot celestial bodies made up of gases, with their own heat and light\nThe Sun is a star",
          note: "Other stars appear tiny and give no felt heat/light because they are extremely far away",
        },
        {
          key: "Constellations",
          main: "Patterns formed by different groups of stars\nUrsa Major (Big Bear) is one such constellation",
          note: "Saptarishi ('seven sages') — a group of 7 stars forming part of Ursa Major",
        },
        {
          key: "Pole Star (North Star)",
          main: "Indicates the north direction; always remains in the same position in the sky\nLocated using the Saptarishi's pointer stars",
          note: "Used historically to determine direction at night",
        },
        {
          key: "Planets",
          main: "Celestial bodies with NO heat/light of their own — lit by starlight\nWord 'planet' comes from Greek 'Planetai' meaning 'wanderers'\nEarth is a planet, getting its heat & light from the Sun",
          note: "",
        },
        {
          key: "Satellites",
          main: "A celestial body that moves around a planet, the way planets move around the Sun\nThe Moon is Earth's (only) natural satellite",
          note: "Human-made satellites are artificial bodies, carried by rockets, placed in orbit for communication/data-gathering — e.g. INSAT, IRS, EDUSAT (Indian satellites)",
        },
        {
          key: "The Solar System",
          main: "Sun + 8 planets + satellites + asteroids + meteoroids = the Solar System (a 'solar family' with the Sun as its head)",
          note: "",
        },
        {
          key: "The Sun",
          main: "Centre of the Solar System; huge, made of extremely hot gases\nProvides the pulling (gravitational) force binding the Solar System; ultimate source of heat & light",
          note: "About 150 million km from Earth",
        },
        {
          key: "The 8 Planets (in order from Sun)",
          main: "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune\nMnemonic: 'My Very Efficient Mother Just Served Us Nuts'",
          note: "All planets move around the Sun in fixed, elongated paths called orbits",
        },
        {
          key: "Mercury",
          main: "Nearest planet to the Sun; distance from Sun ≈ 58 million km\nTakes only ~88 days to complete one orbit",
          note: "",
        },
        {
          key: "Venus",
          main: "Called 'Earth's twin' — size and shape very similar to Earth's\nDistance from Sun ≈ 108 million km",
          note: "",
        },
        {
          key: "Earth",
          main: "3rd nearest planet to the Sun; 5th largest planet\nSlightly flattened at the poles → shape described as a Geoid (earth-like shape)\nDistance from Sun ≈ 150 million km",
          note: "Unique due to: not too hot/cold, presence of water & air, oxygen (life-supporting gas)",
        },
        {
          key: "Earth as 'Blue Planet'",
          main: "Appears blue from outer space because two-thirds of its surface is covered by water",
          note: "",
        },
        { key: "Mars", main: "Distance from Sun ≈ 228 million km", note: "" },
        {
          key: "Jupiter",
          main: "Largest planet; distance from Sun ≈ 778 million km",
          note: "Has rings (belts of small debris), visible from Earth via powerful telescopes",
        },
        {
          key: "Saturn",
          main: "Distance from Sun ≈ 1,427 million km",
          note: "Has rings, visible from Earth via powerful telescopes",
        },
        {
          key: "Uranus",
          main: "Distance from Sun ≈ 2,869 million km",
          note: "Has rings, visible from Earth via powerful telescopes",
        },
        {
          key: "Neptune",
          main: "Farthest planet from the Sun; distance from Sun ≈ 4,496 million km",
          note: "",
        },
        {
          key: "Pluto — Dwarf Planet",
          main: "Considered a planet until August 2006\nInternational Astronomical Union reclassified it (along with Ceres, 2003 UB313) as a 'dwarf planet'",
          note: "",
        },
        {
          key: "The Moon",
          main: "Earth's only natural satellite; diameter ≈ 1/4 of Earth's\nDistance from Earth ≈ 3,84,400 km\nOrbits Earth in ~27 days, and also SPINS on its axis in ~27 days",
          note: "Because orbit period = spin period, only ONE side of the Moon is ever visible from Earth",
        },
        {
          key: "Moon's Surface",
          main: "No conditions favourable for life\nHas mountains, plains, and depressions, which cast shadows visible from Earth",
          note: "",
        },
        {
          key: "Asteroids",
          main: "Numerous tiny bodies that move around the Sun\nFound in the Asteroid Belt — between the orbits of Mars and Jupiter",
          note: "Scientists believe asteroids are parts of a planet that exploded long ago",
        },
        {
          key: "Meteoroids",
          main: "Small pieces of rock that move around the Sun\nWhen they near Earth and fall, friction with air heats/burns them, causing a flash of light ('meteor' / shooting star)",
          note: "A meteoroid not fully burnt may fall on Earth and create a hollow (crater)",
        },
        {
          key: "Milky Way Galaxy",
          main: "The whitish broad band across a clear starry night sky — a cluster of millions of stars\nOur Solar System is part of this galaxy",
          note: "In ancient India, imagined as a river of light in the sky, named Akash Ganga",
        },
        {
          key: "Galaxy & Universe",
          main: "A galaxy = a huge system of billions of stars + clouds of dust and gases\nMillions of such galaxies together make up the Universe",
          note: "",
        },
        {
          key: "Full Moon & New Moon",
          main: "Full Moon Night (Poornima) — moon fully visible, occurs once about every month\nNew Moon Night (Amavasya) — moon not visible at all, a fortnight after Poornima",
          note: "New Moon night is best for observing the night sky clearly",
        },
        {
          key: "First Moon Landing",
          main: "Neil Armstrong — first human to step on the Moon's surface, on 20 July 1969",
          note: "",
        },
      ],
      traps: [
        {
          label: "Distance Order Trap (memorise exact figures)",
          lines: [
            "Mercury 58 → Venus 108 → Earth 150 → Mars 228 (million km from Sun)",
            "Jupiter 778 → Saturn 1,427 → Uranus 2,869 → Neptune 4,496",
            "UPSC may ask 'which planet is X million km from the Sun' or rank planets by distance",
          ],
        },
        {
          label: "Orbit Period vs Spin Period",
          lines: [
            "'One orbit around Sun' (revolution) ≠ 'one spin on axis' (rotation) — don't confuse the two",
            "Mercury: orbit 88 days, spin 59 days",
            "Venus: orbit 255 days, spin 243 days (spin is SLOWER than a Mercury year!)",
            "Earth: orbit 365 days, spin 1 day",
          ],
        },
        {
          label: "Moon: Orbit = Spin (unique among these)",
          lines: [
            "The Moon orbits Earth in ~27 days AND spins on its axis in ~27 days",
            "This equality is WHY only one side of the Moon is ever visible from Earth",
            "Don't confuse this with planets, where orbit and spin periods are usually very different",
          ],
        },
        {
          label: "Star vs Planet vs Satellite",
          lines: [
            "Star = own heat & light (e.g. Sun)",
            "Planet = NO own heat/light, lit by a star, orbits a star (e.g. Earth)",
            "Satellite = orbits a PLANET, not a star (e.g. Moon orbits Earth)",
          ],
        },
        {
          label: "Pluto Reclassification",
          lines: [
            "Pluto was a planet UNTIL August 2006",
            "Reclassified as a 'dwarf planet' by the International Astronomical Union",
            "Other dwarf planets mentioned: Ceres, 2003 UB313",
          ],
        },
        {
          label: "Asteroids vs Meteoroids",
          lines: [
            "Asteroids: bigger, found in the belt between Mars and Jupiter, orbit the Sun continuously",
            "Meteoroids: smaller ROCK pieces; when they enter Earth's atmosphere they burn up (flash of light) or create a crater",
          ],
        },
        {
          label: "Number of Moons (from the table)",
          lines: [
            "Earth = 1 moon; Mars = 2 moons",
            "Jupiter ≈ 53 moons; Saturn ≈ 53 moons (approximately equal!)",
            "Uranus ≈ 27 moons; Neptune = 13 moons",
            "Mercury & Venus = 0 moons (not listed with any moon count)",
          ],
        },
      ],
      mainsAngle:
        "While this NCERT chapter is primarily a Prelims-facts chapter (distances, orbital data, classification), its core theme — Earth's rare combination of conditions (temperature, water, oxygen) enabling life — connects to broader GS-1/GS-3 discussions on planetary habitability, the search for exoplanets, and India's own space exploration programme (ISRO's planetary missions).",
      mainsTheme:
        "Earth's habitability as a 'unique planet' — foundational concept for broader space & environment discussions",
      recall: [
        "8 planets: My Very Efficient Mother Just Served Us Nuts",
        "Sun–Earth distance ≈ 150 million km",
        "Earth = 3rd from Sun, 5th largest, shape = Geoid",
        "Earth = 'Blue Planet' (2/3 water-covered)",
        "Moon: orbit period = spin period ≈ 27 days → same side always visible",
        "Asteroid belt: between Mars & Jupiter",
        "Pluto → dwarf planet since Aug 2006",
        "Pole Star located via Saptarishi's pointer stars",
        "Neil Armstrong — first Moon landing, 20 July 1969",
        "Milky Way = our galaxy; Akash Ganga (ancient Indian name)",
        "Indian satellites: INSAT, IRS, EDUSAT",
      ],
    },
  },
  quizzes: {
    "geo6-ch1": {
      title: "The Earth in the Solar System",
      questions: [
        {
          q: "Which of the following best defines a 'celestial body'?",
          options: [
            "Only planets and their moons",
            "The sun, the moon, and all objects shining in the night sky",
            "Only stars visible without a telescope",
            "Only human-made satellites",
          ],
          correct: 1,
          explain:
            "Celestial bodies include the sun, moon, and all shining objects in the night sky — a broad category covering stars, planets, satellites, asteroids, and meteoroids.",
        },
        {
          q: [
            "Consider the following statements regarding stars:",
            "I. Stars are made up of extremely hot gases.",
            "II. Stars have their own heat and light.",
            "III. All stars appear small because they are inherently smaller than planets.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I and II only",
            "II and III only",
            "I, II and III",
            "I only",
          ],
          correct: 0,
          explain:
            "Statements I and II are correct. Statement III is incorrect — stars appear small/tiny because of their extreme DISTANCE from us, not because they are inherently small; in fact the Sun (a star) is far larger than Earth.",
        },
        {
          q: "The Sun is classified as a:",
          options: ["Planet", "Star", "Satellite", "Dwarf planet"],
          correct: 1,
          explain:
            "The Sun is a star — a huge, hot celestial body made of gases with its own heat and light.",
        },
        {
          q: "A 'constellation' is best defined as:",
          options: [
            "A single very bright star",
            "A pattern formed by a group of stars",
            "Another name for a galaxy",
            "A belt of asteroids",
          ],
          correct: 1,
          explain:
            "A constellation is a pattern formed by different groups of stars, such as Ursa Major.",
        },
        {
          q: "The Saptarishi, a group of seven stars, forms part of which constellation?",
          options: [
            "Orion",
            "Ursa Major (Big Bear)",
            "Ursa Minor",
            "Cassiopeia",
          ],
          correct: 1,
          explain:
            "The Saptarishi is a group of seven stars forming part of the Ursa Major (Big Bear) constellation.",
        },
        {
          q: [
            "Assertion (A): The Pole Star (North Star) has historically been used to determine direction at night.",
            "Reason (R): The Pole Star always remains in the same position in the sky.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R directly explains A — the Pole Star's fixed position is precisely why it could reliably indicate the north direction for navigation.",
        },
        {
          q: "The position of the Pole Star can be located with the help of which group of stars?",
          options: [
            "Orion's Belt",
            "The Saptarishi (pointer stars)",
            "The Milky Way band",
            "The Asteroid Belt",
          ],
          correct: 1,
          explain:
            "An imaginary line joining the Saptarishi's 'pointer stars' and extended further points to the Pole Star.",
        },
        {
          q: "Which of the following correctly distinguishes a planet from a star?",
          options: [
            "Planets have their own heat and light; stars do not",
            "Planets have NO heat/light of their own and are lit by starlight; stars have their own heat and light",
            "Both planets and stars generate their own heat and light equally",
            "There is no meaningful difference between the two",
          ],
          correct: 1,
          explain:
            "This is the fundamental distinction — planets are lit by reflected/received starlight, while stars generate their own heat and light.",
        },
        {
          q: "The word 'planet' is derived from the Greek word 'Planetai', which means:",
          options: [
            "Shining objects",
            "Wanderers",
            "Fixed stars",
            "Giant bodies",
          ],
          correct: 1,
          explain:
            "'Planetai' means 'wanderers' — reflecting how planets appear to move against the fixed backdrop of stars.",
        },
        {
          q: "A 'satellite' is best defined as a celestial body that:",
          options: [
            "Moves around the Sun directly, like a planet",
            "Moves around a planet, in the same way planets move around the Sun",
            "Generates its own heat and light",
            "Is found only in the asteroid belt",
          ],
          correct: 1,
          explain:
            "A satellite orbits a planet, analogous to how planets orbit the Sun — the Moon is Earth's natural satellite.",
        },
        {
          q: "Which of the following are examples of Indian human-made satellites?",
          options: [
            "INSAT, IRS, EDUSAT",
            "Sputnik, Apollo, Voyager",
            "Hubble, Kepler, Chandra",
            "Artemis, Orion, Gemini",
          ],
          correct: 0,
          explain:
            "INSAT, IRS, and EDUSAT are examples of Indian satellites mentioned in the chapter.",
        },
        {
          q: [
            "Consider the following statements regarding the composition of the Solar System:",
            "I. It consists of the Sun, eight planets, and satellites.",
            "II. It also includes asteroids and meteoroids.",
            "III. Pluto is officially counted among the eight planets of the Solar System.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I and II only",
            "I, II and III",
            "II and III only",
            "I only",
          ],
          correct: 0,
          explain:
            "Statements I and II are correct. Statement III is incorrect — Pluto was reclassified as a 'dwarf planet' in August 2006 and is not among the eight planets.",
        },
        {
          q: "What force does the Sun provide that binds the Solar System together?",
          options: [
            "Magnetic force",
            "The pulling (gravitational) force",
            "Nuclear force",
            "Electrostatic force",
          ],
          correct: 1,
          explain:
            "The Sun provides the pulling (gravitational) force that binds the entire Solar System together.",
        },
        {
          q: "The approximate distance between the Sun and the Earth is:",
          options: [
            "108 million km",
            "150 million km",
            "228 million km",
            "778 million km",
          ],
          correct: 1,
          explain:
            "The Sun is approximately 150 million km away from the Earth.",
        },
        {
          q: "Which of the following correctly lists the eight planets of the Solar System in order of increasing distance from the Sun?",
          options: [
            "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune",
            "Venus, Mercury, Earth, Mars, Saturn, Jupiter, Neptune, Uranus",
            "Mercury, Earth, Venus, Mars, Jupiter, Uranus, Saturn, Neptune",
            "Mercury, Venus, Mars, Earth, Jupiter, Saturn, Neptune, Uranus",
          ],
          correct: 0,
          explain:
            "The correct order, matching the mnemonic 'My Very Efficient Mother Just Served Us Nuts', is Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.",
        },
        {
          q: "Which planet is nearest to the Sun, and approximately how long does it take to complete one orbit?",
          options: [
            "Venus; about 255 days",
            "Mercury; about 88 days",
            "Earth; about 365 days",
            "Mars; about 687 days",
          ],
          correct: 1,
          explain:
            "Mercury is nearest to the Sun and takes about 88 days to complete one orbit.",
        },
        {
          q: "Which planet is often referred to as 'Earth's twin' because of its similar size and shape?",
          options: ["Mars", "Venus", "Mercury", "Jupiter"],
          correct: 1,
          explain:
            "Venus is called 'Earth's twin' due to its size and shape being very similar to Earth's.",
        },
        {
          q: [
            "Consider the following pairs of planets and their approximate distance from the Sun (in million km):",
            "I. Mars — 228",
            "II. Jupiter — 1,427",
            "III. Neptune — 4,496",
            "How many of the above pairs are correctly matched?",
          ],
          options: [
            "Only one pair",
            "Only two pairs",
            "All three pairs",
            "None of the pairs",
          ],
          correct: 1,
          explain:
            "Pairs I and III are correctly matched. Pair II is incorrect — Jupiter's distance is approximately 778 million km; 1,427 million km is Saturn's distance.",
        },
        {
          q: "The Earth is the ____ nearest planet to the Sun and the ____ largest planet in the Solar System.",
          options: [
            "third; fifth",
            "fifth; third",
            "second; fourth",
            "fourth; fifth",
          ],
          correct: 0,
          explain:
            "The Earth is the third nearest planet to the Sun and the fifth largest planet overall.",
        },
        {
          q: "The Earth's shape is described as a 'Geoid' primarily because:",
          options: [
            "It is a perfect sphere",
            "It is slightly flattened at the poles",
            "It has continents and oceans",
            "It rotates on a tilted axis",
          ],
          correct: 1,
          explain:
            "'Geoid' (earth-like shape) describes the Earth's actual shape, which is slightly flattened at the poles rather than a perfect sphere.",
        },
        {
          q: "Which of the following is NOT among the reasons the chapter gives for Earth being called a 'unique planet'?",
          options: [
            "Presence of water",
            "Presence of life-supporting gases like oxygen",
            "Neither too hot nor too cold",
            "Presence of visible rings",
          ],
          correct: 3,
          explain:
            "Visible rings are a feature of Jupiter, Saturn, and Uranus — NOT a reason cited for Earth's uniqueness. Earth's uniqueness stems from its temperature balance, water, and oxygen-rich air.",
        },
        {
          q: "The Earth is called the 'Blue Planet' because:",
          options: [
            "Its atmosphere scatters blue light exclusively",
            "Two-thirds of its surface is covered by water",
            "It appears blue due to its core temperature",
            "Its polar ice caps are blue in colour",
          ],
          correct: 1,
          explain:
            "The Earth appears blue from outer space because two-thirds of its surface is covered by water.",
        },
        {
          q: "Which planet has rings around it, as visible with powerful telescopes?",
          options: [
            "Only Saturn",
            "Jupiter, Saturn, and Uranus",
            "Only Jupiter and Mars",
            "Mercury, Venus, and Mars",
          ],
          correct: 1,
          explain:
            "Jupiter, Saturn, and Uranus all have rings — belts of small debris — visible from Earth with powerful telescopes.",
        },
        {
          q: [
            "Consider the following statements regarding Pluto:",
            "I. It was considered a planet until August 2006.",
            "II. It was reclassified as a 'dwarf planet' by the International Astronomical Union.",
            "III. Ceres and 2003 UB313 were reclassified alongside Pluto.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I and II only",
            "I, II and III",
            "II and III only",
            "I only",
          ],
          correct: 1,
          explain:
            "All three statements are correct — Pluto's 2006 reclassification alongside Ceres and 2003 UB313 into the 'dwarf planet' category is a frequently tested fact.",
        },
        {
          q: "The Moon's diameter is approximately what fraction of the Earth's diameter?",
          options: ["One-half", "One-third", "One-quarter", "One-tenth"],
          correct: 2,
          explain:
            "The Moon's diameter is only about one-quarter that of the Earth's.",
        },
        {
          q: "The Moon is approximately how far from the Earth?",
          options: [
            "1,50,000 km",
            "3,84,400 km",
            "5,00,000 km",
            "10,00,000 km",
          ],
          correct: 1,
          explain:
            "The Moon is about 3,84,400 km away from the Earth — vastly closer than the Sun (150 million km).",
        },
        {
          q: [
            "Assertion (A): Only one side of the Moon is ever visible from Earth.",
            "Reason (R): The Moon's orbital period around Earth and its rotational (spin) period on its own axis are both approximately 27 days.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R directly explains A — because the Moon's orbit and spin periods are equal (~27 days each), the same face always points toward Earth.",
        },
        {
          q: "Which of the following features are found on the Moon's surface?",
          options: [
            "Oceans and rivers only",
            "Mountains, plains, and depressions",
            "Dense forests",
            "Polar ice caps only",
          ],
          correct: 1,
          explain:
            "The Moon's surface has mountains, plains, and depressions, which cast shadows visible from Earth.",
        },
        {
          q: "Asteroids are found primarily in the belt located between the orbits of which two planets?",
          options: [
            "Earth and Mars",
            "Mars and Jupiter",
            "Jupiter and Saturn",
            "Venus and Earth",
          ],
          correct: 1,
          explain:
            "The Asteroid Belt lies between the orbits of Mars and Jupiter.",
        },
        {
          q: "According to the chapter, what do scientists believe about the origin of asteroids?",
          options: [
            "They are fragments of comets",
            "They are parts of a planet that exploded many years back",
            "They are debris from the Moon",
            "They originated from the Sun's outer layers",
          ],
          correct: 1,
          explain:
            "Scientists are of the view that asteroids are parts of a planet which exploded many years back.",
        },
        {
          q: "Which of the following correctly distinguishes asteroids from meteoroids?",
          options: [
            "Asteroids are tiny bodies orbiting the Sun (mainly in the Mars-Jupiter belt); meteoroids are small rock pieces that may fall to Earth and burn up due to atmospheric friction",
            "Meteoroids orbit only within the asteroid belt, while asteroids fall to Earth",
            "Both terms refer to exactly the same category of celestial body",
            "Asteroids are found only near the Moon, while meteoroids orbit the Sun",
          ],
          correct: 0,
          explain:
            "Asteroids are tiny Sun-orbiting bodies (mainly between Mars and Jupiter); meteoroids are small rock fragments that, upon nearing Earth, heat up and burn due to atmospheric friction — sometimes producing a visible flash or, if unburnt, a crater.",
        },
        {
          q: "The flash of light sometimes seen in the night sky, caused by a meteoroid burning up due to friction with air, is commonly called a:",
          options: ["Comet", "Meteor (shooting star)", "Nova", "Constellation"],
          correct: 1,
          explain:
            "This flash of light, caused by atmospheric friction burning a meteoroid, is what is commonly seen as a 'shooting star' or meteor.",
        },
        {
          q: "The whitish, broad, glowing band visible across a clear night sky is:",
          options: [
            "The Asteroid Belt",
            "The Milky Way galaxy",
            "The Pole Star's halo",
            "Earth's shadow",
          ],
          correct: 1,
          explain:
            "This band is the Milky Way galaxy, a cluster of millions of stars — our Solar System is part of it.",
        },
        {
          q: "In ancient India, the Milky Way was imagined as a river of light flowing in the sky and was named:",
          options: [
            "Ganga Sagar",
            "Akash Ganga",
            "Nakshatra Path",
            "Surya Marg",
          ],
          correct: 1,
          explain:
            "The Milky Way was poetically named Akash Ganga in ancient India.",
        },
        {
          q: "A 'galaxy' is best defined as:",
          options: [
            "A single very large star",
            "A huge system of billions of stars along with clouds of dust and gases",
            "The path a planet takes around the Sun",
            "A collection of all the planets in one solar system",
          ],
          correct: 1,
          explain:
            "A galaxy is a huge system of billions of stars and clouds of dust and gases — millions of such galaxies together form the Universe.",
        },
        {
          q: "Which of the following correctly describes 'Poornima' and 'Amavasya'?",
          options: [
            "Poornima is New Moon night; Amavasya is Full Moon night",
            "Poornima is Full Moon night; Amavasya is New Moon night, occurring about a fortnight later",
            "Both refer to the same lunar phase",
            "Poornima occurs only once a year",
          ],
          correct: 1,
          explain:
            "Poornima is the Full Moon night; Amavasya, the New Moon night (when the Moon is not visible at all), occurs about a fortnight after Poornima.",
        },
        {
          q: "The night sky is best observed on which of the following nights, according to the chapter?",
          options: [
            "Poornima (Full Moon)",
            "Amavasya (New Moon), provided it is clear",
            "Any night with a full sky of clouds",
            "Only during a solar eclipse",
          ],
          correct: 1,
          explain:
            "On Amavasya (New Moon night), with no bright moonlight to interfere, the night sky can be observed best, provided it is a clear night.",
        },
        {
          q: "Neil Armstrong became the first human to step on the surface of the Moon on which date?",
          options: [
            "15 August 1969",
            "20 July 1969",
            "4 July 1969",
            "12 April 1961",
          ],
          correct: 1,
          explain:
            "Neil Armstrong stepped onto the Moon's surface on 20 July 1969.",
        },
        {
          q: "Considering the table of orbital and rotational data, which of the following pairs is correctly matched (planet — approximate number of moons)?",
          options: [
            "Earth — 2 moons",
            "Mars — 1 moon",
            "Jupiter — about 53 moons",
            "Neptune — about 27 moons",
          ],
          correct: 2,
          explain:
            "Jupiter has about 53 moons. Earth has 1 moon (not 2), Mars has 2 moons (not 1), and Neptune has 13 moons (not 27 — that figure belongs to Uranus).",
        },
        {
          q: "Which of the following planets takes LONGER to spin once on its axis than Mercury takes to complete an entire orbit around the Sun?",
          options: [
            "Earth",
            "Mars",
            "Venus",
            "None — no planet's spin period exceeds Mercury's orbital period",
          ],
          correct: 2,
          explain:
            "Venus takes about 243 days to spin once on its axis — longer than Mercury's ~88-day orbital period around the Sun, an unusual and frequently tested fact about Venus's extremely slow rotation.",
        },
      ],
    },
  },
});
