// ═══════════════════════════════════════════════════════════
// CONTENT "gs3/economics/budget/budget-2025" — Auto-generated by build-bundle.js. DO NOT EDIT.
// Mirrors the source notes file js/data/gs3/economics/budget/budget-2025.js. Loaded on demand
// by js/engine/loader.js the first time one of its topics is opened.
// Edit the source under js/data/ and re-run: node build-bundle.js
// ═══════════════════════════════════════════════════════════
__registerContent("gs3/economics/budget/budget-2025", {
  notes: {
    "news-budget-2025": {
      newsType: true,
      date: "1 February 2025",
      subject: "Economics",
      section: "Union Budget / Economic Survey",
      summary:
        "FM Nirmala Sitharaman presented the Union Budget 2025-26 — her 8th consecutive Budget, a record for any Finance Minister. Themed 'Sabka Vikas' (balanced growth of all regions), it was built around four declared 'engines of growth': Agriculture, MSMEs, Investment, and Exports, with development measures targeted at the poor (Garib), youth, farmers (Annadata), and women (Nari) as part of the Viksit Bharat vision.",
      keyPoints: [
        {
          key: "4 Engines of Growth",
          detail:
            "Agriculture, MSMEs, Investment, and Exports — declared as the structural pillars driving the Budget's growth strategy",
        },
        {
          key: "Income Tax Relief",
          detail:
            "Zero income tax up to ₹12 lakh under the new tax regime (₹12.75 lakh for salaried taxpayers after standard deduction) — a major consumption-boosting measure for the middle class",
        },
        { key: "Fiscal Deficit", detail: "Targeted at 4.4% of GDP for FY26" },
        {
          key: "Capital Expenditure",
          detail: "₹11.21 lakh crore earmarked for FY26 (3.1% of GDP)",
        },
        {
          key: "Overall Fiscal Numbers",
          detail:
            "Total receipts (excl. borrowings): ₹34.96 lakh crore; total expenditure: ₹50.65 lakh crore; net tax receipts: ₹28.37 lakh crore; gross market borrowings: ₹14.82 lakh crore",
        },
        {
          key: "PM Dhan-Dhaanya Krishi Yojana",
          detail:
            "Launched in partnership with states, covering 100 districts with low productivity, moderate crop intensity, and below-average credit access — modelled on the Aspirational Districts Programme; to benefit 1.7 crore farmers",
        },
        {
          key: "National Manufacturing Mission",
          detail:
            "Covers small, medium and large industries to further 'Make in India'; includes a dedicated scheme to make India a global toy-manufacturing hub",
        },
        {
          key: "Export Promotion Mission",
          detail:
            "Jointly driven by the Commerce, MSME, and Finance Ministries to help MSMEs access export markets; includes 'BharatTradeNet' (BTN), a unified digital platform for trade documentation and financing",
        },
        {
          key: "Education & Skilling",
          detail:
            "50,000 Atal Tinkering Labs to be set up in government schools over 5 years; Bharatiya Bhasha Pustak Scheme for digital-form Indian-language textbooks; Bharatnet broadband extended to all rural government secondary schools and primary health centres",
        },
        {
          key: "Global Capability Centres",
          detail:
            "National Framework proposed to promote GCCs in emerging tier-2 cities, alongside support for domestic electronics manufacturing tied to Industry 4.0",
        },
      ],
      syllabusLink:
        "GS-3: Indian Economy — Government Budgeting, inclusive growth strategy, agricultural and MSME policy. Also relevant for GS-2 (welfare/development schemes) and Essay (Viksit Bharat, balanced regional growth themes).",
      prelimsPoints: [
        "Budget 2025-26 presented 1 February 2025 — Nirmala Sitharaman's 8th consecutive Budget (a record for any Finance Minister).",
        "Theme: 'Sabka Vikas' — stimulating balanced growth of all regions.",
        "Fiscal deficit target for FY26: 4.4% of GDP.",
        "New tax regime: Nil tax up to ₹12 lakh (₹12.75 lakh for salaried, after standard deduction).",
        "PM Dhan-Dhaanya Krishi Yojana: covers 100 districts, benefits 1.7 crore farmers.",
        "Capital expenditure FY26: ₹11.21 lakh crore (3.1% of GDP).",
      ],
      mainsAngle:
        "Budget 2025-26's twin emphasis — middle-class tax relief to spur consumption alongside targeted agricultural and MSME-focused structural schemes — reflects a demand-and-supply-side balancing act, setting up the subsequent Budget 2026-27's pivot toward a more explicitly capex-led, infrastructure-driven growth strategy.",
      mainsGS: "GS-3 — Indian Economy (Budgeting & Inclusive Growth Strategy)",
      recall: [
        "8th consecutive Budget — record",
        "Theme: Sabka Vikas",
        "Zero tax up to ₹12 lakh",
        "Fiscal deficit target: 4.4% of GDP",
        "Capex: ₹11.21 lakh crore (3.1% of GDP)",
        "PM Dhan-Dhaanya Krishi Yojana — 100 districts, 1.7 cr farmers",
        "BharatTradeNet — export platform",
        "4 Engines: Agriculture, MSMEs, Investment, Exports",
      ],
    },
  },
  quizzes: {
    "news-budget-2025": {
      title: "Union Budget 2025-26",
      questions: [
        {
          q: "Union Budget 2025-26 was presented on:",
          options: [
            "1 February 2025",
            "1 March 2025",
            "31 January 2025",
            "5 February 2025",
          ],
          correct: 0,
          explain:
            "The Budget was presented on 1 February 2025, continuing the tradition (since 2017) of presenting it on the first day of February.",
        },
        {
          q: [
            "Consider the following statements regarding Union Budget 2025-26:",
            "I. It was Nirmala Sitharaman's 8th consecutive Budget, a record.",
            "II. Its declared theme was 'Atmanirbhar Bharat'.",
            "Which of the statements given above is/are correct?",
          ],
          options: ["I only", "II only", "Both I and II", "Neither I nor II"],
          correct: 0,
          explain:
            "Statement I is correct. Statement II is incorrect — the Budget's declared theme was 'Sabka Vikas', not 'Atmanirbhar Bharat'.",
        },
        {
          q: "Which of the following correctly lists the '4 engines of growth' identified in Budget 2025-26?",
          options: [
            "Agriculture, MSMEs, Investment, Exports",
            "Industry, Services, Agriculture, IT",
            "Manufacturing, Trade, Finance, Technology",
            "Infrastructure, Health, Education, Defence",
          ],
          correct: 0,
          explain:
            "The Budget identified Agriculture, MSMEs, Investment, and Exports as its four engines of growth.",
        },
        {
          q: "Under the new tax regime in Budget 2025-26, income tax became nil up to what income level?",
          options: ["₹7 lakh", "₹10 lakh", "₹12 lakh", "₹15 lakh"],
          correct: 2,
          explain:
            "Zero income tax was announced up to ₹12 lakh income under the new tax regime.",
        },
        {
          q: [
            "Assertion (A): Budget 2025-26 provided a significant boost to middle-class disposable income.",
            "Reason (R): It raised the effective nil-tax threshold for salaried taxpayers to ₹12.75 lakh, after accounting for the standard deduction.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R directly explains A — the effective ₹12.75 lakh threshold for salaried taxpayers is precisely the mechanism that boosted middle-class disposable income.",
        },
        {
          q: "The fiscal deficit target for FY26, as per Budget 2025-26, was set at:",
          options: ["4.4% of GDP", "4.9% of GDP", "3.5% of GDP", "5.1% of GDP"],
          correct: 0,
          explain: "The fiscal deficit was targeted at 4.4% of GDP for FY26.",
        },
        {
          q: [
            "Consider the following pairs regarding Budget 2025-26's fiscal numbers:",
            "Indicator — Figure",
            "I. Capital expenditure — ₹11.21 lakh crore",
            "II. Capital expenditure as % of GDP — 3.1%",
            "III. Total expenditure — ₹34.96 lakh crore",
            "How many of the above pairs are correctly matched?",
          ],
          options: [
            "Only one pair",
            "Only two pairs",
            "All three pairs",
            "None of the pairs",
          ],
          correct: 1,
          explain:
            "Pairs I and II are correctly matched. Pair III is incorrect — ₹34.96 lakh crore was the TOTAL RECEIPTS (excl. borrowings) figure, not total expenditure (which was ₹50.65 lakh crore).",
        },
        {
          q: "The PM Dhan-Dhaanya Krishi Yojana, announced in Budget 2025-26, covers how many districts?",
          options: [
            "50 districts",
            "75 districts",
            "100 districts",
            "150 districts",
          ],
          correct: 2,
          explain:
            "The scheme covers 100 districts identified as having low productivity, moderate crop intensity, and below-average institutional credit access.",
        },
        {
          q: "The PM Dhan-Dhaanya Krishi Yojana is explicitly modelled on which earlier government programme?",
          options: [
            "MGNREGA",
            "Aspirational Districts Programme",
            "Smart Cities Mission",
            "PM Gati Shakti",
          ],
          correct: 1,
          explain:
            "The scheme is modelled on the Aspirational Districts Programme's approach of targeting specific underperforming districts.",
        },
        {
          q: "Approximately how many farmers were expected to benefit from the PM Dhan-Dhaanya Krishi Yojana, as announced in Budget 2025-26?",
          options: ["50 lakh", "1 crore", "1.7 crore", "2.5 crore"],
          correct: 2,
          explain:
            "The scheme was expected to benefit approximately 1.7 crore farmers.",
        },
        {
          q: "Budget 2025-26 launched a National Manufacturing Mission with a dedicated scheme to make India a global hub for which specific product category?",
          options: ["Automobiles", "Toys", "Textiles", "Pharmaceuticals"],
          correct: 1,
          explain:
            "A dedicated scheme was announced specifically to make India a global toy-manufacturing hub, as part of the broader National Manufacturing Mission.",
        },
        {
          q: "Which of the following best describes 'BharatTradeNet', announced as part of the Export Promotion Mission in Budget 2025-26?",
          options: [
            "A new export tax levied on MSMEs",
            "A unified digital platform for trade documentation and financing",
            "A bilateral trade agreement with China",
            "A dedicated fund exclusively for large corporate exporters",
          ],
          correct: 1,
          explain:
            "BharatTradeNet (BTN) is a unified digital platform for trade documentation and financing, designed to help MSMEs access export markets.",
        },
        {
          q: "The Export Promotion Mission announced in Budget 2025-26 is jointly driven by which combination of Ministries?",
          options: [
            "Home, Defence, and External Affairs",
            "Commerce, MSME, and Finance",
            "Railways, Shipping, and Commerce",
            "Agriculture, Rural Development, and Finance",
          ],
          correct: 1,
          explain:
            "The Export Promotion Mission is jointly driven by the Commerce, MSME, and Finance Ministries.",
        },
        {
          q: "Under Budget 2025-26's education initiatives, how many Atal Tinkering Labs were announced to be set up in government schools over the next 5 years?",
          options: ["25,000", "50,000", "75,000", "1,00,000"],
          correct: 1,
          explain:
            "50,000 Atal Tinkering Labs were announced to be set up in government schools over 5 years.",
        },
        {
          q: "Which of the following statements about Budget 2025-26's education-related announcements is correct?",
          options: [
            "The Bharatiya Bhasha Pustak Scheme aims to provide digital-form textbooks in Indian languages",
            "Bharatnet broadband was withdrawn from rural government institutions",
            "Atal Tinkering Labs were discontinued under this Budget",
            "The scheme applies only to private schools",
          ],
          correct: 0,
          explain:
            "The Bharatiya Bhasha Pustak Scheme specifically aims to provide digital-form textbooks in Indian languages, extending educational access.",
        },
        {
          q: "Budget 2025-26 proposed a National Framework to promote which of the following in emerging tier-2 cities?",
          options: [
            "Special Economic Zones",
            "Global Capability Centres (GCCs)",
            "Smart City Missions",
            "Export Processing Zones",
          ],
          correct: 1,
          explain:
            "A National Framework was proposed specifically to promote Global Capability Centres (GCCs) in emerging tier-2 cities.",
        },
        {
          q: "Which of the following priority groups were explicitly referenced as beneficiaries of Budget 2025-26's development vision?",
          options: [
            "Garib, Yuva, Annadata, and Nari",
            "Only urban taxpayers",
            "Only large industrial houses",
            "Only government employees",
          ],
          correct: 0,
          explain:
            "The Budget explicitly framed its development measures around the poor (Garib), youth (Yuva), farmers (Annadata), and women (Nari).",
        },
        {
          q: [
            "Consider the following statements about Budget 2025-26:",
            "1. It targeted a fiscal deficit of 4.4% of GDP.",
            "2. Income tax became nil up to ₹15 lakh under the new regime.",
            "3. The PM Dhan-Dhaanya Krishi Yojana covers 100 districts.",
            "Which of the statements given above is/are correct?",
          ],
          options: ["1 and 3 only", "2 only", "1, 2 and 3", "1 only"],
          correct: 0,
          explain:
            "Statement 2 is incorrect — nil tax applied up to ₹12 lakh (₹12.75 lakh for salaried), not ₹15 lakh. Statements 1 and 3 are correct.",
        },
        {
          q: "Which of the following statements about the overall approach of Budget 2025-26 is the MOST accurate assessment?",
          options: [
            "It relied purely on increased public borrowing with no structural reform",
            "It combined middle-class tax relief (a demand-side measure) with targeted agricultural and MSME structural schemes (supply-side measures)",
            "It focused exclusively on defence expenditure",
            "It eliminated all forms of taxation for the fiscal year",
          ],
          correct: 1,
          explain:
            "This dual demand-supply approach — tax relief to boost consumption alongside targeted structural schemes — is the Budget's defining strategic characteristic.",
        },
        {
          q: "Gross market borrowings under Budget 2025-26 were estimated at approximately:",
          options: [
            "₹10.82 lakh crore",
            "₹14.82 lakh crore",
            "₹18.82 lakh crore",
            "₹22.82 lakh crore",
          ],
          correct: 1,
          explain:
            "Gross market borrowings were estimated at ₹14.82 lakh crore for FY26.",
        },
      ],
    },
  },
});
