// ═══════════════════════════════════════════════════════════
// CONTENT "gs3/economics/budget/budget-2026" — Auto-generated by build-bundle.js. DO NOT EDIT.
// Mirrors the source notes file js/data/gs3/economics/budget/budget-2026.js. Loaded on demand
// by js/engine/loader.js the first time one of its topics is opened.
// Edit the source under js/data/ and re-run: node build-bundle.js
// ═══════════════════════════════════════════════════════════
__registerContent("gs3/economics/budget/budget-2026", {
  notes: {
    "news-budget-2026": {
      newsType: true,
      date: "1 February 2026",
      subject: "Economics",
      section: "Union Budget / Economic Survey",
      summary:
        "FM Nirmala Sitharaman presented the Union Budget 2026-27 — the first Budget prepared in the newly-named 'Kartavya Bhawan' — built around 3 declared 'kartavyas' (duties): accelerating economic growth, building people's capacity, and ensuring inclusive access to opportunity (Sabka Saath, Sabka Vikas). The Budget retained Budget 2025's income-tax slabs while pushing capital expenditure to a record high and further trimming the fiscal deficit.",
      keyPoints: [
        {
          key: "3 Kartavyas (Duties)",
          detail:
            "1) Accelerate & sustain economic growth 2) Fulfil people's aspirations & build capacity 3) Ensure inclusive access (Sabka Saath, Sabka Vikas) across every family/community/region",
        },
        {
          key: "Income Tax Slabs",
          detail:
            "UNCHANGED from Budget 2025 — no new slab changes announced; existing structure retained and reinforced",
        },
        {
          key: "Income Tax Act, 2025",
          detail:
            "Planned implementation from April 1, 2026 — aims to simplify compliance and reduce legal complexity while retaining existing tax rates/slabs",
        },
        {
          key: "Fiscal Deficit",
          detail:
            "FY27 (BE) target: 4.3% of GDP — down from FY26's revised estimate of 4.4%",
        },
        {
          key: "Capital Expenditure",
          detail:
            "Record ₹12.2 lakh crore for FY27 (4.4% of GDP) — an 11.5% increase over FY26 revised estimates; highest-ever capex push",
        },
        {
          key: "Debt-to-GDP Ratio",
          detail:
            "Estimated at 55.6% of GDP in BE 2026-27, down from 56.1% in RE 2025-26; long-term target ~50% of GDP by March 2031",
        },
        {
          key: "Total Expenditure",
          detail:
            "₹53.47 lakh crore proposed; Revenue expenditure ₹41.25 lakh crore (6.6% rise); Receipts (excl. borrowings) ₹36.5 lakh crore (7.2% rise)",
        },
        {
          key: "Biopharma SHAKTI",
          detail:
            "₹10,000 crore outlay over 5 years to build India as a global biopharma manufacturing hub; 3 new NIPER institutes + 7 upgraded",
        },
        {
          key: "Infrastructure Push",
          detail:
            "Infrastructure spending raised 11.4% to a record ₹12.2 lakh crore (per Reuters); new Infrastructure Risk Guarantee Fund for private developers",
        },
        {
          key: "Railways Capex",
          detail:
            "₹2,77,830 crore allocated for FY27 (10.25% higher than FY26's ₹2,52,000 crore) — highest-ever; plus ₹15,000 crore via Extra Budgetary Resources",
        },
        {
          key: "Freight & Waterways",
          detail:
            "New Dedicated Freight Corridor (Dankuni to Surat); 20 new National Waterways over 5 years, starting with NW-5 in Odisha",
        },
        {
          key: "Disinvestment Target",
          detail:
            "₹80,000 crore for FY27 — first INCREASE in 5 years (FY26 target was ₹47,000 crore; ~71.9% of that was achieved)",
        },
        {
          key: "Semiconductor Mission 2.0",
          detail:
            "India Semiconductor Mission 2.0 announced with hiked electronics outlay, alongside a Rare Earth Corridor initiative for critical mineral processing",
        },
        {
          key: "Revenue Deficit",
          detail:
            "Targeted at 1.5% of GDP for FY27 — same as FY26's revised estimate",
        },
        {
          key: "GDP Growth",
          detail:
            "Real GDP growth for FY26 estimated at 7.4%; nominal growth for FY27 projected at 10%",
        },
      ],
      syllabusLink:
        "GS-3: Indian Economy — Government Budgeting, capital expenditure & infrastructure policy, fiscal consolidation roadmap (16th Finance Commission target: 3.5% fiscal deficit by 2030-31). Also useful for GS-2 as continuity of Budget-making institutional practice.",
      prelimsPoints: [
        "Budget 2026-27 = first Budget prepared in 'Kartavya Bhawan' (new building housing Finance Ministry offices).",
        "FY27 fiscal deficit target: 4.3% of GDP; FY26 revised estimate: 4.4%.",
        "16th Finance Commission recommended fiscal deficit reduction to 3.5% of GDP by 2030-31 for the Centre, and 3% of GSDP annually for states.",
        "Capital expenditure FY27: ₹12.2 lakh crore — record high, 4.4% of GDP.",
        "Debt-to-GDP target: ~50% by March 2031 (currently 55.6% in BE 2026-27).",
      ],
      mainsAngle:
        "Budget 2026-27's decision to hold income-tax slabs steady while sharply raising capital expenditure signals a shift in policy emphasis from consumption-side stimulus (seen in Budget 2025) toward supply-side, infrastructure-led growth — reflecting the government's calculated bet that public capex crowds in private investment more effectively at this stage of the fiscal consolidation glide path recommended by the 16th Finance Commission.",
      mainsGS:
        "GS-3 — Indian Economy (Fiscal Policy, Capital Expenditure & Infrastructure)",
      recall: [
        "3 Kartavyas: Growth, Capacity, Inclusion",
        "Tax slabs UNCHANGED from 2025",
        "Income Tax Act 2025 — effective April 1, 2026",
        "FY27 fiscal deficit target: 4.3%",
        "Capex: ₹12.2 lakh crore (record, 4.4% of GDP)",
        "Debt-to-GDP: 55.6% (target ~50% by 2031)",
        "Biopharma SHAKTI — ₹10,000 cr / 5 yrs",
        "Disinvestment target: ₹80,000 cr (1st rise in 5 yrs)",
        "Semiconductor Mission 2.0",
      ],
    },
  },
  quizzes: {
    "news-budget-2026": {
      title: "Union Budget 2026-27",
      questions: [
        {
          q: "Union Budget 2026-27 was presented on:",
          options: [
            "1 February 2026",
            "1 March 2026",
            "31 January 2026",
            "5 February 2026",
          ],
          correct: 0,
          explain: "The Budget was presented on 1 February 2026.",
        },
        {
          q: "Budget 2026-27 was notable as the first Budget prepared in which newly-named building?",
          options: [
            "North Block",
            "Kartavya Bhawan",
            "Rashtrapati Bhavan",
            "South Block",
          ],
          correct: 1,
          explain:
            "It was the first Budget prepared in the newly-named 'Kartavya Bhawan', housing Finance Ministry offices.",
        },
        {
          q: [
            "Consider the following statements regarding the '3 Kartavyas' framework of Budget 2026-27:",
            "I. It includes accelerating and sustaining economic growth.",
            "II. It includes fulfilling people's aspirations and building capacity.",
            "III. It includes achieving a zero fiscal deficit within the same fiscal year.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I and II only",
            "II and III only",
            "I, II and III",
            "III only",
          ],
          correct: 0,
          explain:
            "Statements I and II are correct — the third Kartavya was 'ensuring inclusive access' (Sabka Saath, Sabka Vikas), not 'zero fiscal deficit', making Statement III incorrect.",
        },
        {
          q: "Regarding income tax provisions, Budget 2026-27:",
          options: [
            "Introduced new, higher tax slabs",
            "Retained Budget 2025's income tax slabs unchanged",
            "Abolished the new tax regime entirely",
            "Raised the nil-tax threshold to ₹15 lakh",
          ],
          correct: 1,
          explain:
            "Income tax slabs were retained UNCHANGED from Budget 2025 — no new slab changes were announced this year.",
        },
        {
          q: "The Income Tax Act, 2025 was planned for implementation from which date?",
          options: [
            "1 February 2026",
            "1 April 2026",
            "1 January 2027",
            "1 April 2027",
          ],
          correct: 1,
          explain:
            "The Income Tax Act, 2025 was planned to take effect from April 1, 2026, aiming to simplify compliance while retaining existing rates.",
        },
        {
          q: [
            "Assertion (A): Budget 2026-27 represented a strategic shift toward supply-side, infrastructure-led growth.",
            "Reason (R): The Budget held income tax slabs steady while sharply increasing capital expenditure to a record ₹12.2 lakh crore.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R directly explains A — holding tax slabs steady (rather than cutting further, as in 2025) while pushing capex to a record is precisely the mechanism behind this supply-side policy shift.",
        },
        {
          q: "The fiscal deficit target for FY27, as per Budget 2026-27, was:",
          options: ["4.4% of GDP", "4.3% of GDP", "3.5% of GDP", "5.0% of GDP"],
          correct: 1,
          explain:
            "FY27 fiscal deficit was targeted at 4.3% of GDP, a reduction from FY26's revised estimate of 4.4%.",
        },
        {
          q: "Capital expenditure for FY27 under Budget 2026-27 was set at a record:",
          options: [
            "₹10.5 lakh crore",
            "₹11.21 lakh crore",
            "₹12.2 lakh crore",
            "₹13.5 lakh crore",
          ],
          correct: 2,
          explain:
            "A record ₹12.2 lakh crore was allocated for capital expenditure in FY27, equal to 4.4% of GDP — the highest-ever capex allocation.",
        },
        {
          q: [
            "Consider the following statements regarding fiscal indicators in Budget 2026-27:",
            "I. Capital expenditure represented 4.4% of GDP.",
            "II. This capex figure represented an 11.5% increase over FY26 revised estimates.",
            "Which of the statements given above is/are correct?",
          ],
          options: ["I only", "II only", "Both I and II", "Neither I nor II"],
          correct: 2,
          explain:
            "Both statements are correct — the record capex allocation both constituted 4.4% of GDP and represented an 11.5% year-on-year increase.",
        },
        {
          q: "The estimated Debt-to-GDP ratio under Budget Estimates 2026-27 was:",
          options: ["50.6%", "52.3%", "55.6%", "58.1%"],
          correct: 2,
          explain:
            "The Debt-to-GDP ratio was estimated at 55.6% for BE 2026-27, down from 56.1% in RE 2025-26.",
        },
        {
          q: "The long-term Debt-to-GDP target associated with Budget 2026-27's fiscal roadmap was approximately 50% of GDP by which target date?",
          options: ["March 2028", "March 2030", "March 2031", "March 2035"],
          correct: 2,
          explain:
            "The long-term target was approximately 50% of GDP by March 2031, in line with the fiscal consolidation glide path.",
        },
        {
          q: "'Biopharma SHAKTI', announced in Budget 2026-27, was allocated an outlay of:",
          options: [
            "₹5,000 crore over 5 years",
            "₹10,000 crore over 5 years",
            "₹15,000 crore over 5 years",
            "₹20,000 crore over 5 years",
          ],
          correct: 1,
          explain:
            "Biopharma SHAKTI was announced with a ₹10,000 crore outlay over 5 years, aimed at building India as a global biopharma manufacturing hub.",
        },
        {
          q: "Which of the following was part of the Biopharma SHAKTI scheme announced in Budget 2026-27?",
          options: [
            "1 new NIPER institute only",
            "3 new NIPER institutes plus 7 upgraded institutes",
            "Closure of all existing NIPER institutes",
            "Transfer of NIPER institutes to state governments",
          ],
          correct: 1,
          explain:
            "The scheme included establishing 3 new NIPER institutes and upgrading 7 existing ones.",
        },
        {
          q: "Railways capital expenditure for FY27 under Budget 2026-27 was allocated at approximately:",
          options: [
            "₹2,00,000 crore",
            "₹2,52,000 crore",
            "₹2,77,830 crore",
            "₹3,00,000 crore",
          ],
          correct: 2,
          explain:
            "₹2,77,830 crore was allocated for Railways in FY27 — about 10.25% higher than FY26's ₹2,52,000 crore, and the highest-ever railways allocation.",
        },
        {
          q: "Budget 2026-27 announced a new Dedicated Freight Corridor connecting which two locations?",
          options: [
            "Delhi to Mumbai",
            "Dankuni to Surat",
            "Chennai to Kolkata",
            "Kanpur to Ludhiana",
          ],
          correct: 1,
          explain:
            "A new Dedicated Freight Corridor from Dankuni to Surat was announced in Budget 2026-27.",
        },
        {
          q: "Budget 2026-27 announced plans for 20 new National Waterways over 5 years, beginning with which specific waterway?",
          options: [
            "NW-1 in Uttar Pradesh",
            "NW-3 in Kerala",
            "NW-5 in Odisha",
            "NW-9 in Andhra Pradesh",
          ],
          correct: 2,
          explain:
            "The plan begins with NW-5 in Odisha, as part of a broader 20-new-waterway development plan over 5 years.",
        },
        {
          q: "The disinvestment target for FY27 set in Budget 2026-27 was:",
          options: [
            "₹47,000 crore",
            "₹65,000 crore",
            "₹80,000 crore",
            "₹1,00,000 crore",
          ],
          correct: 2,
          explain:
            "₹80,000 crore was set as the disinvestment target — notably the first increase in this target in 5 years (FY26's target had been ₹47,000 crore).",
        },
        {
          q: "Which new initiative for critical mineral processing was announced in Budget 2026-27, alongside India Semiconductor Mission 2.0?",
          options: [
            "Critical Minerals Fund",
            "Rare Earth Corridor",
            "Mineral Security Partnership",
            "National Mining Mission",
          ],
          correct: 1,
          explain:
            "A Rare Earth Corridor initiative for critical mineral processing was announced alongside India Semiconductor Mission 2.0.",
        },
        {
          q: "The Revenue Deficit target for FY27 under Budget 2026-27 was:",
          options: ["1.0% of GDP", "1.5% of GDP", "2.0% of GDP", "2.5% of GDP"],
          correct: 1,
          explain:
            "Revenue Deficit was targeted at 1.5% of GDP for FY27 — the same level as FY26's revised estimate.",
        },
        {
          q: [
            "Consider the following statements comparing Budget 2025-26 and Budget 2026-27:",
            "1. Both Budgets targeted the same fiscal deficit percentage.",
            "2. Budget 2026-27's capital expenditure allocation was higher than Budget 2025-26's.",
            "3. Budget 2026-27 retained the income tax slabs introduced in Budget 2025-26.",
            "Which of the statements given above is/are correct?",
          ],
          options: ["2 and 3 only", "1 only", "1, 2 and 3", "3 only"],
          correct: 0,
          explain:
            "Statements 2 and 3 are correct. Statement 1 is incorrect — the fiscal deficit target DECREASED from 4.4% (FY26) to 4.3% (FY27), rather than staying the same.",
        },
      ],
    },
  },
});
