// ═══════════════════════════════════════════════════════════
// CONTENT "gs1/geography/ncert/class7/ch3/ch3" — Auto-generated by build-bundle.js. DO NOT EDIT.
// Mirrors the source notes file js/data/gs1/geography/ncert/class7/ch3/ch3.js. Loaded on demand
// by js/engine/loader.js the first time one of its topics is opened.
// Edit the source under js/data/ and re-run: node build-bundle.js
// ═══════════════════════════════════════════════════════════
__registerContent("gs1/geography/ncert/class7/ch3/ch3", {
  notes: {
    "geo7-ch3": {
      era: "NCERT Class 7 — Geography (Our Environment), Chapter 3",
      significance: [
        "Endogenic vs exogenic forces, focus vs epicentre, and the entire landform classification is a core Prelims static topic",
        "River landforms (waterfall, meander, ox-bow lake, flood plain, levee, delta) are individually testable in match-the-following",
        "Sea wave landforms (sea cave, sea arch, stack, sea cliff, beach) and glacial landforms (moraines) are high-frequency items",
        "Bhuj earthquake case study (6.9 Richter, 26 January 2001) and seismograph/Richter Scale facts are directly testable",
      ],
      features: [
        {
          key: "Lithospheric Plates",
          main: "The lithosphere is broken into a number of plates called Lithospheric Plates\nThese plates move very slowly — just a few millimetres each year\nMovement driven by molten magma inside the Earth moving in a circular manner",
          note: "Lithospheric plates = the Earth's crust consisting of several large and small, rigid, irregularly-shaped slabs (plates) carrying continents and ocean floor",
        },
        {
          key: "Earth Movements — Two Types of Forces",
          main: "Endogenic forces: forces that act in the INTERIOR of the Earth; include sudden forces (earthquake, volcano, landslide) and diastrophic forces (building mountains)\nExogenic forces: forces that work on the SURFACE of the Earth; include erosional and depositional forces (river, wind, sea-waves, glaciers)",
          note: "Endo = inside; Exo = outside; both + 'genic' (origin)",
        },
        {
          key: "Endogenic — Sudden Forces",
          main: "Earthquakes and volcanoes: cause mass destruction over the surface of the Earth\nLandslides: also included under sudden forces",
          note: "",
        },
        {
          key: "Volcano",
          main: "A vent (opening) in the Earth's crust through which molten material erupts suddenly\nParts: Crater, Vent, Lava, Gases and ash, Crust, Mantle, Magma Chamber",
          note: "",
        },
        {
          key: "Earthquake — Key Terms",
          main: "When lithospheric plates move, the Earth's surface vibrates\nVibrations that travel all round the earth = earthquakes\nFocus: the place in the crust WHERE the movement starts (origin of seismic energy)\nEpicentre: the place on the SURFACE directly above the focus\nVibrations travel outward from the epicentre as seismic waves\nGreatest damage is usually closest to the epicentre",
          note: "",
        },
        {
          key: "Earthquake Waves — Three Types",
          main: "1. P waves (Primary/Longitudinal waves)\n2. S waves (Secondary/Transverse waves)\n3. L waves (Surface waves)",
          note: "",
        },
        {
          key: "Earthquake Measurement",
          main: "Measured by a machine called a Seismograph\nMagnitude measured on the Richter Scale\n2.0 or less: felt only a little\nOver 5.0: can cause damage\n6.0 or higher: considered very strong\n7.0: classified as a major earthquake",
          note: "",
        },
        {
          key: "Bhuj Earthquake — Case Study",
          main: "Date: 26 January 2001\nMagnitude: 6.9 on the Richter Scale\nLocation: Bhuj Town, Gujarat\nImpacts: at least 971 students and 31 teachers feared to have lost their lives from collapse of school buildings; phone/water/power lines knocked out; hundreds of fires in the city; state of emergency declared",
          note: "Earthquake prediction methods: studying animal behaviour (fish in ponds get agitated, snakes come to surface)",
        },
        {
          key: "Earthquake Preparedness",
          main: "Safe spot: under a kitchen counter, table or desk; against an inside corner or wall\nStay away from: fire places, areas around chimneys, windows/mirrors/picture frames\nBe prepared: spread awareness among friends and family",
          note: "",
        },
        {
          key: "Major Landforms — Formed by Weathering and Erosion",
          main: "Weathering: breaking up of rocks on the Earth's surface\nErosion: wearing away of the landscape by different agents (water, wind, ice)\nEroded material is carried away and eventually deposited — creating different landforms",
          note: "",
        },
        {
          key: "Work of a River — Landforms",
          main: "Waterfall: river tumbles at steep angle over very hard rocks or down a steep valley side\nMeandering river: as the river enters the plain, it twists and turns forming large bends called MEANDERS\nOx-bow lake: the meander loop cuts off from the river, forming a cut-off lake (also called ox-bow lake)\nFlood plain: river overflows its banks → deposits fine soil/sediment along banks → flat fertile area called flood plain\nLevees: raised banks formed by river deposits (keep river in its channel)\nDelta: as river approaches sea, speed decreases → breaks into distributaries → sediments from all mouths form a delta",
          note: "Highest waterfall: Angel Falls, Venezuela (South America); Niagara Falls on Canada-USA border; Victoria Falls on Zambia-Zimbabwe border in Africa",
        },
        {
          key: "Work of Sea Waves — Coastal Landforms",
          main: "Sea caves: hollow cavities formed on rocks by continuous wave action\nSea arches: formed as sea caves grow larger, only roofs remain\nStacks: formed when erosion breaks the roof of a sea arch, leaving only walls\nSea cliff: steep rocky coast rising almost vertically above sea water\nBeaches: formed where sea waves deposit sediments along the shores",
          note: "",
        },
        {
          key: "Work of Ice (Glaciers)",
          main: "Glaciers = 'rivers of ice' that erode the landscape by bulldozing soil and stones to expose solid rock below\nGlaciers carve out deep hollows; as ice melts, they become beautiful lakes in the mountains\nGlacial Moraines: material carried by the glacier (rocks, sand, silt) gets deposited — these deposits form moraines",
          note: "",
        },
        {
          key: "Work of Wind — Desert Landforms",
          main: "Main agent of erosion and deposition in deserts = WIND\nMushroom rocks: rocks in the shape of a mushroom (wind erodes lower section more than upper → narrower base, wider top)\nSand dunes: low hill-like structures formed when wind deposits sand\nLoess: when very fine, light sand grains are deposited in large areas — large deposits of loess found in CHINA",
          note: "",
        },
      ],
      traps: [
        {
          label: "Focus vs Epicentre",
          lines: [
            "FOCUS = underground point where earthquake originates (origin of seismic energy)",
            "EPICENTRE = point on the SURFACE directly above the focus",
            "Greatest damage = closest to the epicentre, NOT the focus",
          ],
        },
        {
          label: "Endogenic vs Exogenic Forces",
          lines: [
            "ENDOGENIC = from inside the Earth → Earthquakes, Volcanoes, Landslides, Mountain-building",
            "EXOGENIC = on the surface → River, Wind, Sea-waves, Glaciers (Erosional and Depositional)",
            "A common trap: placing rivers/glaciers under endogenic forces",
          ],
        },
        {
          label: "Sea Wave Landform Sequence",
          lines: [
            "Waves strike rocks → Cracks develop → Caves form",
            "Caves grow bigger → only roof remains → Sea Arch",
            "Erosion breaks arch roof → only walls remain → Stack",
            "Vertical rocky coast = Sea Cliff",
            "Sediment deposited along shore = Beach",
          ],
        },
        {
          label: "Beach — Erosional or Depositional?",
          lines: [
            "Beach is a DEPOSITIONAL feature of sea waves (NOT erosional)",
            "Erosional sea wave features: sea cave, sea arch, stack, sea cliff",
            "This distinction appears directly in the chapter's exercises",
          ],
        },
        {
          label: "Moraine — Glacier's Depositional Feature",
          lines: [
            "Glacial moraine = depositional feature of glaciers",
            "NOT a beach (beach = sea waves); NOT a flood plain (flood plain = rivers)",
            "This appears in the chapter's exercise: depositional feature of a glacier = Moraine",
          ],
        },
        {
          label: "Loess Location",
          lines: [
            "Large deposits of loess are found in CHINA",
            "Loess = very fine, light sand carried over long distances by wind and deposited in large areas",
          ],
        },
        {
          label: "Bhuj Earthquake — Key Facts",
          lines: [
            "Date: 26 January 2001",
            "Magnitude: 6.9 on Richter Scale",
            "Location: Bhuj Town, Gujarat",
          ],
        },
      ],
      mainsAngle:
        "Chapter 3 is directly relevant to GS-3 Disaster Management questions. The Bhuj earthquake case study (2001) illustrates cascading disaster impacts: infrastructure destruction, supply chain failure, mass casualties, emergency declaration, and the role of central-state coordination in relief. The earthquake preparedness section also maps onto NDMA guidelines.",
      mainsTheme:
        "Tectonic forces, landform evolution, and disaster preparedness — connections to GS-3 Disaster Management",
      recall: [
        "Lithospheric plates move a few mm/year due to molten magma circulation",
        "Endogenic (interior): earthquake, volcano, landslide, mountain-building",
        "Exogenic (surface): river, wind, sea-waves, glaciers",
        "Focus = underground origin; Epicentre = surface point above focus",
        "Seismograph measures earthquakes; Richter scale measures magnitude",
        "Bhuj: 26 Jan 2001, 6.9 Richter, Gujarat",
        "3 earthquake wave types: P (longitudinal), S (transverse), L (surface)",
        "River landforms: waterfall → meander → ox-bow lake → flood plain → levee → delta",
        "Sea wave: sea cave → sea arch → stack; sea cliff; beach (depositional)",
        "Glacier: moraines (depositional); deep hollow lakes",
        "Wind: mushroom rocks (erosional); sand dunes + loess (depositional); loess in China",
        "Beach = depositional (not erosional); Moraine = glacial depositional feature",
      ],
    },
  },
  quizzes: {
    "geo7-ch3": {
      title: "Our Changing Earth",
      questions: [
        {
          q: "Lithospheric plates move very slowly because of:",
          options: [
            "The gravitational pull of the Moon",
            "The movement of molten magma inside the Earth in a circular manner",
            "The rotation of the Earth on its axis",
            "The tidal forces of the oceans",
          ],
          correct: 1,
          explain:
            "The movement of molten magma inside the Earth in a circular manner drives the movement of lithospheric plates — just a few millimetres each year.",
        },
        {
          q: [
            "Consider the following pairs:",
            "Force — Type",
            "I. Earthquake — Endogenic",
            "II. River erosion — Endogenic",
            "III. Volcano — Endogenic",
            "IV. Glacier — Exogenic",
            "How many of the above pairs are correctly matched?",
          ],
          options: [
            "Only two pairs",
            "Only three pairs",
            "All four pairs",
            "Only one pair",
          ],
          correct: 1,
          explain:
            "Pairs I, III, and IV are correctly matched. Pair II is incorrect — River erosion is an EXOGENIC force (working on the surface), not endogenic.",
        },
        {
          q: "Which of the following is NOT an exogenic force?",
          options: ["River", "Wind", "Volcano", "Glaciers"],
          correct: 2,
          explain:
            "A Volcano is an ENDOGENIC force — it originates from the interior of the Earth. Rivers, wind, and glaciers are all exogenic forces working on the Earth's surface.",
        },
        {
          q: [
            "Assertion (A): The Focus and the Epicentre of an earthquake are two different points.",
            "Reason (R): The Focus is the point in the crust where the earthquake originates, while the Epicentre is the point on the surface directly above the Focus.",
            "Which one of the following is correct?",
          ],
          options: [
            "Both A and R are true, and R is the correct explanation of A",
            "Both A and R are true, but R is NOT the correct explanation of A",
            "A is true, but R is false",
            "A is false, but R is true",
          ],
          correct: 0,
          explain:
            "Both are true and R correctly explains A — the Focus is the underground origin (where the earthquake actually starts) while the Epicentre is the surface point directly above it.",
        },
        {
          q: "Where does the greatest damage from an earthquake usually occur?",
          options: [
            "At the Focus (underground origin)",
            "At the Epicentre (point on surface above focus) and areas closest to it",
            "At the farthest point from the Epicentre",
            "Equally at all distances from the Focus",
          ],
          correct: 1,
          explain:
            "The greatest damage is usually closest to the Epicentre — the strength of the earthquake decreases as you move away from the centre.",
        },
        {
          q: "A seismograph is used to:",
          options: [
            "Predict the exact location and time of future earthquakes",
            "Measure the magnitude of earthquakes on the Richter Scale",
            "Create artificial earthquakes for research",
            "Control tectonic plate movements",
          ],
          correct: 1,
          explain:
            "A seismograph is the machine used to measure and record earthquakes, and the magnitude is measured on the Richter Scale.",
        },
        {
          q: "According to the chapter, an earthquake measuring 7.0 on the Richter Scale is classified as:",
          options: [
            "Barely felt",
            "Minor damage",
            "Very strong",
            "A major earthquake",
          ],
          correct: 3,
          explain:
            "7.0 on the Richter Scale is classified as a MAJOR earthquake. 6.0 or higher is considered 'very strong'; over 5.0 can cause damage.",
        },
        {
          q: "The Bhuj earthquake of 26 January 2001 measured how much on the Richter Scale?",
          options: ["5.0", "6.9", "7.5", "8.2"],
          correct: 1,
          explain:
            "The Bhuj earthquake was a massive 6.9 on the Richter Scale, hitting Bhuj Town, Gujarat on 26 January 2001.",
        },
        {
          q: [
            "Consider the following statements about the three types of earthquake waves:",
            "I. P waves are also called longitudinal waves.",
            "II. S waves are also called transverse waves.",
            "III. L waves are also called surface waves.",
            "Which of the statements given above is/are correct?",
          ],
          options: [
            "I and II only",
            "II and III only",
            "I, II and III",
            "I only",
          ],
          correct: 2,
          explain:
            "All three statements are correct — P (Primary/Longitudinal), S (Secondary/Transverse), and L (Surface) waves are the three types of earthquake waves.",
        },
        {
          q: "A volcano is defined as:",
          options: [
            "A sudden movement of the tectonic plates",
            "A vent (opening) in the Earth's crust through which molten material erupts suddenly",
            "A type of sedimentary rock formed by lava",
            "The epicentre of an earthquake on the ocean floor",
          ],
          correct: 1,
          explain:
            "A volcano is a vent (opening) in the Earth's crust through which molten material (lava, gases, ash) erupts suddenly.",
        },
        {
          q: "Weathering is best defined as:",
          options: [
            "The wearing away of the landscape by water, wind and ice",
            "The breaking up of rocks on the Earth's surface",
            "The deposition of sediments in river beds",
            "The movement of material by glaciers",
          ],
          correct: 1,
          explain:
            "Weathering is the BREAKING UP of rocks on the Earth's surface. Erosion is the WEARING AWAY of the landscape by different agents (water, wind, ice).",
        },
        {
          q: "When a river enters a plain and twists and turns, the large bends formed are called:",
          options: ["Levees", "Deltas", "Meanders", "Ox-bow lakes"],
          correct: 2,
          explain:
            "When the river enters the plain, it twists and turns, forming large bends known as MEANDERS.",
        },
        {
          q: "An ox-bow lake is formed when:",
          options: [
            "A glacier melts and fills a deep hollow",
            "A meander loop cuts off from the main river, forming a cut-off lake",
            "Sea waves deposit sediment along the shore",
            "A river overflows and deposits sediment on its banks",
          ],
          correct: 1,
          explain:
            "Continuous erosion along the meander loop brings its ends closer together until the loop cuts off from the river, forming an ox-bow lake.",
        },
        {
          q: "A flood plain and levees are both formed by the work of:",
          options: ["Glaciers", "Sea waves", "Wind", "Rivers"],
          correct: 3,
          explain:
            "Flood plains (flat fertile areas alongside rivers, formed by sediment deposition during flooding) and levees (raised river banks from deposited sediment) are both formed by the work of rivers.",
        },
        {
          q: "A delta is formed when:",
          options: [
            "A river enters a mountain and creates a waterfall",
            "A meander loop cuts off from the river",
            "As the river approaches the sea, it slows and breaks into distributaries, depositing sediment that accumulates at the mouths",
            "A glacier deposits moraines at its base",
          ],
          correct: 2,
          explain:
            "A delta forms as the river slows near the sea, breaks into distributaries, and the sediment deposited at all the mouths accumulates to form a delta.",
        },
        {
          q: [
            "Consider the following coastal landform sequence created by sea waves:",
            "I. Waves strike rocks → cracks develop → Sea caves",
            "II. Caves grow → only roof remains → Sea arches",
            "III. Arch roof erodes → only walls remain → Stacks",
            "IV. Sediment deposited along shore → Beach",
            "Which sequence is correctly ordered?",
          ],
          options: [
            "I → II → IV → III",
            "I → II → III, and IV separately (depositional)",
            "II → I → III → IV",
            "IV → III → II → I",
          ],
          correct: 1,
          explain:
            "The correct sequence for erosional features is: Sea caves → Sea arches → Stacks. Beach is a separate DEPOSITIONAL feature of sea waves, not part of the erosional sequence.",
        },
        {
          q: "Which of the following is a depositional feature of sea waves?",
          options: ["Sea cave", "Sea arch", "Stack", "Beach"],
          correct: 3,
          explain:
            "Beach is a DEPOSITIONAL feature — formed where sea waves deposit sediments along the shores. Sea caves, arches, and stacks are all EROSIONAL features.",
        },
        {
          q: "Glacial moraines are formed by:",
          options: [
            "The erosion of the glacier cutting deep hollows",
            "Deposition of material carried by the glacier (rocks, sand, silt)",
            "The melting of glaciers forming mountain lakes",
            "Wind depositing sand near glacial areas",
          ],
          correct: 1,
          explain:
            "Glacial moraines are DEPOSITIONAL features — the material (rocks, sand, silt) carried by a glacier gets deposited, forming moraines.",
        },
        {
          q: "Mushroom rocks are found in deserts and are caused by:",
          options: [
            "Rivers eroding softer rock underneath hard rock",
            "Wind eroding the lower section of rocks more than the upper part, creating a narrower base and wider top",
            "Glaciers carving out asymmetric hollows in rocks",
            "Sea waves undercutting coastal rocks",
          ],
          correct: 1,
          explain:
            "In deserts, wind erodes the lower section of rocks more than the upper, because it lifts sand only a certain height. This creates mushroom rocks with a narrower base and wider top.",
        },
        {
          q: "Large deposits of 'loess' — fine sand carried by wind over very long distances — are found in:",
          options: ["India", "USA", "China", "Australia"],
          correct: 2,
          explain:
            "Large deposits of loess are found in China — when fine, light sand grains are carried over very long distances by wind and deposited in large areas.",
        },
      ],
    },
  },
});
